/** User-visible copy for views — merged into src/strings.json */
export default {
  issues: {
    title: 'Site Audit',
    subtitlePrefix: 'Prioritized issues impacting crawlability, indexing, and rankings.',
    subtitleTotal: '{count} total {issuesWord} found.',
    issueWord: 'issue',
    issuesWord: 'issues',
    fixRecommendation: 'Fix Recommendation',
    issuesByCategory: 'Issues by category',
    issuesByCategoryHint: 'Reflects current search and category filter, not priority filter.',
    issuesByPriority: 'Issues by priority',
    issuesByPriorityHint: 'Same slice as category chart (search + category filter only).',
    allPriorities: 'All Priorities',
    allCategories: 'All Categories',
    noMatches: 'No issues match the current filters.',
    categoryOther: 'Other',
    priorityOrder: ['Critical', 'High', 'Medium', 'Low'],
  },
  redirects: {
    title: 'Redirects',
    subtitle: 'URLs that redirect to another location. From → To.',
    chartTitle: 'Redirects by status code',
    chartHint: 'How many redirect responses use each HTTP status',
    colFrom: 'From (requested URL)',
    colStatus: 'Status',
    colTo: 'To (final URL)',
    noSearchMatch: 'No redirects match your search.',
    noneFound: 'No redirects found.',
    datasetLabel: 'Redirects',
  },
  techStack: {
    title: 'Tech Detection',
    subtitle: 'Technologies detected across {count} analyzed pages.',
    techDetectedSuffix: 'technologies detected',
    cardDetected: 'Detected Technologies',
    cardHint: 'Number of pages where each technology was found',
    chartAxisPages: 'Pages',
    tooltipPages: ' Found on {count} page(s)',
    categoryOther: 'Other',
    noSearchMatch: 'No technologies match your search.',
    noData: 'No technology data. Run a crawl first.',
    breakdownTitle: 'Technology Breakdown',
    colTechnology: 'Technology',
    colCategory: 'Category',
    colPages: 'Pages',
    colSampleUrls: 'Sample URLs',
  },
  gallery: {
    title: 'Gallery',
    subtitle: 'Images discovered during the crawl: on-page assets, Open Graph, and Twitter images. Click any tile to enlarge.',
    filterSource: 'Source',
    filterAll: 'All',
    filterOnPage: 'On-page',
    filterOg: 'OG',
    filterTwitter: 'Twitter',
    bySourceType: 'By source type',
    grid: 'Grid',
    titleDense: 'Dense',
    titleBalanced: 'Balanced',
    titleLarge: 'Large',
    statUnique: 'Unique images',
    statShown: 'Shown (filtered)',
    helpBlurb:
      'Crawled pages with page_analysis.image_urls populate most tiles. OG and Twitter images are merged in when present. Use the header search to filter by page URL or image URL.',
    emptyNoImages:
      'No images found. Re-run the crawler with page analysis enabled so image URLs are captured per page.',
    emptyNoMatch: 'No images match your filters or search.',
    previewUnavailable: 'Preview unavailable',
    ariaImagePreview: 'Image preview',
    ariaClose: 'Close',
    foundOn: 'Found on',
    kindLabels: { content: 'On-page', og: 'Open Graph', twitter: 'Twitter / X' },
    wcBreakdownLabels: ['On-page', 'Open Graph', 'Twitter / X'],
  },
  network: {
    title: 'Internal Linking Map',
    subtitle: 'Physics-based graph of internal link structure. Red nodes indicate 4xx/5xx errors.',
    searchEmpty: 'No pages match your search.',
    legendOk: 'OK (2xx)',
    legendBroken: 'Broken (4xx/5xx)',
    legendLink: 'Internal Link',
    fullscreen: 'Full screen',
    exitFullscreen: 'Exit full screen',
    titleFullscreen: 'Full screen',
    titleExitFullscreen: 'Exit full screen',
    noEdges: 'No edge data available.',
  },
  charts: {
    title: 'Crawl Analytics',
    subtitle: 'Status codes, content types, outlinks, title length, and domain distribution.',
    statusDist: 'Status code distribution',
    statusHintPrefix: 'Crawl response codes',
    topMime: 'Top content-types',
    mimeByCount: 'By URL count',
    outlinksTitle: 'Outlinks per page',
    outlinksHint: 'Bucket distribution',
    titleLength: 'Title length (characters)',
    titleLengthHint: '51–100 is ideal for SEO',
    topDomains: 'Top domains discovered',
    topDomainsHint: 'By URL count (ranking)',
    perfDepthTitle: 'Performance & Depth Analytics',
    rtDistTitle: 'Response Time Distribution',
    rtP50: 'p50:',
    rtP75: 'p75:',
    rtP95: 'p95:',
    rtAria: 'Response time histogram',
    depthDistTitle: 'Page Depth Distribution',
    maxDepth: 'Max depth:',
    avgDepth: 'Avg depth:',
    depthAria: 'Depth distribution',
    bubbleTitle: 'PageRank vs Inlinks vs Word Count',
    bubbleHint: 'Bubble size = PageRank weight',
    bubbleAria: 'Bubble chart: inlinks vs word count',
    scatterTitle: 'Word Count vs Response Time',
    scatterHint: 'Each dot is one page',
    scatterAria: 'Scatter chart: word count vs response time',
    tooltipUrls: ' URLs',
    ariaStatusPrefix: 'Bar chart: status code distribution.',
    ariaNoStatus: 'No status data',
    ariaMime: 'Bar chart: top content types.',
    ariaOutlinks: 'Bar chart: outlinks distribution by bucket.',
    ariaTitleLen: 'Bar chart: title length distribution by character bucket.',
    ariaDomainsPrefix: 'Bar chart: top domains.',
  },
  content: {
    title: 'On-Page SEO',
    subtitlePrefix: 'Audit missing or duplicate titles, meta descriptions, and H1 tags.',
    subtitleIssues: '{count} total {word} detected.',
    issueWord: 'issue',
    issuesWord: 'issues',
    filters: [
      {
        key: 'missing_h1',
        label: 'Missing H1',
        guidance:
          'Every page should have exactly one H1 tag that clearly describes the page content for both users and search engines.',
      },
      {
        key: 'missing_title',
        label: 'Missing Title',
        guidance:
          'The <title> tag is a critical ranking signal. Missing titles result in poor click-through rates from search results.',
      },
      {
        key: 'multiple_h1',
        label: 'Multiple H1s',
        guidance:
          'Having more than one H1 dilutes your heading hierarchy. Consolidate to a single, keyword-rich H1 per page.',
      },
      {
        key: 'missing_meta_desc',
        label: 'Missing Meta Desc',
        guidance:
          'Meta descriptions influence click-through rates. Write a unique, compelling 120–160 character summary for each page.',
      },
      {
        key: 'meta_desc_short',
        label: 'Meta Desc Short',
        guidance:
          'Meta descriptions under ~120 characters leave wasted SERP real estate. Expand them to be more descriptive and persuasive.',
      },
      {
        key: 'meta_desc_long',
        label: 'Meta Desc Long',
        guidance:
          'Meta descriptions over ~160 characters get truncated in search results. Trim them down to the most impactful text.',
      },
      {
        key: 'thin_content',
        label: 'Thin Content',
        guidance:
          'Pages with very little text (under ~300 words) are often low-value to search engines. Expand or consolidate thin pages.',
      },
    ],
    dupClusters: 'Near-duplicate clusters',
    colCluster: 'Cluster',
    colRepresentative: 'Representative',
    colUrls: 'URLs',
    issuesByType: 'Issues by type',
    issuesByTypeHint: 'URL count per on-page issue category',
    emptyFilter: 'No URLs affected by this issue.',
    emptyGreat: 'Great job — nothing to fix here.',
    issueTableHint:
      "Rows are pages that match the selected issue. Swipe sideways on small screens if columns don't all fit.",
    showingSlice: 'Showing {from}–{to} of {total}',
    tablePage: 'Page',
    noTitle: 'No title',
    tableUrl: 'URL',
    tablePageTitle: 'Page Title',
    tableLength: 'Length',
    tableH1Count: 'H1 Count',
    tableChars: 'Chars',
    urlOne: 'URL',
    urlMany: 'URLs',
  },
  links: {
    title: 'Link Explorer',
    showingResults: 'Analyze discovered URLs. Showing',
    resultsSuffix: 'results.',
    explorerHint:
      'Each row is a page from this crawl. Scan by title and path; "Links in" counts internal links pointing here (in this crawl). Sort columns or open Inspect for full details.',
    noTitle: 'No title',
    filterAllPages: 'All pages',
    filterOrphans: 'Orphans (0 inlinks)',
    filterAllStatus: 'All Status Codes',
    status200: '200 OK',
    status404: '404 Not Found',
    status301: '301 Redirect',
    status302: '302 Redirect',
    filterAllRt: 'All Response Times',
    filterFast: 'Fast (<500ms)',
    filterSlow: 'Slow (>2s)',
    filterAllWc: 'All Word Counts',
    filterThin: 'Thin (<300)',
    filterMedium: 'Medium (300–1000)',
    filterLong: 'Long (1000+)',
    chartStatusTitle: 'All crawled URLs by status',
    chartStatusHint: 'Full link list (ignores table filters)',
    chartWcTitle: 'Word count bands',
    chartWcHint: 'Same buckets as the word-count filter',
    wcBands: ['Thin (<300)', 'Medium (300–999)', 'Long (1000+)', 'No / zero words'],
    thPage: 'Page',
    thStatus: 'Status',
    thLinksIn: 'Links in',
    thCrawlDepth: 'Crawl depth',
    thLoadTime: 'Load time',
    thWords: 'Words',
    thActions: 'Actions',
    inspect: 'Inspect',
    pageOf: 'Page',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    backToExplorer: 'Back to Link Explorer',
    urlInspector: 'URL Inspector',
    noUrlData: 'No data found for this URL.',
    urlOne: 'URL',
    urlMany: 'URLs',
  },
  security: {
    title: 'Security & Headers',
    subtitlePrefix: 'HTTP security headers, injection risk, open redirect, and vulnerability findings.',
    subtitleCount: '{count} finding{s} total.',
    findingsBySeverity: 'Findings by severity',
    findingsBySeverityHint: 'All findings in this report',
    findingsByType: 'Findings by type',
    findingsByTypeHint: 'Grouped by finding_type from the scanner',
    showAllSeverities: '← Show all severities',
    emptyTitle: 'No security findings detected',
    emptyFiltered: 'No findings match the current filters or search.',
    emptyNoScan: 'Run a crawl with security scanning enabled to see results here.',
    recommendation: 'Recommendation',
    findingTooltip: '{n} finding{s}',
  },
  lighthouse: {
    emptyTitle: 'Page Speed',
    emptySubtitle: 'Core Web Vitals and performance audit results.',
    emptyBodyBefore: 'No Lighthouse data yet. Run',
    emptyBodyAfter: 'and regenerate the report to see results here.',
    cmdSnippet: 'python -m src lighthouse',
    pageSpeedTitle: 'Page Speed',
    analysisSettings: 'Analysis settings',
    mode: 'Mode',
    device: 'Device',
    categories: 'Categories',
    categoriesFallback: 'Performance, Accessibility, Best practices, SEO, PWA',
    runsMedians: 'Runs:',
    mediansShown: '(medians shown)',
    runsMediansFull: 'Runs: {n} (medians shown)',
    generated: 'Generated:',
    multiCompare: 'Multi-page comparison',
    multiCompareHint: 'Click any row to view its detailed breakdown below. Sort by any column.',
    detailedView: 'Detailed view',
    noUrlMatch: 'No URLs match your search.',
    categoriesSection: 'Categories',
    scorePoor: '0–49 Poor',
    scoreNeeds: '50–89 Needs improvement',
    scoreGood: '90–100 Good',
    categoryScores: 'Category scores',
    categoryScoresHint: 'Ranked worst to best (Score 0–100)',
    noCategoryScores: 'No category scores',
    categoryScoresAriaPrefix: 'Category scores:',
    scoreAxisTitle: 'Score (0–100)',
    datasetScore: 'Score',
    metrics: 'Metrics',
    metricsHint: 'Hover any metric for threshold details. Bars fill relative to the good threshold. Medians from {runs} run(s).',
    quickWins: 'Quick Wins',
    quickWinsHint: 'Click any card to see why it matters, how to fix it, and the estimated impact.',
    summary: 'Summary',
    auditTables: 'Audit tables & previews',
    auditTablesHint: 'Expand any row for full Lighthouse detail rows (thumbnails, resource URLs, DOM nodes).',
    noAuditsSearch: 'No audits match your search.',
    diagnostics: 'Diagnostics & Fixes',
    diagnosticsHint:
      'Issues grouped by impact area. Click a group to expand. Click any issue for full detail and evidence.',
    allChecksPassed: 'No failing audits — all checks passed.',
    noDiagnosticsSearch: 'No diagnostics match your search.',
    defaultFix: 'See Lighthouse report for fix.',
  },
  overview: {
    mlErrors: 'ML enrichment reported {count} error{plural}',
    dashboard: 'Dashboard',
    subtitleSiteHealth: 'Site health summary for',
    crawlDone: 'Crawl completed.',
    crawlDoneSeconds: 'Crawl completed in {seconds}s.',
    totalUrls: 'Total URLs',
    avgOutlinks: 'Avg Outlinks / Page',
    successRate: 'Success Rate (2xx)',
    broken: 'Broken (4xx/5xx)',
    count4xx5xx: '{count4xx} 4xx, {count5xx} 5xx',
    missingH1s: 'Missing H1s',
    medianWordCount: 'Median Word Count',
    perPage2xx: 'per page (2xx HTML)',
    ogCoverage: 'OG Tag Coverage',
    ogPagesWith: 'pages with og:title',
    technologies: 'Technologies',
    techDetectedAcross: 'detected across site',
    responseP50: 'Response Time p50',
    p95Label: 'p95:',
    reportComparison: 'Report comparison',
    reportComparisonHint:
      'Differences vs the baseline report selected in the header. Uses compact fingerprints (title, meta, headings, word count, content length) — not a full HTML diff. New/removed URLs and pages whose primary text fingerprint changed between runs.',
    newUrls: 'New URLs',
    removedUrls: 'Removed URLs',
    contentChanged: 'Content changed',
    structureChanged: 'Structure changed',
    sampleNew: 'Sample new',
    sampleRemoved: 'Sample removed',
    sampleContentChanged: 'Sample content changed',
    keywordOpportunities: 'Keyword opportunities',
    keywordOpportunitiesHint:
      'On-site discovery from crawl copy (titles, headings, meta, slugs). Scores are heuristic — not Google search volume or difficulty.',
    quickWinsEase: 'Quick wins (ease proxy)',
    highEmphasis: 'High emphasis (frequency proxy)',
    contentIntelligence: 'Content intelligence',
    duplicateGroups: 'Duplicate groups',
    nearDuplicateGroups: 'Near-duplicate groups',
    anomalies: 'Anomalies',
    outliers: 'Outliers',
    parentTopics: 'Parent topics (semantic)',
    semanticGroups: 'Semantic groups',
    namedEntities: 'Named entities',
    pagesSampled: '{n} page(s) sampled',
    entitiesSitewide: 'entities sitewide',
    languagesSampled: 'Languages (sampled)',
    mixedLanguage: 'Mixed-language site detected',
    anomalyUrls: 'Anomaly URLs',
    thUrl: 'URL',
    thScore: 'Score',
    thReasons: 'Reasons',
    insightsGlance: 'Insights at a glance',
    insightsHint:
      'Distributions and coverage derived from this crawl: where content sits by length, how fast URLs responded, how deep the crawler reached, on-page metadata health, share-preview tags, and—when a Lighthouse run is attached—category scores.',
    contentDepth: 'Content depth (word count)',
    contentDepthHint:
      '2xx HTML pages by word-count bucket. Heavy left skew often means thin or template-heavy indexable URLs.',
    serverLatency: 'Server / fetch latency',
    serverLatencyHint:
      'All crawled URLs by response time. Tail in slower buckets flags pages to optimize or investigate.',
    crawlDepth: 'Crawl depth from start URL',
    crawlDepthHint:
      'How discovered URLs spread by hop count. A sharp drop after depth 1–2 is common; spikes at high depth may mean long chains or deep archives.',
    maxDepth: 'Max depth',
    avg: 'avg',
    titleMetaHealth: 'Title & meta description health',
    titleMetaHint:
      'Per-page checks across the crawl: missing, length outside recommended ranges, or within target bands (titles ~30–60 chars, descriptions ~70–160).',
    socialPreview: 'Social preview coverage',
    socialPreviewHint:
      'Share of 2xx HTML pages with Open Graph / Twitter signals. Low og:image hurts link previews on social and chat apps.',
    readingLevel: 'Reading level (estimated)',
    readingLevelHint:
      'Grade-level style buckets on 2xx pages. Use to sanity-check whether copy matches your audience.',
    topMime: 'Top MIME types',
    topMimeHint:
      'What the crawler actually fetched. Large non-HTML counts can mean assets, feeds, or mis-linked URLs in scope.',
    lhCategoryScores: 'Lighthouse category scores',
    lhCategoryHint:
      'From the attached Lighthouse summary (typically the audited landing or representative URL). Scores are 0–100; bars use the same good / needs work / poor coloring as elsewhere.',
    healthByCategory: 'Health by Category',
    noCategorySearch: 'No categories match your search.',
    noCategoryData: 'No category data.',
    scoreGood: 'Good',
    scoreNeeds: 'Needs Improvement',
    scoreCritical: 'Critical',
    statusBreakdown: 'Status breakdown',
    siteConfiguration: 'Site Configuration',
    robotsTxt: 'robots.txt:',
    sitemapXml: 'sitemap.xml:',
    sitemapValid: ' (valid)',
    sitemapInvalid: ' (invalid or unparsed)',
    recommendations: 'Recommendations',
    noRecSearch: 'No recommendations match your search.',
    topPagesTitle: 'Most important pages',
    topPagesHint:
      "From your crawl's internal link graph: importance is a PageRank-style score (relative to this site, not Google). Connections = edges touching this URL in the graph.",
    noTopSearch: 'No top pages match your search.',
    thRank: 'Rank',
    thPage: 'Page',
    thImportance: 'Importance',
    thConnections: 'Connections',
    noTitle: 'No title',
    noTopPagesData: 'No top pages data (crawl had no edges or outlinks).',
    chartTitleTags: 'Title tags',
    chartMetaDesc: 'Meta descriptions',
    titleMetaLabels: ['Missing', 'Too short', 'Too long', 'In range'],
    socialLabelsOg: 'og:title',
    socialLabelsTwitter: 'Twitter card',
    socialLabelsOgImage: 'og:image',
    wcBuckets: ['0-100', '101-300', '301-600', '601-1000', '1001-2000', '2001+'],
    rtBuckets: ['<200ms', '200-500ms', '500ms-1s', '1-2s', '>2s'],
    rlBuckets: ['Elementary (0-5)', 'Middle School (6-8)', 'High School (9-12)', 'College (13+)'],
    depthLabel: 'Depth {n}',
    chartPages: 'Pages',
    chartUrls: 'URLs',
    chartLighthouse: 'Lighthouse',
    chartCoverage: 'Coverage',
    groupedTitleMetaAria:
      'Grouped comparison of title tag and meta description length health across all crawled pages.',
    lighthouseCategoryLabels: {
      performance: 'Performance',
      accessibility: 'Accessibility',
      'best-practices': 'Best practices',
      seo: 'SEO',
      pwa: 'PWA',
    },
    tooltipCountBar: '{count} pages',
    tooltipGroupedBar: '{dataset}: {count} pages',
    socialTooltipHtml: '{label}: {pct}% of HTML pages',
    lhTooltipNoScore: 'No score',
    lhTooltipScore: '{score} / 100',
    anomalyUrlsTitle: 'Anomaly URLs ({count})',
    categoryScoreAria: '{name}: {band}, score {score}',
    depthSummaryLine: 'Max depth {maxDepth}, avg {avgDepth}',
    ariaWordCountIntro: 'Word count buckets for successful HTML pages:',
    ariaResponseTimeIntro: 'Response time buckets:',
    ariaDepthIntro: 'URLs by crawl depth from start URL:',
    ariaReadingIntro: 'Reading level (estimated) on 2xx pages:',
    ariaMimeIntro: 'Top content types:',
    ariaLighthouseIntro: 'Lighthouse category scores (0–100):',
    ariaSocialIntro: 'Social preview coverage on HTML pages:',
    statusAriaIntro: 'Status:',
  },
  contentAnalytics: {
    title: 'Content Insights',
    subtitle:
      'Word count, readability, content-to-HTML ratio, top keywords, social meta coverage, crawl health, and on-page flags.',
    meanWords: 'Mean Words',
    medianWords: 'Median Words',
    perPage: 'per page',
    ogCoverage: 'OG Coverage',
    ogTags: 'open graph tags',
    twitterCoverage: 'Twitter Coverage',
    twitterTags: 'twitter card tags',
    thinPages: 'Thin Pages',
    under300: 'under 300 words',
    i18nTitle: 'Internationalization (crawl)',
    pages2xx: '2xx pages',
    missingHtmlLang: 'Missing <html lang>',
    pagesHreflang: 'Pages with hreflang alternates',
    outboundDomains: 'Outbound link domains',
    thHost: 'Host',
    thLinks: 'Links',
    languageMix: 'Language mix',
    entityLabels: 'Entity labels',
    countAxis: 'Count',
    parentTopicsToken: 'Parent topics (token overlap)',
    thRepresentative: 'Representative',
    thClusterScore: 'Cluster score',
    thKeywords: 'Keywords',
    parentTopicsSemantic: 'Parent topics (semantic similarity)',
    crawlHealth: 'Crawl health & response times',
    urlsByStatus: 'URLs by HTTP status',
    totalCrawled: 'Total crawled:',
    returned2xx: 'returned 2xx',
    responseTimeDist: 'Response time distribution',
    pagesPerBand: 'Pages per latency band',
    onPageQuality: 'On-page quality & thin content',
    urlsByIssue: 'URLs flagged by issue type',
    pagesGoodRanges: 'Pages in “good” ranges',
    stackedInRange: 'In range / optimal',
    stackedNeeds: 'Needs attention',
    thinSignals: 'Thin content signals',
    thinUnder300: 'Under 300 words',
    thinSmallBody: 'Small HTML body',
    thinMatchSearch: '{shown} of {total} thin page{plural} match search',
    thinHaveLittle: '{count} page{plural} have very little content',
    noThinSearch: 'No thin pages match your search.',
    contentMetrics: 'Content Metrics',
    wordCountDist: 'Word Count Distribution',
    readingLevelDist: 'Reading Level Distribution',
    contentHtmlRatio: 'Content-to-HTML Ratio',
    topKeywords: 'Top 30 Keywords (Site-Wide)',
    noKeywordData: 'No keyword data',
    wordCountLadder: 'Word count ladder (min → max)',
    onPageSignals: 'On-Page SEO Signals',
    h1Dist: 'H1 Tag Distribution',
    titleTagQuality: 'Title Tag Length Quality',
    metaDescQuality: 'Meta Description Quality',
    socialMetaCoverage: 'Social Meta Coverage',
    ogProgress: 'Open Graph Coverage',
    twitterProgress: 'Twitter Card Coverage',
    socialOverview: 'Social Meta Coverage Overview',
    datasetHasTag: 'Has Tag',
    datasetMissing: 'Missing',
    ogImageCov: 'OG Image Coverage',
    hasOgImage: 'Has OG Image',
    missingOgImage: 'Missing OG Image',
    missingOgTags: 'Missing Open Graph Tags',
    missingTwitterTags: 'Missing Twitter Card Tags',
    socialAllGood:
      'All pages have social meta tags, or no data available yet. Run a crawl to populate.',
    siteArchitecture: 'Site Architecture',
    crawlDepthDist: 'Crawl Depth Distribution',
    maxDepth: 'Max depth:',
    avgDepth: 'avg:',
    wordCountPercentiles: 'Word Count Percentiles',
    wcMin: 'Min',
    wcP25: '25th Percentile (P25)',
    wcP50: 'Median (P50)',
    wcMean: 'Mean (Avg)',
    wcP75: '75th Percentile (P75)',
    wcMax: 'Max',
    h1Labels: ['No H1', 'One H1', 'Multiple H1s'],
    titleQualLabels: ['Missing', 'Too Short (<30)', 'Optimal (30–60)', 'Too Long (>60)'],
    metaQualLabels: ['Missing', 'Too Short (<70)', 'Optimal (70–160)', 'Too Long (>160)'],
    status2xx: '2xx OK',
    status3xx: '3xx Redirect',
    status4xx: '4xx Client error',
    status5xx: '5xx Server error',
    statusErr: 'Error / blocked',
    openGraph: 'Open Graph',
    twitterCard: 'Twitter Card',
    ogImage: 'OG Image',
    seoTitle: 'Title length',
    seoMeta: 'Meta description',
    seoH1: 'H1 count',
    noUrlSearch: 'No URLs match your search.',
    thinPagesView: 'View {count} thin page{s}',
    thThinHash: '#',
    thThinUrl: 'URL',
    thThinWords: 'Words',
    chartTooltipCount: '{n} pages',
    chartTooltipDoughnut: '{label}: {n} pages',
    chartTooltipGrouped: '{dataset}: {n} pages',
    chartTooltipPercent: '{dataset}: {pct}%',
    wcPercLabels: ['Min', 'P25', 'Median', 'Mean', 'P75', 'Max'],
    thPages: 'Pages',
    contentIssueKeys: [
      { key: 'missing_h1', label: 'Missing H1' },
      { key: 'missing_title', label: 'Missing title' },
      { key: 'multiple_h1', label: 'Multiple H1s' },
      { key: 'missing_meta_desc', label: 'Missing meta desc' },
      { key: 'meta_desc_short', label: 'Meta too short' },
      { key: 'meta_desc_long', label: 'Meta too long' },
      { key: 'thin_content', label: 'Thin (body chars)' },
    ],
  },
  sqlPlayground: {
    title: 'Audit database',
    subtitle:
      'Explore the crawl SQLite file like a small SQL lab: schema browser, guided examples, syntax-highlighted editor, and results below. Everything runs in your browser.',
    run: 'Run',
    reloadReport: 'Reload report.db',
    loadingReport: 'Loading report…',
    loadFailedHttp: 'Could not load report:',
    downloadDb: 'Download copy (.sqlite)',
    openLocalFile: 'Open local .db file',
    pickFileAccept: '.db,.sqlite,application/octet-stream',
    hintModEnter: 'Ctrl+Enter · ⌘+Enter',
    emptySql: 'Enter some SQL to run.',
    executedNoRows: 'Statement completed (no result rows).',
    rowsAffected: 'Rows changed by last write:',
    resultSetTitle: 'Result set {n}',
    resultSetsCount: '{count} result sets',
    engineFailed: 'Could not load SQLite engine',
    panelTitle: 'Sidebar',
    tabSchema: 'Schema',
    tabExamples: 'Examples',
    panelLoading: 'Loading audit database…',
    panelNoDb: 'No database loaded yet.',
    panelEmpty: 'No user tables in this file.',
    schemaTruncated: 'List truncated. Query sqlite_master for the full list.',
    pkBadge: 'PK',
    rowCountUnknown: '—',
    rowsLabel: '{count} rows',
    schemaTableHint: 'Table — click for SELECT *',
    schemaColHint: 'Column — inserts at cursor',
    localLoadError: 'Could not read that file as SQLite.',
    sqlQueryLabel: 'SQL query',
    resultsLabel: 'Results',
    resultsEmptyTitle: 'Run a query',
    resultsEmptyHint: 'Results from SELECT statements appear here.',
    rowsBadge: '{count} rows',
    resultsExplorerHint:
      'Sticky header · drag column edges to resize · double-click a handle to reset widths · hover cells for full text.',
    resizeColumnAria: 'Resize column {column}',
    resetColumnWidthsHint: 'Double-click to reset all column widths',
    resultsUiTruncated:
      'Only the first {shown} rows are shown here ({total} returned). Add LIMIT to your query for a smaller grid.',
    statusEngine: 'SQLite engine…',
    statusDb: 'Loading report.db…',
    statusReady: 'Ready',
    statusError: 'Error',
    examplesSearchPlaceholder: 'Search examples…',
    diffAll: 'All levels',
    diffEasy: 'Easy',
    diffMedium: 'Medium',
    diffHard: 'Hard',
    examplesEmpty: 'No examples match this database or filters.',
    insertSolution: 'Insert solution',
    closeChallenge: 'Dismiss',
    challengeStarter: '-- Example: {title}\n\n',
  },
  modelLoader: {
    title: 'LLM lab',
    subtitle: 'Chat with your chosen model. Open Settings to pick provider, model name, API keys, and advanced tools.',
    toolSelectLabel: 'Tool or provider',
    toolOptionHF: 'Hugging Face (browser)',
    settings: {
      openButton: 'Settings',
      title: 'Settings',
      closeAria: 'Close settings',
      tablistAria: 'Settings sections',
      tabs: {
        model: 'Model & API',
        apiTest: 'Quick test',
        browser: 'Browser HF',
        curl: 'Curl',
      },
      sectionModel: 'Model & connection',
      sectionApiTest: 'Quick API test',
      sectionBrowser: 'Browser (Transformers.js)',
      sectionCurl: 'Curl import',
    },
    browser: {
      intro:
        'Runs entirely in your browser via Transformers.js. Use ONNX-compatible Hub models (often the Xenova organization).',
      hfModelsLink: 'Browse Transformers.js–compatible models on Hugging Face',
      taskLabel: 'Pipeline task',
      modelIdLabel: 'Model id',
      modelIdPlaceholder: 'e.g. Xenova/all-MiniLM-L6-v2',
      modelRequired: 'Enter a model id.',
      loadBtn: 'Load model',
      loading: 'Loading…',
      smokeBtn: 'Run smoke test',
      progressLabel: 'Downloading…',
      readyHint: 'Pipeline ready. You can run a smoke test or switch models.',
      onnxHint:
        'If this persists, try another model, clear site data, or reload. Large models can exhaust WASM memory.',
      smokeEmbedText: 'hello world',
      smokeEmbedResult: 'Embedding dim: {dim}. First values: {preview}',
      smokeGenText: 'Once upon a time',
      smokeGenResult: '{text}',
    },
    api: {
      intro: 'Send a test prompt using your API key. Keys are not sent to this app’s servers—requests go from your browser to the provider.',
      keyWarning:
        'Never share API keys or commit them to git. For production, use a backend proxy instead of exposing keys in the browser.',
      corsWarning:
        'Some providers block browser requests (CORS). If a request fails with a network or CORS error, use Copy curl and run the command in your terminal, or use a proxy.',
      presetGemini: 'Google Gemini',
      presetOpenAi: 'OpenAI-compatible',
      baseUrlLabel: 'Base URL',
      modelLabel: 'Model',
      apiKeyLabel: 'API key',
      apiKeyPlaceholder: 'Paste key here',
      promptLabel: 'Test prompt',
      rememberSession: 'Remember keys for this browser tab session (sessionStorage)',
      sendBtn: 'Send test',
      copyCurlBtn: 'Copy curl',
      copied: 'Copied',
      corsDetail:
        'This is often a CORS restriction: the provider does not allow browser origins to call the API directly. Use Copy curl to run the same request from your machine, or route traffic through a server you control.',
      keyRequired: 'Enter an API key.',
      copyFailed: 'Could not copy to clipboard.',
    },
    chat: {
      intro:
        'A ChatGPT-style thread: multi-turn conversation with Google Gemini or an OpenAI-compatible API. Uses the same API key and model fields as the API tab.',
      systemLabel: 'System instructions (optional)',
      systemPlaceholder: 'e.g. You are a concise coding assistant.',
      emptyHint: 'Send a message to start the conversation.',
      openSettingsHint: 'Use Settings (top right) to choose Gemini or OpenAI, set the model name, and paste your API key.',
      composerPlaceholder: 'Message…',
      send: 'Send',
      clear: 'Clear chat',
      thinking: 'Thinking…',
      attachImages: 'Add images',
      removeAttachmentAria: 'Remove attachment',
      imageMarkdownNotice:
        'Markdown in replies can include images from HTTPS URLs. Attach images here to send them to vision-capable models.',
      footerNote: 'Responses are generated by the model and may be inaccurate. Verify important facts.',
      curlModeHint:
        'Curl mode: each Send merges the chat thread into your JSON body. OpenAI-style: messages[] is replaced with system (your Settings text + optional DB schema) plus the conversation. Gemini generateContent: contents[] is filled and systemInstruction is set or merged with your template. For manual curl in a terminal, put the schema in the system message: OpenAI: messages[0] = { role: "system", content: "<paste schema>" }; Gemini: "systemInstruction": { "parts": [{ "text": "<paste schema>" }] }. Use Copy schema below to grab the block.',
      curlChatUrlRequired: 'Set a request URL in Settings → Curl before sending.',
      curlChatBodyInvalid:
        'Curl body must be valid JSON for chat. Use an OpenAI-compatible object (e.g. include model and any other fields your API needs); messages will be filled automatically.',
      curlChatMethodPost: 'Chat over Curl requires POST, PUT, or PATCH so a JSON body can be sent.',
      dbPanelTitle: 'Audit database (SQLite)',
      dbLoading: 'Loading database…',
      dbLoadedFrom: 'Loaded: {label}',
      dbReload: 'Reload from app URL',
      dbPickFile: 'Open local file…',
      dbSettingsHint:
        'When the audit DB is loaded, schema is added to the model context. Tool calling (executing read-only SQL, etc.) runs only if you choose Google Gemini or OpenAI in the lab tool dropdown—not Curl. Curl mode still merges schema into system / systemInstruction for each Send.',
      curlToolsExplainer:
        'With a loaded audit DB: Curl + Gemini uses the same REST tool loop and `generativelanguage.googleapis.com` as your template (model from Settings). Curl + OpenAI uses your Settings base URL and key. Put your API key in Settings or in Curl headers (X-goog-api-key / Authorization: Bearer).',
      curlToolsGeminiKeyRequired:
        'For tools with Curl: add your Gemini API key under Settings → Model & API, or X-goog-api-key in the Curl tab headers.',
      curlToolsOpenAiKeyRequired:
        'For tools with Curl: add your OpenAI API key under Settings → Model & API, or Authorization: Bearer … in the Curl headers.',
      curlDbToolsHint:
        'A database is loaded: each Send appends the schema to system instructions (OpenAI system message or Gemini systemInstruction). If your curl body already defines systemInstruction, the app merges the schema after your text. For a shell curl, use Copy schema and paste into system content as shown in the curl hint above.',
      dbCopySchema: 'Copy schema',
      dbCopySchemaTitle: 'Copy markdown + JSON schema for pasting into a manual curl request body',
    },
    curl: {
      intro:
        'Paste a curl command to fill the fields below. Parsing is best-effort (quotes and common flags). Then edit and Send—same CORS limits apply as in the API tab. Use “Load Gemini REST template” for `generativelanguage.googleapis.com/.../models/MODEL:generateContent` with `X-goog-api-key`, or “Load OpenAI Chat template” for `…/v1/chat/completions` with `Authorization: Bearer`.',
      pasteLabel: 'curl command',
      pastePlaceholder:
        'curl -X POST "https://api.openai.com/v1/chat/completions" -H "Content-Type: application/json" -H "Authorization: Bearer YOUR_KEY" -d \'{"model":"gpt-4o-mini","messages":[{"role":"user","content":"Hi"}]}\'',
      parseBtn: 'Parse into fields',
      geminiTemplateBtn: 'Load Gemini REST template',
      geminiTemplateHint:
        'Sets URL, POST, headers, and a sample multi-turn `contents` array with `generationConfig.responseMimeType` for JSON. If the body is `{}` or missing `contents`, Send fills a placeholder turn. Chat with Curl transport still merges the full thread from the composer.',
      openaiTemplateBtn: 'Load OpenAI Chat template',
      openaiTemplateHint:
        'Sets URL to your Settings base + `/chat/completions`, POST, optional Bearer header, and a sample `messages` array with `response_format` JSON mode and `temperature`.',
      methodLabel: 'Method',
      urlLabel: 'URL',
      headersLabel: 'Headers (one Name: value per line)',
      headersPlaceholder:
        'Content-Type: application/json\nX-goog-api-key: …\n\n(OpenAI-compatible: Authorization: Bearer …)',
      bodyLabel: 'Body',
      sendBtn: 'Send request',
      corsHint:
        'If you see a CORS or network error, the target host may forbid browser calls. Run the equivalent curl in a terminal or use a proxy.',
      statusPrefix: 'Status:',
    },
  },
};
