/** User-visible copy for views — merged into src/strings.json */
export default {
  issues: {
    title: 'Site Audit',
    subtitlePrefix: 'Prioritized issues impacting crawlability, indexing, and rankings.',
    subtitleTotal: '{count} total {issuesWord} found.',
    issueWord: 'issue',
    issuesWord: 'issues',
    fixRecommendation: 'Fix Recommendation',
    issuesByCategory: 'Issues by category',
    issuesByCategoryHint: 'Reflects current search and category filter, not priority filter.',
    issuesByPriority: 'Issues by priority',
    issuesByPriorityHint: 'Same slice as category chart (search + category filter only).',
    allPriorities: 'All Priorities',
    allCategories: 'All Categories',
    noMatches: 'No issues match the current filters.',
    categoryOther: 'Other',
    priorityOrder: ['Critical', 'High', 'Medium', 'Low'],
  },
  redirects: {
    title: 'Redirects',
    subtitle: 'URLs that redirect to another location. From → To.',
    chartTitle: 'Redirects by status code',
    chartHint: 'How many redirect responses use each HTTP status',
    colFrom: 'From (requested URL)',
    colStatus: 'Status',
    colTo: 'To (final URL)',
    noSearchMatch: 'No redirects match your search.',
    noneFound: 'No redirects found.',
    datasetLabel: 'Redirects',
  },
  techStack: {
    title: 'Tech Detection',
    subtitle: 'Technologies detected across {count} analyzed pages.',
    techDetectedSuffix: 'technologies detected',
    cardDetected: 'Detected Technologies',
    cardHint: 'Number of pages where each technology was found',
    chartAxisPages: 'Pages',
    tooltipPages: ' Found on {count} page(s)',
    categoryOther: 'Other',
    noSearchMatch: 'No technologies match your search.',
    noData: 'No technology data. Run a crawl first.',
    breakdownTitle: 'Technology Breakdown',
    colTechnology: 'Technology',
    colCategory: 'Category',
    colPages: 'Pages',
    colSampleUrls: 'Sample URLs',
  },
  gallery: {
    title: 'Gallery',
    subtitle: 'Images discovered during the crawl: on-page assets, Open Graph, and Twitter images. Click any tile to enlarge.',
    filterSource: 'Source',
    filterAll: 'All',
    filterOnPage: 'On-page',
    filterOg: 'OG',
    filterTwitter: 'Twitter',
    bySourceType: 'By source type',
    grid: 'Grid',
    titleDense: 'Dense',
    titleBalanced: 'Balanced',
    titleLarge: 'Large',
    statUnique: 'Unique images',
    statShown: 'Shown (filtered)',
    helpBlurb:
      'Crawled pages with page_analysis.image_urls populate most tiles. OG and Twitter images are merged in when present. Use the header search to filter by page URL or image URL.',
    emptyNoImages:
      'No images found. Re-run the crawler with page analysis enabled so image URLs are captured per page.',
    emptyNoMatch: 'No images match your filters or search.',
    previewUnavailable: 'Preview unavailable',
    ariaImagePreview: 'Image preview',
    ariaClose: 'Close',
    foundOn: 'Found on',
    kindLabels: { content: 'On-page', og: 'Open Graph', twitter: 'Twitter / X' },
    wcBreakdownLabels: ['On-page', 'Open Graph', 'Twitter / X'],
  },
  network: {
    title: 'Internal Linking Map',
    subtitle: 'Physics-based graph of internal link structure. Red nodes indicate 4xx/5xx errors.',
    searchEmpty: 'No pages match your search.',
    legendOk: 'OK (2xx)',
    legendBroken: 'Broken (4xx/5xx)',
    legendLink: 'Internal Link',
    fullscreen: 'Full screen',
    exitFullscreen: 'Exit full screen',
    titleFullscreen: 'Full screen',
    titleExitFullscreen: 'Exit full screen',
    noEdges: 'No edge data available.',
  },
  charts: {
    title: 'Crawl Analytics',
    subtitle: 'Status codes, content types, outlinks, title length, and domain distribution.',
    statusDist: 'Status code distribution',
    statusHintPrefix: 'Crawl response codes',
    topMime: 'Top content-types',
    mimeByCount: 'By URL count',
    outlinksTitle: 'Outlinks per page',
    outlinksHint: 'Bucket distribution',
    titleLength: 'Title length (characters)',
    titleLengthHint: '51–100 is ideal for SEO',
    topDomains: 'Top domains discovered',
    topDomainsHint: 'By URL count (ranking)',
    perfDepthTitle: 'Performance & Depth Analytics',
    rtDistTitle: 'Response Time Distribution',
    rtP50: 'p50:',
    rtP75: 'p75:',
    rtP95: 'p95:',
    rtAria: 'Response time histogram',
    depthDistTitle: 'Page Depth Distribution',
    maxDepth: 'Max depth:',
    avgDepth: 'Avg depth:',
    depthAria: 'Depth distribution',
    bubbleTitle: 'PageRank vs Inlinks vs Word Count',
    bubbleHint: 'Bubble size = PageRank weight',
    bubbleAria: 'Bubble chart: inlinks vs word count',
    scatterTitle: 'Word Count vs Response Time',
    scatterHint: 'Each dot is one page',
    scatterAria: 'Scatter chart: word count vs response time',
    tooltipUrls: ' URLs',
    ariaStatusPrefix: 'Bar chart: status code distribution.',
    ariaNoStatus: 'No status data',
    ariaMime: 'Bar chart: top content types.',
    ariaOutlinks: 'Bar chart: outlinks distribution by bucket.',
    ariaTitleLen: 'Bar chart: title length distribution by character bucket.',
    ariaDomainsPrefix: 'Bar chart: top domains.',
  },
  content: {
    title: 'On-Page SEO',
    subtitlePrefix: 'Audit missing or duplicate titles, meta descriptions, and H1 tags.',
    subtitleIssues: '{count} total {word} detected.',
    issueWord: 'issue',
    issuesWord: 'issues',
    filters: [
      {
        key: 'missing_h1',
        label: 'Missing H1',
        guidance:
          'Every page should have exactly one H1 tag that clearly describes the page content for both users and search engines.',
      },
      {
        key: 'missing_title',
        label: 'Missing Title',
        guidance:
          'The <title> tag is a critical ranking signal. Missing titles result in poor click-through rates from search results.',
      },
      {
        key: 'multiple_h1',
        label: 'Multiple H1s',
        guidance:
          'Having more than one H1 dilutes your heading hierarchy. Consolidate to a single, keyword-rich H1 per page.',
      },
      {
        key: 'missing_meta_desc',
        label: 'Missing Meta Desc',
        guidance:
          'Meta descriptions influence click-through rates. Write a unique, compelling 120–160 character summary for each page.',
      },
      {
        key: 'meta_desc_short',
        label: 'Meta Desc Short',
        guidance:
          'Meta descriptions under ~120 characters leave wasted SERP real estate. Expand them to be more descriptive and persuasive.',
      },
      {
        key: 'meta_desc_long',
        label: 'Meta Desc Long',
        guidance:
          'Meta descriptions over ~160 characters get truncated in search results. Trim them down to the most impactful text.',
      },
      {
        key: 'thin_content',
        label: 'Thin Content',
        guidance:
          'Pages with very little text (under ~300 words) are often low-value to search engines. Expand or consolidate thin pages.',
      },
    ],
    dupClusters: 'Near-duplicate clusters',
    colCluster: 'Cluster',
    colRepresentative: 'Representative',
    colUrls: 'URLs',
    issuesByType: 'Issues by type',
    issuesByTypeHint: 'URL count per on-page issue category',
    emptyFilter: 'No URLs affected by this issue.',
    emptyGreat: 'Great job — nothing to fix here.',
    issueTableHint:
      "Rows are pages that match the selected issue. Swipe sideways on small screens if columns don't all fit.",
    showingSlice: 'Showing {from}–{to} of {total}',
    tablePage: 'Page',
    noTitle: 'No title',
    tableUrl: 'URL',
    tablePageTitle: 'Page Title',
    tableLength: 'Length',
    tableH1Count: 'H1 Count',
    tableChars: 'Chars',
    urlOne: 'URL',
    urlMany: 'URLs',
  },
  links: {
    title: 'Link Explorer',
    showingResults: 'Analyze discovered URLs. Showing',
    resultsSuffix: 'results.',
    explorerHint:
      'Each row is a page from this crawl. Scan by title and path; "Links in" counts internal links pointing here (in this crawl). Sort columns or open Inspect for full details.',
    noTitle: 'No title',
    filterAllPages: 'All pages',
    filterOrphans: 'Orphans (0 inlinks)',
    filterAllStatus: 'All Status Codes',
    status200: '200 OK',
    status404: '404 Not Found',
    status301: '301 Redirect',
    status302: '302 Redirect',
    filterAllRt: 'All Response Times',
    filterFast: 'Fast (<500ms)',
    filterSlow: 'Slow (>2s)',
    filterAllWc: 'All Word Counts',
    filterThin: 'Thin (<300)',
    filterMedium: 'Medium (300–1000)',
    filterLong: 'Long (1000+)',
    chartStatusTitle: 'All crawled URLs by status',
    chartStatusHint: 'Full link list (ignores table filters)',
    chartWcTitle: 'Word count bands',
    chartWcHint: 'Same buckets as the word-count filter',
    wcBands: ['Thin (<300)', 'Medium (300–999)', 'Long (1000+)', 'No / zero words'],
    thPage: 'Page',
    thStatus: 'Status',
    thLinksIn: 'Links in',
    thCrawlDepth: 'Crawl depth',
    thLoadTime: 'Load time',
    thWords: 'Words',
    thActions: 'Actions',
    inspect: 'Inspect',
    pageOf: 'Page',
    of: 'of',
    previous: 'Previous',
    next: 'Next',
    backToExplorer: 'Back to Link Explorer',
    urlInspector: 'URL Inspector',
    noUrlData: 'No data found for this URL.',
    urlOne: 'URL',
    urlMany: 'URLs',
  },
  security: {
    title: 'Security & Headers',
    subtitlePrefix: 'HTTP security headers, injection risk, open redirect, and vulnerability findings.',
    subtitleCount: '{count} finding{s} total.',
    findingsBySeverity: 'Findings by severity',
    findingsBySeverityHint: 'All findings in this report',
    findingsByType: 'Findings by type',
    findingsByTypeHint: 'Grouped by finding_type from the scanner',
    showAllSeverities: '← Show all severities',
    emptyTitle: 'No security findings detected',
    emptyFiltered: 'No findings match the current filters or search.',
    emptyNoScan: 'Run a crawl with security scanning enabled to see results here.',
    recommendation: 'Recommendation',
    findingTooltip: '{n} finding{s}',
  },
  lighthouse: {
    emptyTitle: 'Page Speed',
    emptySubtitle: 'Core Web Vitals and performance audit results.',
    emptyBodyBefore: 'No Lighthouse data yet. Run',
    emptyBodyAfter: 'and regenerate the report to see results here.',
    cmdSnippet: 'python -m src lighthouse',
    pageSpeedTitle: 'Page Speed',
    analysisSettings: 'Analysis settings',
    mode: 'Mode',
    device: 'Device',
    categories: 'Categories',
    categoriesFallback: 'Performance, Accessibility, Best practices, SEO, PWA',
    runsMedians: 'Runs:',
    mediansShown: '(medians shown)',
    runsMediansFull: 'Runs: {n} (medians shown)',
    generated: 'Generated:',
    multiCompare: 'Multi-page comparison',
    multiCompareHint: 'Click any row to view its detailed breakdown below. Sort by any column.',
    detailedView: 'Detailed view',
    noUrlMatch: 'No URLs match your search.',
    categoriesSection: 'Categories',
    scorePoor: '0–49 Poor',
    scoreNeeds: '50–89 Needs improvement',
    scoreGood: '90–100 Good',
    categoryScores: 'Category scores',
    categoryScoresHint: 'Ranked worst to best (Score 0–100)',
    noCategoryScores: 'No category scores',
    categoryScoresAriaPrefix: 'Category scores:',
    scoreAxisTitle: 'Score (0–100)',
    datasetScore: 'Score',
    metrics: 'Metrics',
    metricsHint: 'Hover any metric for threshold details. Bars fill relative to the good threshold. Medians from {runs} run(s).',
    quickWins: 'Quick Wins',
    quickWinsHint: 'Click any card to see why it matters, how to fix it, and the estimated impact.',
    summary: 'Summary',
    auditTables: 'Audit tables & previews',
    auditTablesHint: 'Expand any row for full Lighthouse detail rows (thumbnails, resource URLs, DOM nodes).',
    noAuditsSearch: 'No audits match your search.',
    diagnostics: 'Diagnostics & Fixes',
    diagnosticsHint:
      'Issues grouped by impact area. Click a group to expand. Click any issue for full detail and evidence.',
    allChecksPassed: 'No failing audits — all checks passed.',
    noDiagnosticsSearch: 'No diagnostics match your search.',
    defaultFix: 'See Lighthouse report for fix.',
  },
  overview: {
    mlErrors: 'ML enrichment reported {count} error{plural}',
    dashboard: 'Dashboard',
    subtitleSiteHealth: 'Site health summary for',
    crawlDone: 'Crawl completed.',
    crawlDoneSeconds: 'Crawl completed in {seconds}s.',
    totalUrls: 'Total URLs',
    avgOutlinks: 'Avg Outlinks / Page',
    successRate: 'Success Rate (2xx)',
    broken: 'Broken (4xx/5xx)',
    count4xx5xx: '{count4xx} 4xx, {count5xx} 5xx',
    missingH1s: 'Missing H1s',
    medianWordCount: 'Median Word Count',
    perPage2xx: 'per page (2xx HTML)',
    ogCoverage: 'OG Tag Coverage',
    ogPagesWith: 'pages with og:title',
    technologies: 'Technologies',
    techDetectedAcross: 'detected across site',
    responseP50: 'Response Time p50',
    p95Label: 'p95:',
    reportComparison: 'Report comparison',
    reportComparisonHint:
      'Differences vs the baseline report selected in the header. Uses compact fingerprints (title, meta, headings, word count, content length) — not a full HTML diff. New/removed URLs and pages whose primary text fingerprint changed between runs.',
    newUrls: 'New URLs',
    removedUrls: 'Removed URLs',
    contentChanged: 'Content changed',
    structureChanged: 'Structure changed',
    sampleNew: 'Sample new',
    sampleRemoved: 'Sample removed',
    sampleContentChanged: 'Sample content changed',
    keywordOpportunities: 'Keyword opportunities',
    keywordOpportunitiesHint:
      'On-site discovery from crawl copy (titles, headings, meta, slugs). Scores are heuristic — not Google search volume or difficulty.',
    quickWinsEase: 'Quick wins (ease proxy)',
    highEmphasis: 'High emphasis (frequency proxy)',
    contentIntelligence: 'Content intelligence',
    duplicateGroups: 'Duplicate groups',
    nearDuplicateGroups: 'Near-duplicate groups',
    anomalies: 'Anomalies',
    outliers: 'Outliers',
    parentTopics: 'Parent topics (semantic)',
    semanticGroups: 'Semantic groups',
    namedEntities: 'Named entities',
    pagesSampled: '{n} page(s) sampled',
    entitiesSitewide: 'entities sitewide',
    languagesSampled: 'Languages (sampled)',
    mixedLanguage: 'Mixed-language site detected',
    anomalyUrls: 'Anomaly URLs',
    thUrl: 'URL',
    thScore: 'Score',
    thReasons: 'Reasons',
    insightsGlance: 'Insights at a glance',
    insightsHint:
      'Distributions and coverage derived from this crawl: where content sits by length, how fast URLs responded, how deep the crawler reached, on-page metadata health, share-preview tags, and—when a Lighthouse run is attached—category scores.',
    contentDepth: 'Content depth (word count)',
    contentDepthHint:
      '2xx HTML pages by word-count bucket. Heavy left skew often means thin or template-heavy indexable URLs.',
    serverLatency: 'Server / fetch latency',
    serverLatencyHint:
      'All crawled URLs by response time. Tail in slower buckets flags pages to optimize or investigate.',
    crawlDepth: 'Crawl depth from start URL',
    crawlDepthHint:
      'How discovered URLs spread by hop count. A sharp drop after depth 1–2 is common; spikes at high depth may mean long chains or deep archives.',
    maxDepth: 'Max depth',
    avg: 'avg',
    titleMetaHealth: 'Title & meta description health',
    titleMetaHint:
      'Per-page checks across the crawl: missing, length outside recommended ranges, or within target bands (titles ~30–60 chars, descriptions ~70–160).',
    socialPreview: 'Social preview coverage',
    socialPreviewHint:
      'Share of 2xx HTML pages with Open Graph / Twitter signals. Low og:image hurts link previews on social and chat apps.',
    readingLevel: 'Reading level (estimated)',
    readingLevelHint:
      'Grade-level style buckets on 2xx pages. Use to sanity-check whether copy matches your audience.',
    topMime: 'Top MIME types',
    topMimeHint:
      'What the crawler actually fetched. Large non-HTML counts can mean assets, feeds, or mis-linked URLs in scope.',
    lhCategoryScores: 'Lighthouse category scores',
    lhCategoryHint:
      'From the attached Lighthouse summary (typically the audited landing or representative URL). Scores are 0–100; bars use the same good / needs work / poor coloring as elsewhere.',
    healthByCategory: 'Health by Category',
    noCategorySearch: 'No categories match your search.',
    noCategoryData: 'No category data.',
    scoreGood: 'Good',
    scoreNeeds: 'Needs Improvement',
    scoreCritical: 'Critical',
    statusBreakdown: 'Status breakdown',
    siteConfiguration: 'Site Configuration',
    robotsTxt: 'robots.txt:',
    sitemapXml: 'sitemap.xml:',
    sitemapValid: ' (valid)',
    sitemapInvalid: ' (invalid or unparsed)',
    recommendations: 'Recommendations',
    noRecSearch: 'No recommendations match your search.',
    topPagesTitle: 'Most important pages',
    topPagesHint:
      "From your crawl's internal link graph: importance is a PageRank-style score (relative to this site, not Google). Connections = edges touching this URL in the graph.",
    noTopSearch: 'No top pages match your search.',
    thRank: 'Rank',
    thPage: 'Page',
    thImportance: 'Importance',
    thConnections: 'Connections',
    noTitle: 'No title',
    noTopPagesData: 'No top pages data (crawl had no edges or outlinks).',
    chartTitleTags: 'Title tags',
    chartMetaDesc: 'Meta descriptions',
    titleMetaLabels: ['Missing', 'Too short', 'Too long', 'In range'],
    socialLabelsOg: 'og:title',
    socialLabelsTwitter: 'Twitter card',
    socialLabelsOgImage: 'og:image',
    wcBuckets: ['0-100', '101-300', '301-600', '601-1000', '1001-2000', '2001+'],
    rtBuckets: ['<200ms', '200-500ms', '500ms-1s', '1-2s', '>2s'],
    rlBuckets: ['Elementary (0-5)', 'Middle School (6-8)', 'High School (9-12)', 'College (13+)'],
    depthLabel: 'Depth {n}',
    chartPages: 'Pages',
    chartUrls: 'URLs',
    chartLighthouse: 'Lighthouse',
    chartCoverage: 'Coverage',
    groupedTitleMetaAria:
      'Grouped comparison of title tag and meta description length health across all crawled pages.',
    lighthouseCategoryLabels: {
      performance: 'Performance',
      accessibility: 'Accessibility',
      'best-practices': 'Best practices',
      seo: 'SEO',
      pwa: 'PWA',
    },
    tooltipCountBar: '{count} pages',
    tooltipGroupedBar: '{dataset}: {count} pages',
    socialTooltipHtml: '{label}: {pct}% of HTML pages',
    lhTooltipNoScore: 'No score',
    lhTooltipScore: '{score} / 100',
    anomalyUrlsTitle: 'Anomaly URLs ({count})',
    categoryScoreAria: '{name}: {band}, score {score}',
    depthSummaryLine: 'Max depth {maxDepth}, avg {avgDepth}',
    ariaWordCountIntro: 'Word count buckets for successful HTML pages:',
    ariaResponseTimeIntro: 'Response time buckets:',
    ariaDepthIntro: 'URLs by crawl depth from start URL:',
    ariaReadingIntro: 'Reading level (estimated) on 2xx pages:',
    ariaMimeIntro: 'Top content types:',
    ariaLighthouseIntro: 'Lighthouse category scores (0–100):',
    ariaSocialIntro: 'Social preview coverage on HTML pages:',
    statusAriaIntro: 'Status:',
  },
  contentAnalytics: {
    title: 'Content Insights',
    subtitle:
      'Word count, readability, content-to-HTML ratio, top keywords, social meta coverage, crawl health, and on-page flags.',
    meanWords: 'Mean Words',
    medianWords: 'Median Words',
    perPage: 'per page',
    ogCoverage: 'OG Coverage',
    ogTags: 'open graph tags',
    twitterCoverage: 'Twitter Coverage',
    twitterTags: 'twitter card tags',
    thinPages: 'Thin Pages',
    under300: 'under 300 words',
    i18nTitle: 'Internationalization (crawl)',
    pages2xx: '2xx pages',
    missingHtmlLang: 'Missing <html lang>',
    pagesHreflang: 'Pages with hreflang alternates',
    outboundDomains: 'Outbound link domains',
    thHost: 'Host',
    thLinks: 'Links',
    languageMix: 'Language mix',
    entityLabels: 'Entity labels',
    countAxis: 'Count',
    parentTopicsToken: 'Parent topics (token overlap)',
    thRepresentative: 'Representative',
    thClusterScore: 'Cluster score',
    thKeywords: 'Keywords',
    parentTopicsSemantic: 'Parent topics (semantic similarity)',
    crawlHealth: 'Crawl health & response times',
    urlsByStatus: 'URLs by HTTP status',
    totalCrawled: 'Total crawled:',
    returned2xx: 'returned 2xx',
    responseTimeDist: 'Response time distribution',
    pagesPerBand: 'Pages per latency band',
    onPageQuality: 'On-page quality & thin content',
    urlsByIssue: 'URLs flagged by issue type',
    pagesGoodRanges: 'Pages in “good” ranges',
    stackedInRange: 'In range / optimal',
    stackedNeeds: 'Needs attention',
    thinSignals: 'Thin content signals',
    thinUnder300: 'Under 300 words',
    thinSmallBody: 'Small HTML body',
    thinMatchSearch: '{shown} of {total} thin page{plural} match search',
    thinHaveLittle: '{count} page{plural} have very little content',
    noThinSearch: 'No thin pages match your search.',
    contentMetrics: 'Content Metrics',
    wordCountDist: 'Word Count Distribution',
    readingLevelDist: 'Reading Level Distribution',
    contentHtmlRatio: 'Content-to-HTML Ratio',
    topKeywords: 'Top 30 Keywords (Site-Wide)',
    noKeywordData: 'No keyword data',
    wordCountLadder: 'Word count ladder (min → max)',
    onPageSignals: 'On-Page SEO Signals',
    h1Dist: 'H1 Tag Distribution',
    titleTagQuality: 'Title Tag Length Quality',
    metaDescQuality: 'Meta Description Quality',
    socialMetaCoverage: 'Social Meta Coverage',
    ogProgress: 'Open Graph Coverage',
    twitterProgress: 'Twitter Card Coverage',
    socialOverview: 'Social Meta Coverage Overview',
    datasetHasTag: 'Has Tag',
    datasetMissing: 'Missing',
    ogImageCov: 'OG Image Coverage',
    hasOgImage: 'Has OG Image',
    missingOgImage: 'Missing OG Image',
    missingOgTags: 'Missing Open Graph Tags',
    missingTwitterTags: 'Missing Twitter Card Tags',
    socialAllGood:
      'All pages have social meta tags, or no data available yet. Run a crawl to populate.',
    siteArchitecture: 'Site Architecture',
    crawlDepthDist: 'Crawl Depth Distribution',
    maxDepth: 'Max depth:',
    avgDepth: 'avg:',
    wordCountPercentiles: 'Word Count Percentiles',
    wcMin: 'Min',
    wcP25: '25th Percentile (P25)',
    wcP50: 'Median (P50)',
    wcMean: 'Mean (Avg)',
    wcP75: '75th Percentile (P75)',
    wcMax: 'Max',
    h1Labels: ['No H1', 'One H1', 'Multiple H1s'],
    titleQualLabels: ['Missing', 'Too Short (<30)', 'Optimal (30–60)', 'Too Long (>60)'],
    metaQualLabels: ['Missing', 'Too Short (<70)', 'Optimal (70–160)', 'Too Long (>160)'],
    status2xx: '2xx OK',
    status3xx: '3xx Redirect',
    status4xx: '4xx Client error',
    status5xx: '5xx Server error',
    statusErr: 'Error / blocked',
    openGraph: 'Open Graph',
    twitterCard: 'Twitter Card',
    ogImage: 'OG Image',
    seoTitle: 'Title length',
    seoMeta: 'Meta description',
    seoH1: 'H1 count',
    noUrlSearch: 'No URLs match your search.',
    thinPagesView: 'View {count} thin page{s}',
    thThinHash: '#',
    thThinUrl: 'URL',
    thThinWords: 'Words',
    chartTooltipCount: '{n} pages',
    chartTooltipDoughnut: '{label}: {n} pages',
    chartTooltipGrouped: '{dataset}: {n} pages',
    chartTooltipPercent: '{dataset}: {pct}%',
    wcPercLabels: ['Min', 'P25', 'Median', 'Mean', 'P75', 'Max'],
    thPages: 'Pages',
    contentIssueKeys: [
      { key: 'missing_h1', label: 'Missing H1' },
      { key: 'missing_title', label: 'Missing title' },
      { key: 'multiple_h1', label: 'Multiple H1s' },
      { key: 'missing_meta_desc', label: 'Missing meta desc' },
      { key: 'meta_desc_short', label: 'Meta too short' },
      { key: 'meta_desc_long', label: 'Meta too long' },
      { key: 'thin_content', label: 'Thin (body chars)' },
    ],
  },
};
