/** Audit tools exposed to the report UI via POST /api/report/audit-tool. */
export const AUDIT_TOOL_ALLOWLIST = new Set([
  // Image SEO
  'get_image_audit_summary',
  'list_pages_with_missing_alt',
  'list_pages_with_images_missing_dimensions',
  'list_pages_without_lazy_images',
  'list_unoptimized_images',
  'list_largest_images',
  // Accessibility (axe)
  'get_axe_audit_summary',
  'list_pages_with_axe_violations',
  // GEO / AEO
  'get_geo_readiness_score',
  'get_agent_readiness_score',
  'get_agents_md_status',
  'get_skill_md_status',
  'get_agent_permissions_status',
  'get_token_budget_summary',
  'list_oversized_pages_for_agents',
  'get_content_structure_aeo_summary',
  'get_markdown_availability_summary',
  'list_pages_agent_unfriendly',
  'get_copy_for_ai_signals',
  'list_pages_missing_copy_for_ai',
  'generate_agent_readiness_bundle',
  'get_llms_txt_status',
  'get_ai_discovery_status',
  'get_robots_ai_access_score',
  'get_faq_schema_coverage',
  'list_pages_missing_faq_schema',
  'get_eeat_signals_summary',
  'get_citability_score',
  'get_citability_for_url',
  'get_negative_signals',
  'detect_prompt_injection',
  'get_rag_chunk_readiness',
  'get_content_decay_signals',
  'get_multimodal_readiness',
  'get_topic_authority',
  'generate_schema',
  'generate_robots_txt',
  'generate_meta_tags',
  'generate_geo_fix_bundle',
  'check_ai_citations_live',
  'compare_geo_score_deltas',
  'get_report_summary',
  'get_category_scores',
  'get_critical_issues',
  'list_broken_links',
  'get_lighthouse_summary',
  'get_google_summary',
]);

export function isAllowedAuditTool(name: string): boolean {
  return AUDIT_TOOL_ALLOWLIST.has(name);
}
