"""Initial PostgreSQL schema for WebsiteProfiling.

Revision ID: 001
Revises:
Create Date: 2026-06-02
"""
from __future__ import annotations

from alembic import op

revision = "001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE crawl_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            start_url TEXT
        );

        CREATE TABLE crawl_results (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            crawl_run_id BIGINT NOT NULL REFERENCES crawl_runs(id) ON DELETE CASCADE,
            url TEXT NOT NULL,
            data JSONB NOT NULL,
            UNIQUE (crawl_run_id, url)
        );
        CREATE INDEX idx_crawl_results_run ON crawl_results(crawl_run_id);

        CREATE TABLE edges (
            crawl_run_id BIGINT NOT NULL REFERENCES crawl_runs(id) ON DELETE CASCADE,
            from_url TEXT NOT NULL,
            to_url TEXT NOT NULL,
            PRIMARY KEY (crawl_run_id, from_url, to_url)
        );

        CREATE TABLE nodes (
            crawl_run_id BIGINT NOT NULL REFERENCES crawl_runs(id) ON DELETE CASCADE,
            url TEXT NOT NULL,
            count INTEGER NOT NULL,
            PRIMARY KEY (crawl_run_id, url)
        );

        CREATE TABLE lighthouse_summary (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            data JSONB NOT NULL
        );

        CREATE TABLE lighthouse_runs (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            url TEXT NOT NULL,
            strategy TEXT NOT NULL,
            run_index INTEGER NOT NULL,
            data JSONB NOT NULL
        );

        CREATE TABLE lighthouse_page_summaries (
            url TEXT PRIMARY KEY,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            data JSONB NOT NULL
        );

        CREATE TABLE report_payload (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            generated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            data JSONB NOT NULL
        );

        CREATE TABLE google_data (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            data JSONB NOT NULL
        );

        CREATE TABLE keyword_data (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            data JSONB NOT NULL
        );

        CREATE TABLE keyword_history (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            keyword TEXT NOT NULL,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            position DOUBLE PRECISION,
            clicks INTEGER,
            impressions INTEGER,
            ctr DOUBLE PRECISION
        );
        CREATE INDEX idx_kw_history_keyword ON keyword_history(keyword);

        CREATE TABLE keyword_suggest_cache (
            cache_key TEXT PRIMARY KEY,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            data JSONB NOT NULL
        );

        CREATE TABLE lh_audits (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            run_id BIGINT NOT NULL REFERENCES lighthouse_runs(id) ON DELETE CASCADE,
            audit_id TEXT NOT NULL,
            category_id TEXT,
            score DOUBLE PRECISION,
            score_display_mode TEXT,
            title TEXT,
            description TEXT,
            display_value TEXT,
            numeric_value DOUBLE PRECISION,
            help_text TEXT,
            details_type TEXT,
            details_headings JSONB,
            details_meta JSONB
        );
        CREATE INDEX idx_lh_audits_run_id ON lh_audits(run_id);
        CREATE INDEX idx_lh_audits_run_audit ON lh_audits(run_id, audit_id);
        CREATE INDEX idx_lh_audits_audit_id ON lh_audits(audit_id);

        CREATE TABLE lh_audit_items (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            audit_row_id BIGINT NOT NULL REFERENCES lh_audits(id) ON DELETE CASCADE,
            item_index INTEGER NOT NULL,
            row_data JSONB NOT NULL
        );
        CREATE INDEX idx_lh_audit_items_audit_row ON lh_audit_items(audit_row_id);

        CREATE TABLE pipeline_config (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            is_unknown BOOLEAN NOT NULL DEFAULT false,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE llm_config (
            key TEXT PRIMARY KEY,
            value TEXT NOT NULL,
            is_secret BOOLEAN NOT NULL DEFAULT false,
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );

        CREATE TABLE llm_cache (
            cache_key TEXT PRIMARY KEY,
            response_json JSONB NOT NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
    """)


def downgrade() -> None:
    op.execute("""
        DROP TABLE IF EXISTS llm_cache CASCADE;
        DROP TABLE IF EXISTS llm_config CASCADE;
        DROP TABLE IF EXISTS pipeline_config CASCADE;
        DROP TABLE IF EXISTS lh_audit_items CASCADE;
        DROP TABLE IF EXISTS lh_audits CASCADE;
        DROP TABLE IF EXISTS keyword_suggest_cache CASCADE;
        DROP TABLE IF EXISTS keyword_history CASCADE;
        DROP TABLE IF EXISTS keyword_data CASCADE;
        DROP TABLE IF EXISTS google_data CASCADE;
        DROP TABLE IF EXISTS report_payload CASCADE;
        DROP TABLE IF EXISTS lighthouse_page_summaries CASCADE;
        DROP TABLE IF EXISTS lighthouse_runs CASCADE;
        DROP TABLE IF EXISTS lighthouse_summary CASCADE;
        DROP TABLE IF EXISTS nodes CASCADE;
        DROP TABLE IF EXISTS edges CASCADE;
        DROP TABLE IF EXISTS crawl_results CASCADE;
        DROP TABLE IF EXISTS crawl_runs CASCADE;
    """)
