"""Properties, durable pipeline/export jobs, audit log.

Revision ID: 003
Revises: 002
"""
from __future__ import annotations

from alembic import op

revision = "003"
down_revision = "002"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE properties (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            name TEXT NOT NULL,
            canonical_domain TEXT NOT NULL,
            site_url TEXT,
            gsc_site_url TEXT,
            ga4_property_id TEXT,
            default_crawl_preset TEXT,
            crawl_authorized_at TIMESTAMPTZ,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (canonical_domain)
        );
        CREATE INDEX idx_properties_domain ON properties(canonical_domain);

        CREATE TABLE pipeline_jobs (
            id UUID PRIMARY KEY,
            job_type TEXT NOT NULL DEFAULT 'pipeline',
            status TEXT NOT NULL DEFAULT 'running',
            exit_code INTEGER,
            log_text TEXT NOT NULL DEFAULT '',
            error_text TEXT,
            property_id BIGINT REFERENCES properties(id) ON DELETE SET NULL,
            config_hash TEXT,
            started_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            finished_at TIMESTAMPTZ
        );
        CREATE INDEX idx_pipeline_jobs_started ON pipeline_jobs(started_at DESC);

        CREATE TABLE export_jobs (
            id UUID PRIMARY KEY,
            report_id BIGINT NOT NULL,
            format TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'pending',
            file_path TEXT,
            error_text TEXT,
            property_id BIGINT REFERENCES properties(id) ON DELETE SET NULL,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            finished_at TIMESTAMPTZ
        );

        CREATE TABLE audit_log (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            action TEXT NOT NULL,
            actor TEXT,
            property_id BIGINT REFERENCES properties(id) ON DELETE SET NULL,
            detail JSONB,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_audit_log_created ON audit_log(created_at DESC);

        ALTER TABLE crawl_runs ADD COLUMN IF NOT EXISTS property_id BIGINT
            REFERENCES properties(id) ON DELETE SET NULL;
        CREATE INDEX IF NOT EXISTS idx_crawl_runs_property ON crawl_runs(property_id);
    """)


def downgrade() -> None:
    op.execute("""
        DROP INDEX IF EXISTS idx_crawl_runs_property;
        ALTER TABLE crawl_runs DROP COLUMN IF EXISTS property_id;
        DROP TABLE IF EXISTS audit_log;
        DROP TABLE IF EXISTS export_jobs;
        DROP TABLE IF EXISTS pipeline_jobs;
        DROP TABLE IF EXISTS properties;
    """)
