"""Per-page live Google fetch history (GSC + GA4)."""

from alembic import op

revision = "004_page_google_snapshots"
down_revision = "003"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE page_google_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            page_url TEXT NOT NULL,
            url_norm TEXT NOT NULL,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            data JSONB NOT NULL
        );
        CREATE INDEX ix_page_google_snapshots_url_norm_fetched
            ON page_google_snapshots (url_norm, fetched_at DESC);
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS page_google_snapshots CASCADE;")
