"""Roadmap foundation: issue workflow, property schedule, audit snapshots.

Revision ID: 011_roadmap_foundation
Revises: 010_gsc_links_data
"""
from __future__ import annotations

from alembic import op

revision = "011_roadmap_foundation"
down_revision = "010_gsc_links_data"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE issue_status (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
            report_id BIGINT,
            issue_fingerprint TEXT NOT NULL,
            category_id TEXT,
            message TEXT NOT NULL,
            url TEXT NOT NULL DEFAULT '',
            priority TEXT NOT NULL DEFAULT 'Medium',
            status TEXT NOT NULL DEFAULT 'open',
            assignee TEXT,
            note TEXT,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (property_id, issue_fingerprint)
        );
        CREATE INDEX idx_issue_status_property ON issue_status(property_id, status);
        CREATE INDEX idx_issue_status_report ON issue_status(report_id);

        ALTER TABLE properties
            ADD COLUMN IF NOT EXISTS schedule_cron TEXT,
            ADD COLUMN IF NOT EXISTS alert_webhook_url TEXT,
            ADD COLUMN IF NOT EXISTS alert_email TEXT;

        CREATE TABLE audit_health_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
            report_id BIGINT NOT NULL,
            canonical_domain TEXT,
            health_score INTEGER,
            category_scores JSONB NOT NULL DEFAULT '{}',
            issue_counts JSONB NOT NULL DEFAULT '{}',
            generated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_audit_health_property ON audit_health_snapshots(property_id, generated_at DESC);
        CREATE INDEX idx_audit_health_report ON audit_health_snapshots(report_id);

        CREATE TABLE gsc_links_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            referring_domains INTEGER NOT NULL DEFAULT 0,
            top_domains JSONB NOT NULL DEFAULT '[]'
        );
        CREATE INDEX idx_gsc_links_snapshots_property ON gsc_links_snapshots(property_id, fetched_at DESC);

        CREATE TABLE log_file_uploads (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
            filename TEXT NOT NULL,
            line_count INTEGER NOT NULL DEFAULT 0,
            uploaded_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            analysis JSONB NOT NULL DEFAULT '{}'
        );
        CREATE INDEX idx_log_uploads_property ON log_file_uploads(property_id, uploaded_at DESC);

        CREATE TABLE crux_snapshots (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT REFERENCES properties(id) ON DELETE CASCADE,
            origin TEXT NOT NULL,
            url TEXT,
            metrics JSONB NOT NULL DEFAULT '{}',
            fetched_at TIMESTAMPTZ NOT NULL DEFAULT now()
        );
        CREATE INDEX idx_crux_snapshots_origin ON crux_snapshots(origin, fetched_at DESC);
    """)


def downgrade() -> None:
    op.execute("""
        DROP TABLE IF EXISTS crux_snapshots;
        DROP TABLE IF EXISTS log_file_uploads;
        DROP TABLE IF EXISTS gsc_links_snapshots;
        DROP TABLE IF EXISTS audit_health_snapshots;
        ALTER TABLE properties
            DROP COLUMN IF EXISTS schedule_cron,
            DROP COLUMN IF EXISTS alert_webhook_url,
            DROP COLUMN IF EXISTS alert_email;
        DROP TABLE IF EXISTS issue_status;
    """)
