"""Chat sessions and messages for in-app AI chat.

Revision ID: 012_chat_sessions
Revises: 011_roadmap_foundation
"""
from __future__ import annotations

from alembic import op

revision = "012_chat_sessions"
down_revision = "011_roadmap_foundation"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE chat_sessions (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
            title TEXT NOT NULL DEFAULT 'New chat',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("""
        CREATE TABLE chat_messages (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            session_id BIGINT NOT NULL REFERENCES chat_sessions(id) ON DELETE CASCADE,
            role TEXT NOT NULL CHECK (role IN ('user', 'assistant', 'tool')),
            content TEXT NOT NULL DEFAULT '',
            tool_name TEXT,
            tool_args JSONB,
            tool_result JSONB,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("""
        CREATE INDEX chat_sessions_property_updated_idx
        ON chat_sessions(property_id, updated_at DESC)
    """)
    op.execute("""
        CREATE INDEX chat_messages_session_created_idx
        ON chat_messages(session_id, created_at)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS chat_messages")
    op.execute("DROP TABLE IF EXISTS chat_sessions")
