"""Crawl discovery mode on crawl_runs and rich link_edges table.

Revision ID: 013_crawl_discovery_edges
Revises: 012_chat_sessions
"""
from __future__ import annotations

from alembic import op

revision = "013_crawl_discovery_edges"
down_revision = "012_chat_sessions"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        ALTER TABLE crawl_runs
            ADD COLUMN IF NOT EXISTS discovery_mode TEXT DEFAULT 'spider';

        CREATE TABLE IF NOT EXISTS link_edges (
            crawl_run_id BIGINT NOT NULL REFERENCES crawl_runs(id) ON DELETE CASCADE,
            from_url TEXT NOT NULL,
            to_url TEXT NOT NULL,
            anchor_text TEXT NOT NULL DEFAULT '',
            rel TEXT NOT NULL DEFAULT '',
            is_nofollow BOOLEAN NOT NULL DEFAULT FALSE,
            is_sponsored BOOLEAN NOT NULL DEFAULT FALSE,
            is_ugc BOOLEAN NOT NULL DEFAULT FALSE,
            link_type TEXT NOT NULL DEFAULT 'internal',
            PRIMARY KEY (crawl_run_id, from_url, to_url, anchor_text, rel)
        );
        CREATE INDEX IF NOT EXISTS idx_link_edges_run_from
            ON link_edges(crawl_run_id, from_url);
        CREATE INDEX IF NOT EXISTS idx_link_edges_run_to
            ON link_edges(crawl_run_id, to_url);

        CREATE TABLE IF NOT EXISTS saved_crawl_filters (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
            name TEXT NOT NULL,
            filter_json JSONB NOT NULL DEFAULT '{}',
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            UNIQUE (property_id, name)
        );
        CREATE INDEX IF NOT EXISTS idx_saved_crawl_filters_property
            ON saved_crawl_filters(property_id);
    """)


def downgrade() -> None:
    op.execute("""
        DROP TABLE IF EXISTS saved_crawl_filters CASCADE;
        DROP TABLE IF EXISTS link_edges CASCADE;
        ALTER TABLE crawl_runs DROP COLUMN IF EXISTS discovery_mode;
    """)
