"""Property-scoped content drafts for Content Studio.

Revision ID: 017_content_drafts
Revises: 016_competitor_keyword_gap
"""
from __future__ import annotations

from alembic import op

revision = "017_content_drafts"
down_revision = "016_competitor_keyword_gap"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE content_drafts (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
            title TEXT NOT NULL DEFAULT 'Untitled draft',
            target_keyword TEXT NOT NULL DEFAULT '',
            landing_url TEXT,
            status TEXT NOT NULL DEFAULT 'draft'
                CHECK (status IN ('draft', 'ready', 'archived')),
            body_html TEXT NOT NULL DEFAULT '',
            title_tag TEXT NOT NULL DEFAULT '',
            meta_description TEXT NOT NULL DEFAULT '',
            grade_score SMALLINT,
            grade_snapshot JSONB,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("""
        CREATE INDEX content_drafts_property_updated_idx
        ON content_drafts(property_id, updated_at DESC)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS content_drafts")
