"""Custom dashboards — property-scoped dashboard builder with JSONB layout.

Revision ID: 022_dashboards
Revises: 021_google_ads_planner_settings
Create Date: 2026-06-19
"""
from __future__ import annotations

from alembic import op

revision = "022_dashboards"
down_revision = "021_google_ads_planner_settings"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute("""
        CREATE TABLE dashboards (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            property_id BIGINT NOT NULL REFERENCES properties(id) ON DELETE CASCADE,
            name TEXT NOT NULL DEFAULT 'Untitled dashboard',
            layout_json JSONB NOT NULL DEFAULT '{}'::jsonb,
            is_default BOOLEAN NOT NULL DEFAULT false,
            created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
            updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
        )
    """)
    op.execute("""
        CREATE INDEX dashboards_property_updated_idx
        ON dashboards(property_id, updated_at DESC)
    """)


def downgrade() -> None:
    op.execute("DROP TABLE IF EXISTS dashboards")
