using System.Text.Json;
using System.Text.Json.Nodes;
using AiService.Api.Tools.Context;
using AiService.Api.Tools.Persistence;
using WebsiteProfiling.Contracts.Json;

namespace AiService.Api.Tools.Handlers.Geo;

/// <summary>GEO file generators — ports Python <c>integrations/llm_tools.py</c> schema/robots/meta tools.</summary>
public static class GeoGenerationToolHandlers
{
    private static readonly string[] AiBotAgents =
    [
        "GPTBot", "OAI-SearchBot", "ChatGPT-User", "ClaudeBot", "anthropic-ai",
        "PerplexityBot", "Perplexity-User", "Google-Extended", "Googlebot", "Bingbot",
        "BingPreview", "DuckDuckBot", "Applebot", "Applebot-Extended", "CCBot",
        "Bytespider", "FacebookBot", "Amazonbot", "meta-externalagent", "meta-externalfetcher",
        "Diffbot", "ImagesiftBot", "omgili", "omgilibot", "Timpibot", "DataForSeoBot", "PiplBot",
    ];

    public static async Task<JsonObject> DraftLlmsTxtAsync(
        AuditToolsDbContext db,
        AuditToolContext ctx,
        JsonObject args,
        CancellationToken cancellationToken)
    {
        var scoped = ctx.WithArgs(args);
        var payload = await scoped.LoadPayloadAsync(db, cancellationToken);
        if (payload.Count == 0)
        {
            return new JsonObject { ["error"] = "no report found" };
        }

        var domain = await scoped.ResolvePropertyDomainAsync(db, cancellationToken);
        var siteName = JsonCoercion.AsString(payload["site_name"])?.Trim()
            ?? domain
            ?? "Site";
        var topPages = payload["top_pages"] as JsonArray ?? payload["links"] as JsonArray ?? [];
        var pageUrls = new List<string>();
        foreach (var node in topPages.Take(10))
        {
            if (node is JsonObject page && JsonCoercion.AsString(page["url"]) is { Length: > 0 } url)
            {
                pageUrls.Add(url);
            }
        }

        var schemaCov = payload["schema_coverage"] as JsonObject ?? [];
        var pagesWithSchema = JsonCoercion.AsString(schemaCov["pages_with_schema"]) ?? "n/a";
        var draftLines = new List<string>
        {
            $"# {siteName}",
            "",
            "> LLM-oriented site index (draft — review before publishing)",
            "",
            "## Key pages",
        };
        draftLines.AddRange(pageUrls.Select(u => $"- {u}"));
        draftLines.Add("");
        draftLines.Add($"## Schema coverage: {pagesWithSchema} pages with structured data");

        return new JsonObject
        {
            ["site_name"] = siteName,
            ["llms_txt_draft"] = string.Join('\n', draftLines),
            ["provenance"] = "AI insights",
        };
    }

    public static async Task<JsonObject> GenerateRobotsTxtAsync(
        AuditToolsDbContext db,
        AuditToolContext ctx,
        JsonObject args,
        CancellationToken cancellationToken)
    {
        var scoped = ctx.WithArgs(args);
        var domain = await scoped.ResolvePropertyDomainAsync(db, cancellationToken);
        var baseUrl = BaseUrl(domain);
        var lines = new List<string> { "# robots.txt — generated by Site Audit", "" };
        foreach (var agent in AiBotAgents)
        {
            lines.Add($"User-agent: {agent}");
            lines.Add("Allow: /");
            lines.Add("");
        }

        lines.Add("User-agent: *");
        lines.Add("Allow: /");
        lines.Add("");
        if (baseUrl.Length > 0)
        {
            lines.Add($"Sitemap: {baseUrl}/sitemap.xml");
        }

        return new JsonObject
        {
            ["domain"] = domain,
            ["robots_txt"] = string.Join('\n', lines),
            ["ai_bots_allowed"] = new JsonArray(AiBotAgents.Select(a => JsonValue.Create(a)).ToArray()),
            ["provenance"] = "Generated",
        };
    }

    public static async Task<JsonObject> GenerateMetaTagsAsync(
        AuditToolsDbContext db,
        AuditToolContext ctx,
        JsonObject args,
        CancellationToken cancellationToken)
    {
        var scoped = ctx.WithArgs(args);
        var url = JsonCoercion.AsString(args["url"])?.Trim() ?? "";
        if (url.Length == 0)
        {
            return new JsonObject { ["error"] = "url is required" };
        }

        var rows = await scoped.LoadCrawlDfAsync(db, cancellationToken);
        if (rows.Count == 0)
        {
            return new JsonObject { ["error"] = "no crawl data", ["url"] = url };
        }

        var needle = url.ToLowerInvariant();
        foreach (var row in rows)
        {
            var rowUrl = JsonCoercion.AsString(row["url"])?.Trim().ToLowerInvariant() ?? "";
            if (rowUrl != needle)
            {
                continue;
            }

            var title = JsonCoercion.AsString(row["title"]) ?? "";
            var rawDesc = JsonCoercion.AsString(row["meta_description"])
                ?? JsonCoercion.AsString(row["content_excerpt"])
                ?? "";
            var desc = rawDesc.Length > 160 ? rawDesc[..160] : rawDesc;
            var displayTitle = string.IsNullOrWhiteSpace(title) ? "Page Title" : title;
            var displayDesc = string.IsNullOrWhiteSpace(desc) ? "Page description." : desc;
            var tags = new[]
            {
                $"<title>{displayTitle}</title>",
                $"<meta name=\"description\" content=\"{displayDesc}\">",
                $"<link rel=\"canonical\" href=\"{url}\">",
                $"<meta property=\"og:title\" content=\"{displayTitle}\">",
                $"<meta property=\"og:description\" content=\"{displayDesc}\">",
                $"<meta property=\"og:url\" content=\"{url}\">",
                "<meta property=\"og:type\" content=\"website\">",
            };

            return new JsonObject
            {
                ["url"] = url,
                ["meta_tags_html"] = string.Join('\n', tags),
                ["title"] = title,
                ["meta_description"] = desc,
                ["provenance"] = "Generated",
            };
        }

        return new JsonObject { ["error"] = "url not found in crawl", ["url"] = url };
    }

    public static async Task<JsonObject> GenerateSchemaAsync(
        AuditToolsDbContext db,
        AuditToolContext ctx,
        JsonObject args,
        CancellationToken cancellationToken)
    {
        var scoped = ctx.WithArgs(args);
        var schemaType = JsonCoercion.AsString(args["schema_type"])?.Trim() ?? "WebSite";
        var url = JsonCoercion.AsString(args["url"])?.Trim() ?? "";
        var payload = await scoped.LoadPayloadAsync(db, cancellationToken);
        var domain = await scoped.ResolvePropertyDomainAsync(db, cancellationToken);
        var siteName = JsonCoercion.AsString(payload["site_name"])?.Trim() ?? domain ?? "Site";
        var baseUrl = BaseUrl(domain);
        if (baseUrl.Length == 0 && url.Length > 0)
        {
            baseUrl = url.Trim();
        }

        var schemaTypeClean = schemaType switch
        {
            "WebSite" or "Organization" or "FAQPage" or "Article" => schemaType,
            _ => "WebSite",
        };

        JsonObject schemaObj = schemaTypeClean switch
        {
            "Organization" => OrganizationSchema(siteName, baseUrl),
            "FAQPage" => await FaqPageSchemaAsync(scoped, db, cancellationToken),
            "Article" => await ArticleSchemaAsync(scoped, db, url, siteName, baseUrl, cancellationToken),
            _ => WebsiteSchema(siteName, baseUrl),
        };

        var script = $"<script type=\"application/ld+json\">\n{schemaObj.ToJsonString(new JsonSerializerOptions { WriteIndented = true })}\n</script>";
        return new JsonObject
        {
            ["schema_type"] = schemaTypeClean,
            ["schema_json"] = schemaObj,
            ["script_tag"] = script,
            ["provenance"] = "Generated",
        };
    }

    public static async Task<JsonObject> GenerateGeoFixBundleAsync(
        AuditToolsDbContext db,
        AuditToolContext ctx,
        JsonObject args,
        CancellationToken cancellationToken)
    {
        var scoped = ctx.WithArgs(args);
        var domain = await scoped.ResolvePropertyDomainAsync(db, cancellationToken);
        var llms = await DraftLlmsTxtAsync(db, scoped, args, cancellationToken);
        var robots = await GenerateRobotsTxtAsync(db, scoped, args, cancellationToken);
        var websiteSchema = await GenerateSchemaAsync(
            db, scoped, new JsonObject { ["schema_type"] = "WebSite" }, cancellationToken);
        var orgSchema = await GenerateSchemaAsync(
            db, scoped, new JsonObject { ["schema_type"] = "Organization" }, cancellationToken);

        return new JsonObject
        {
            ["domain"] = domain,
            ["missing_files"] = new JsonArray(),
            ["llms_txt"] = llms,
            ["robots_txt"] = robots,
            ["website_schema"] = websiteSchema,
            ["organization_schema"] = orgSchema,
            ["provenance"] = "Generated",
        };
    }

    private static JsonObject WebsiteSchema(string siteName, string baseUrl) => new()
    {
        ["@context"] = "https://schema.org",
        ["@type"] = "WebSite",
        ["name"] = siteName,
        ["url"] = baseUrl,
        ["description"] = $"{siteName} — official website",
        ["potentialAction"] = new JsonObject
        {
            ["@type"] = "SearchAction",
            ["target"] = new JsonObject
            {
                ["@type"] = "EntryPoint",
                ["urlTemplate"] = $"{baseUrl}/?s={{search_term_string}}",
            },
            ["query-input"] = "required name=search_term_string",
        },
    };

    private static JsonObject OrganizationSchema(string siteName, string baseUrl) => new()
    {
        ["@context"] = "https://schema.org",
        ["@type"] = "Organization",
        ["name"] = siteName,
        ["url"] = baseUrl,
        ["logo"] = new JsonObject
        {
            ["@type"] = "ImageObject",
            ["url"] = $"{baseUrl}/logo.png",
        },
        ["sameAs"] = new JsonArray(),
    };

    private static async Task<JsonObject> FaqPageSchemaAsync(
        AuditToolContext scoped,
        AuditToolsDbContext db,
        CancellationToken cancellationToken)
    {
        var rows = await scoped.LoadCrawlDfAsync(db, cancellationToken);
        var questions = new JsonArray();
        foreach (var row in rows)
        {
            var title = JsonCoercion.AsString(row["title"]) ?? "";
            var excerpt = (JsonCoercion.AsString(row["content_excerpt"]) ?? "")[..Math.Min(300, (JsonCoercion.AsString(row["content_excerpt"]) ?? "").Length)];
            var pageUrl = JsonCoercion.AsString(row["url"]) ?? "";
            if (!title.Contains('?') && !pageUrl.Contains("faq", StringComparison.OrdinalIgnoreCase))
            {
                continue;
            }

            questions.Add(new JsonObject
            {
                ["@type"] = "Question",
                ["name"] = title,
                ["acceptedAnswer"] = new JsonObject
                {
                    ["@type"] = "Answer",
                    ["text"] = excerpt.Length > 0 ? excerpt : "See full answer on the page.",
                },
            });
            if (questions.Count >= 10)
            {
                break;
            }
        }

        if (questions.Count == 0)
        {
            questions.Add(new JsonObject
            {
                ["@type"] = "Question",
                ["name"] = "Example question?",
                ["acceptedAnswer"] = new JsonObject
                {
                    ["@type"] = "Answer",
                    ["text"] = "Example answer.",
                },
            });
        }

        return new JsonObject
        {
            ["@context"] = "https://schema.org",
            ["@type"] = "FAQPage",
            ["mainEntity"] = questions,
        };
    }

    private static async Task<JsonObject> ArticleSchemaAsync(
        AuditToolContext scoped,
        AuditToolsDbContext db,
        string url,
        string siteName,
        string baseUrl,
        CancellationToken cancellationToken)
    {
        var headline = "";
        var description = "";
        if (url.Length > 0)
        {
            var needle = url.ToLowerInvariant();
            var rows = await scoped.LoadCrawlDfAsync(db, cancellationToken);
            foreach (var row in rows)
            {
                var rowUrl = JsonCoercion.AsString(row["url"])?.Trim().ToLowerInvariant() ?? "";
                if (rowUrl != needle)
                {
                    continue;
                }

                headline = JsonCoercion.AsString(row["title"]) ?? "";
                description = (JsonCoercion.AsString(row["meta_description"])
                    ?? JsonCoercion.AsString(row["content_excerpt"])
                    ?? "")[..Math.Min(200, (JsonCoercion.AsString(row["meta_description"])
                        ?? JsonCoercion.AsString(row["content_excerpt"])
                        ?? "").Length)];
                break;
            }
        }

        return new JsonObject
        {
            ["@context"] = "https://schema.org",
            ["@type"] = "Article",
            ["headline"] = headline.Length > 0 ? headline : "Article title",
            ["description"] = description.Length > 0 ? description : "Article description",
            ["url"] = url.Length > 0 ? url : baseUrl,
            ["publisher"] = new JsonObject
            {
                ["@type"] = "Organization",
                ["name"] = siteName,
                ["url"] = baseUrl,
            },
        };
    }

    private static string BaseUrl(string domain)
    {
        var text = (domain ?? "").Trim().TrimStart('.');
        if (text.Length == 0)
        {
            return "";
        }

        if (!text.StartsWith("http://", StringComparison.OrdinalIgnoreCase)
            && !text.StartsWith("https://", StringComparison.OrdinalIgnoreCase))
        {
            text = "https://" + text;
        }

        return text.TrimEnd('/');
    }
}
