"""TOOL_DEFINITIONS catalog for MCP and chat agent."""
from __future__ import annotations

from typing import Any

_PID = {"type": "integer", "description": "Property ID"}
_RID = {"type": "integer", "description": "Report ID (defaults to latest)"}
_LIMIT = {"type": "integer", "minimum": 1, "maximum": 50}
_URL = {"type": "string", "description": "Page URL"}


def _tool(name: str, description: str, properties: dict[str, Any], required: list[str] | None = None) -> dict[str, Any]:
    return {
        "name": name,
        "description": description,
        "inputSchema": {
            "type": "object",
            "properties": properties,
            "required": required or [],
        },
    }


TOOL_DEFINITIONS: list[dict[str, Any]] = [
    _tool("list_properties", "List all configured site properties (domains) in Site Audit.", {}),
    _tool("get_property", "Get details for one property by property_id.", {"property_id": _PID}, ["property_id"]),
    _tool(
        "get_report_summary",
        "Health score, issue counts by priority, crawl stats, and category scores for the latest or specified report.",
        {"property_id": _PID, "report_id": _RID},
    ),
    _tool("get_category_scores", "Category scores and overall health score for a report.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_executive_summary", "AI-generated executive summary narrative for the audit report.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_report_meta", "Report metadata: crawl scope, fetch methods, integration freshness.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_site_level", "Site-level robots.txt and sitemap.xml checks.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_report_history", "Past audit reports for a property (report IDs and dates).", {"property_id": _PID, "limit": _LIMIT}),
    _tool(
        "list_issues",
        "List audit issues with optional filters. Returns paginated results (max 50).",
        {
            "property_id": _PID,
            "report_id": _RID,
            "priority": {"type": "string", "enum": ["Critical", "High", "Medium", "Low"]},
            "category_id": {"type": "string"},
            "url_contains": {"type": "string"},
            "sort": {"type": "string", "enum": ["impact"]},
            "limit": _LIMIT,
        },
    ),
    _tool("list_issues_by_category", "List issues for one category_id only.", {"category_id": {"type": "string"}, "property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ["category_id"]),
    _tool("get_category_issues", "Full issue list and score for a single audit category.", {"category_id": {"type": "string"}, "property_id": _PID, "report_id": _RID}, ["category_id"]),
    _tool("list_issue_workflow", "Issue triage workflow status from issue_status table.", {"property_id": _PID, "status": {"type": "string"}, "limit": _LIMIT}),
    _tool("search_pages", "Search crawled pages by status code or URL substring. Max 30 results.", {"property_id": _PID, "report_id": _RID, "status": {"type": "string"}, "url_contains": {"type": "string"}, "limit": {"type": "integer", "maximum": 30}}),
    _tool("get_page_details", "Crawl row, Lighthouse snippet, and GSC/GA4 slice for one URL.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("get_internal_links", "Inlinks and outlinks for one URL from crawl graph.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("list_redirects", "Redirect chains detected in crawl (3xx with final URL).", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_broken_links", "Broken internal links (4xx/5xx) from crawl issues.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_status_code_breakdown", "HTTP status code counts from crawl summary.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_response_time_stats", "Response time percentiles (p50, p95) from crawl.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_depth_distribution", "Crawl depth histogram (clicks from start URL).", {"property_id": _PID, "report_id": _RID}),
    _tool("get_crawl_segments", "Per-path-prefix crawl segment rollups (requires crawl_path_segments config).", {"property_id": _PID, "report_id": _RID}),
    _tool("get_browser_diagnostics_summary", "Aggregated JS console errors and browser diagnostics from rendered crawl.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_schema_coverage", "Site-wide schema.org coverage from crawl (has_schema + JSON-LD types).", {"property_id": _PID, "report_id": _RID}),
    _tool("list_pages_without_schema", "URLs missing structured data markup. Empty list means full coverage.", {"property_id": _PID, "report_id": _RID, "limit": {"type": "integer", "maximum": 30}}),
    _tool("search_pages_by_schema_type", "Find pages with a specific JSON-LD type (e.g. Organization, Article).", {"schema_type": {"type": "string"}, "property_id": _PID, "report_id": _RID, "limit": {"type": "integer", "maximum": 30}}, ["schema_type"]),
    _tool("get_seo_health", "On-page SEO KPI counts: titles, meta descriptions, H1s, thin content.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_orphan_pages", "Crawled URLs with zero internal inlinks.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_top_linked_pages", "Most-linked internal pages by inlink count.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_outbound_link_domains", "External domains linked from the site.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_link_graph_summary", "Internal link graph node/edge counts and top hub pages.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_url_fingerprints", "URL pattern fingerprints for duplicate URL detection.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_indexation_coverage", "Sitemap vs crawl vs GSC URL set comparison and gap lists.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_hreflang_summary", "Hreflang alternate tag coverage and issues.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_language_summary", "Detected page language distribution.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_content_analytics", "Word count stats, thin pages, top site keywords from crawl.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_content_duplicates", "Near-duplicate content clusters from ML analysis.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_social_coverage", "Open Graph and Twitter card coverage percentages.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_keyword_opportunities", "On-page keyword opportunity hints from crawl.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_ner_site_summary", "Named-entity summary across site content.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_thin_content_pages", "Pages flagged as thin content (low word count).", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_keyword_summary", "Top keywords, striking-distance count, and GSC metrics.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("search_keywords", "Search keyword list by substring match.", {"property_id": _PID, "query": {"type": "string"}, "limit": _LIMIT}, ["property_id", "query"]),
    _tool("get_striking_distance_keywords", "Keywords ranking positions 4–20 (striking distance opportunities).", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("get_keyword_cannibalisation", "Queries where multiple pages rank in GSC.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("get_query_page_misalignment", "GSC queries whose landing page may not match intent.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("get_semantic_keyword_clusters", "LLM-generated semantic keyword clusters.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_keyword_history", "Time-series GSC metrics for one keyword.", {"property_id": _PID, "keyword": {"type": "string"}, "limit": _LIMIT}, ["property_id", "keyword"]),
    _tool("get_google_summary", "GSC and GA4 headline metrics, top queries and pages.", {"property_id": _PID}),
    _tool("get_gsc_top_queries", "Top Search Console queries by clicks.", {"property_id": _PID, "limit": _LIMIT}),
    _tool("get_gsc_top_pages", "Top Search Console pages by clicks.", {"property_id": _PID, "limit": _LIMIT}),
    _tool("get_ga4_summary", "GA4 organic summary and top landing pages.", {"property_id": _PID, "limit": _LIMIT}),
    _tool("get_gsc_page_query_slice", "GSC queries and metrics for a single page URL.", {"url": _URL, "property_id": _PID}, ["url"]),
    _tool("get_gsc_links_summary", "GSC Links CSV import summary: top linking sites and linked pages.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("get_gsc_links_import_status", "Whether GSC Links data is imported and when.", {"property_id": _PID}, ["property_id"]),
    _tool("get_competitor_link_gap", "Domains linking to competitors but not you (requires competitor_domains config).", {"property_id": _PID, "report_id": _RID}),
    _tool("get_bing_backlinks_summary", "Bing Webmaster backlinks summary (if API key configured).", {"property_id": _PID, "report_id": _RID}),
    _tool("get_lighthouse_summary", "Site-wide Lighthouse summary and poor-performance pages.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_lighthouse_for_url", "Lighthouse scores and audits for one URL.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("get_lighthouse_diagnostics", "Lighthouse audit diagnostics across sampled pages.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_crux_summary", "Chrome UX Report field data (CrUX) for origin.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_slow_pages", "Pages with Lighthouse performance below threshold (default 50).", {"property_id": _PID, "report_id": _RID, "performance_threshold": {"type": "integer"}, "limit": _LIMIT}),
    _tool("get_health_history", "Historical health score snapshots for trend analysis.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("compare_reports", "Full audit drift comparison between current and baseline report.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    _tool("get_integration_alerts", "Stale GSC Links imports and health score drop alerts.", {"property_id": _PID}, ["property_id"]),
    _tool("get_tech_stack_summary", "Detected technologies (CMS, analytics, CDN) from crawl.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_security_findings", "Security header and TLS findings from security scan.", {"property_id": _PID, "report_id": _RID, "severity": {"type": "string"}, "limit": _LIMIT}),
    # Report extras
    _tool("get_audit_recommendations", "Actionable SEO recommendation bullets from the audit.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_ml_errors", "ML analysis errors (duplicates, NER, clusters) if any failed.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_ssl_expiry_info", "Site TLS certificate expiry from the audit.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_ads_txt_status", "ads.txt presence and validation from site-level checks.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_security_txt_status", "security.txt presence and Contact/Expires fields from site-level checks.", {"property_id": _PID, "report_id": _RID}),
    _tool(
        "list_subdomains",
        "Passive subdomain inventory from crawl, GSC, and certificate transparency.",
        {
            "property_id": _PID,
            "report_id": _RID,
            "in_scope_only": {"type": "boolean", "description": "Only hosts on the property apex (default true)"},
            "limit": {"type": "integer", "maximum": 200},
        },
    ),
    _tool(
        "get_contact_intelligence",
        "Business contact signals from crawl, schema, security.txt, and RDAP org (sourced).",
        {"property_id": _PID, "report_id": _RID, "limit": {"type": "integer", "maximum": 100}},
    ),
    _tool("list_audit_categories", "All audit categories with scores and issue counts.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_category_recommendations", "Category-level recommendations for one category_id.", {"category_id": {"type": "string"}, "property_id": _PID, "report_id": _RID}, ["category_id"]),
    _tool("list_issues_with_ai_fixes", "Issues that include LLM-generated fix suggestions.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    # On-page
    _tool("list_seo_onpage_issues", "Flat SEO issue list (titles, meta, H1, thin content) with optional issue_type filter.", {"property_id": _PID, "report_id": _RID, "issue_type": {"type": "string"}, "limit": _LIMIT}),
    _tool("list_content_url_issues", "Pages in a content_urls bucket (missing_title, missing_h1, thin_content, etc.).", {"bucket": {"type": "string"}, "property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ["bucket"]),
    _tool("list_pages_missing_title", "Pages with no title tag.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_missing_h1", "Pages with no H1.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_multiple_h1", "Pages with multiple H1 elements.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_missing_meta_description", "Pages with no meta description.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_meta_desc_too_short", "Pages with meta description under 70 characters.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_meta_desc_too_long", "Pages with meta description over 160 characters.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_noindex", "Crawled pages with noindex directive.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    # Charts / aggregates
    _tool("get_crawl_summary", "Full crawl summary block (URL counts, success rate, timing).", {"property_id": _PID, "report_id": _RID}),
    _tool(
        "get_issue_priority_breakdown",
        "Issue counts by priority (Critical/High/Medium/Low) as chart data for chat UI.",
        {"property_id": _PID, "report_id": _RID},
    ),
    _tool(
        "get_critical_issues",
        "All Critical-priority audit issues with URL, category, and message (for chat issue table).",
        {"property_id": _PID, "report_id": _RID, "limit": _LIMIT},
    ),
    _tool("get_mime_type_breakdown", "Content-Type distribution from crawl.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_title_length_distribution", "Title length histogram from crawl.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_domain_link_distribution", "Internal link domain breakdown chart data.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_outlink_distribution", "Outlink count distribution chart data.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_top_crawled_pages", "Top pages by inlinks from crawl.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    # Indexation depth
    _tool("list_indexation_gaps", "URLs in an indexation gap list (sitemap_only, crawled_not_in_sitemap, gsc_not_crawled).", {"gap_type": {"type": "string"}, "property_id": _PID, "report_id": _RID, "limit": {"type": "integer", "maximum": 200}}, ["gap_type"]),
    _tool("get_indexation_url_join", "GSC vs crawl URL join table from indexation coverage.", {"property_id": _PID, "report_id": _RID}),
    # Backlinks depth
    _tool("get_gsc_sample_links", "Sample backlinks from GSC Links CSV import.", {"property_id": _PID, "limit": {"type": "integer", "maximum": 100}}, ["property_id"]),
    _tool("get_gsc_latest_links", "Latest discovered backlinks from GSC Links import.", {"property_id": _PID, "limit": {"type": "integer", "maximum": 100}}, ["property_id"]),
    _tool("get_third_party_links_overlay", "Moz/Majestic third-party backlink overlays.", {"property_id": _PID, "provider": {"type": "string"}}, ["property_id"]),
    _tool("get_backlinks_velocity", "Referring-domain trend from gsc_links_snapshots.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    # Ops / integrations
    _tool("get_property_ops", "Schedule cron and alert webhook/email settings (read-only).", {"property_id": _PID}, ["property_id"]),
    _tool("get_google_integration_status", "Google OAuth, GSC/GA4 mapping, and data freshness.", {"property_id": _PID}, ["property_id"]),
    _tool("list_crawl_runs", "Recent crawl run history for a property.", {"property_id": _PID, "limit": _LIMIT}),
    _tool("list_log_uploads", "Access log file uploads for a property.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("get_latest_log_analysis", "Most recent parsed access log analysis.", {"property_id": _PID}, ["property_id"]),
    # Keywords depth
    _tool("get_keyword_serp_overlay", "Keywords with SERP competition overlay data.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("list_keywords_by_action", "Keywords filtered by recommended_action.", {"property_id": _PID, "recommended_action": {"type": "string"}, "limit": _LIMIT}, ["property_id", "recommended_action"]),
    _tool("list_keywords_by_position", "Keywords filtered by GSC position range.", {"property_id": _PID, "min_position": {"type": "number"}, "max_position": {"type": "number"}, "limit": _LIMIT}, ["property_id"]),
    _tool("list_keywords_by_impressions", "Keywords with at least min_impressions.", {"property_id": _PID, "min_impressions": {"type": "integer"}, "limit": _LIMIT}, ["property_id"]),
    # Lighthouse depth
    _tool("get_lighthouse_human_summary", "Natural-language Lighthouse summary narrative.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_lighthouse_poor_seo_pages", "Pages with Lighthouse SEO score below threshold.", {"property_id": _PID, "report_id": _RID, "seo_threshold": {"type": "integer"}, "limit": _LIMIT}),
    # Crawl depth
    _tool("get_page_analysis", "Full page_analysis JSON (schema, console errors, accessibility) for one URL.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("search_pages_advanced", "Search crawl with filters: status, noindex, word count, fetch method, missing title.", {"property_id": _PID, "report_id": _RID, "status": {"type": "string"}, "url_contains": {"type": "string"}, "noindex_only": {"type": "boolean"}, "missing_title": {"type": "boolean"}, "min_word_count": {"type": "integer"}, "max_word_count": {"type": "integer"}, "fetch_method": {"type": "string"}, "limit": {"type": "integer", "maximum": 50}}),
    _tool("list_pages_with_console_errors", "Rendered pages with JS console errors.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_by_fetch_method", "Pages crawled via static or rendered fetch.", {"property_id": _PID, "report_id": _RID, "fetch_method": {"type": "string"}, "limit": _LIMIT}, ["fetch_method"]),
    _tool("get_crawl_links_table", "Paginated links table from report payload.", {"property_id": _PID, "report_id": _RID, "url_contains": {"type": "string"}, "limit": {"type": "integer", "maximum": 100}}),
    _tool("get_graph_edges_sample", "Sample of internal link graph edges.", {"property_id": _PID, "report_id": _RID, "limit": {"type": "integer", "maximum": 200}}),
    _tool("list_status_4xx_pages", "All crawled 4xx pages.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_status_5xx_pages", "All crawled 5xx pages.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    # Google depth
    _tool("get_ga4_page_metrics", "GA4 metrics for a landing page path or URL.", {"property_id": _PID, "path": {"type": "string"}, "url": _URL}),
    # Health depth
    _tool("get_category_health_history", "Category score trend from audit_health_snapshots.", {"property_id": _PID, "category_id": {"type": "string"}, "limit": _LIMIT}, ["property_id"]),
    # Compare slices
    _tool("compare_issue_deltas", "New and resolved issues vs baseline report.", {"baseline_report_id": _RID, "report_id": _RID, "limit": {"type": "integer", "maximum": 100}}, ["baseline_report_id"]),
    _tool("compare_category_deltas", "Category score changes vs baseline report.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    _tool("compare_seo_health_deltas", "On-page SEO KPI changes vs baseline report.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    _tool("compare_lighthouse_deltas", "Lighthouse score changes per URL vs baseline.", {"baseline_report_id": _RID, "report_id": _RID, "limit": _LIMIT}, ["baseline_report_id"]),
    _tool("compare_url_set_diff", "URLs added or removed from crawl vs baseline.", {"baseline_report_id": _RID, "report_id": _RID, "limit": {"type": "integer", "maximum": 200}}, ["baseline_report_id"]),
    _tool("compare_redirect_deltas", "Redirect chain changes vs baseline.", {"baseline_report_id": _RID, "report_id": _RID, "limit": {"type": "integer", "maximum": 100}}, ["baseline_report_id"]),
    _tool("compare_link_metric_deltas", "Per-URL inlink/outlink/word-count changes vs baseline.", {"baseline_report_id": _RID, "report_id": _RID, "limit": {"type": "integer", "maximum": 200}}, ["baseline_report_id"]),
    _tool("compare_security_deltas", "Security finding additions and resolutions vs baseline.", {"baseline_report_id": _RID, "report_id": _RID, "limit": _LIMIT}, ["baseline_report_id"]),
    _tool("compare_duplicate_deltas", "Near-duplicate cluster changes vs baseline.", {"baseline_report_id": _RID, "report_id": _RID, "limit": _LIMIT}, ["baseline_report_id"]),
    _tool("compare_tech_deltas", "Technology stack changes vs baseline.", {"baseline_report_id": _RID, "report_id": _RID, "limit": _LIMIT}, ["baseline_report_id"]),
    _tool("compare_content_metrics", "Content and crawl metric changes vs baseline.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    _tool("compare_google_metrics", "GSC and GA4 metric changes vs baseline.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    _tool("compare_priority_counts", "Issue priority count changes vs baseline.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    _tool("compare_health_score_delta", "Overall health score change vs baseline.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    # Crawl list tools
    _tool("list_pages_missing_canonical", "2xx pages with no canonical URL.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_canonical_mismatch", "Pages where canonical URL differs from crawled URL.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_with_missing_alt", "Pages with images missing alt text.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_skipped_headings", "Pages with skipped heading levels (e.g. H1 to H3).", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_missing_viewport", "Pages missing viewport meta tag.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_long_redirect_chains", "URLs with redirect chains of 2+ hops.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_robots_blocked_urls", "URLs blocked by robots.txt during crawl.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_missing_og_image", "Pages missing Open Graph image.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_top_pages_by_pagerank", "Top internal pages by crawl PageRank score.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    # Log analyzer slices
    _tool("get_log_top_paths", "Top hit paths from latest access log analysis.", {"property_id": _PID, "limit": {"type": "integer", "maximum": 100}}, ["property_id"]),
    _tool("list_log_only_paths", "Paths in access logs but not in crawl.", {"property_id": _PID, "limit": {"type": "integer", "maximum": 200}}, ["property_id"]),
    _tool("list_crawl_only_paths", "Crawled paths not seen in access logs.", {"property_id": _PID, "limit": {"type": "integer", "maximum": 200}}, ["property_id"]),
    _tool("get_log_googlebot_stats", "Googlebot hit counts and ratio from access log.", {"property_id": _PID}, ["property_id"]),
    _tool("get_log_analysis_by_id", "Access log analysis for a specific upload_id.", {"property_id": _PID, "upload_id": {"type": "integer"}}, ["property_id", "upload_id"]),
    # Lighthouse depth
    _tool("list_lighthouse_poor_accessibility_pages", "Pages with Lighthouse accessibility below threshold.", {"property_id": _PID, "report_id": _RID, "accessibility_threshold": {"type": "integer"}, "limit": _LIMIT}),
    _tool("list_lighthouse_poor_best_practices_pages", "Pages with Lighthouse best-practices below threshold.", {"property_id": _PID, "report_id": _RID, "best_practices_threshold": {"type": "integer"}, "limit": _LIMIT}),
    _tool("list_lighthouse_cwv_failures", "Pages failing LCP, CLS, or TBT thresholds.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    # Drill-down
    _tool("list_pages_by_technology", "Pages using a detected technology name.", {"property_id": _PID, "report_id": _RID, "technology_name": {"type": "string"}, "limit": _LIMIT}, ["technology_name"]),
    _tool("get_duplicate_cluster", "Duplicate content cluster by index or member URL.", {"property_id": _PID, "report_id": _RID, "cluster_index": {"type": "integer"}, "url": _URL}),
    _tool("get_security_findings_summary", "Security findings grouped by finding_type.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_security_findings_by_type", "Security findings filtered by finding_type.", {"property_id": _PID, "report_id": _RID, "finding_type": {"type": "string"}, "limit": _LIMIT}, ["finding_type"]),
    _tool("list_broken_link_sources", "Pages linking to broken URLs.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_link_rel_summary", "nofollow/sponsored/UGC counts from crawl link_edges.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_inlink_anchors", "Inlink anchor text matrix (target × anchor counts).", {"property_id": _PID, "report_id": _RID, "url": _URL, "limit": {"type": "integer", "maximum": 200}}),
    _tool("list_nofollow_internal_links", "Internal links with rel=nofollow from crawl.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("search_issues", "Search audit issues by message, URL, category, or priority.", {"property_id": _PID, "report_id": _RID, "message_contains": {"type": "string"}, "url_contains": {"type": "string"}, "category_id": {"type": "string"}, "priority": {"type": "string"}, "sort": {"type": "string", "enum": ["impact"]}, "limit": _LIMIT}),
    # LLM / portfolio
    _tool("generate_content_brief", "Generate a content brief for a target keyword.", {"property_id": _PID, "keyword": {"type": "string"}, "gaps": {"type": "array", "items": {"type": "string"}}}, ["keyword"]),
    _tool("get_page_coach", "LLM internal linking coach for one URL.", {"url": _URL, "property_id": _PID, "report_id": _RID, "refresh": {"type": "boolean"}}, ["url"]),
    _tool("get_portfolio_summary", "Multi-property health score rollup.", {"limit": {"type": "integer", "maximum": 100}}),
    _tool("expand_keywords", "Expand seed keywords via Google Suggest.", {"property_id": _PID, "seeds": {"type": "array", "items": {"type": "string"}}, "sources": {"type": "array", "items": {"type": "string"}}}, ["seeds"]),
    # Export & deliverables
    _tool(
        "export_audit_report",
        "Export full audit report as PDF, HTML, CSV, or JSON. Returns download artifact metadata.",
        {"property_id": _PID, "report_id": _RID, "format": {"type": "string", "enum": ["pdf", "html", "csv", "json"]}},
    ),
    _tool(
        "export_compare_csv",
        "Export issue added/removed CSV diff between current and baseline report.",
        {"property_id": _PID, "report_id": _RID, "baseline_report_id": {"type": "integer"}},
        ["baseline_report_id"],
    ),
    _tool(
        "export_list_as_csv",
        "Export rows from an allowlisted list tool as CSV.",
        {
            "property_id": _PID,
            "report_id": _RID,
            "tool_name": {"type": "string"},
            "tool_args": {"type": "object"},
            "columns": {"type": "array", "items": {"type": "string"}},
            "limit": {"type": "integer", "maximum": 500},
        },
        ["tool_name"],
    ),
    _tool(
        "export_sitemap_xml",
        "Generate XML sitemap from indexable crawled URLs.",
        {"property_id": _PID, "report_id": _RID},
    ),
    _tool(
        "validate_rich_results",
        "Validate structured data / Rich Results for sample URLs (Estimated without API key).",
        {"property_id": _PID, "report_id": _RID, "limit": {"type": "integer", "maximum": 50}, "api_key": {"type": "string"}},
    ),
    _tool("list_export_formats", "List supported export tools, formats, and example prompts.", {}),
    # Image audit
    _tool("get_image_audit_summary", "Site-wide image audit totals: alt, lazy-load, dimensions, OG, Lighthouse image diagnostics.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_pages_without_lazy_images", "Pages with images not using loading=lazy.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_with_images_missing_dimensions", "Pages with images missing width/height (CLS risk).", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool(
        "list_site_image_urls",
        "Unique image URLs from crawl (on-page, OG, Twitter) with source page.",
        {"property_id": _PID, "report_id": _RID, "kind": {"type": "string", "enum": ["content", "og", "twitter"]}, "limit": {"type": "integer", "maximum": 100}},
    ),
    _tool("list_lighthouse_image_opportunities", "Lighthouse diagnostics related to images and LCP.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool(
        "list_largest_images",
        "Largest probed images by file size (requires probe_image_inventory on report build).",
        {"property_id": _PID, "report_id": _RID, "min_size_kb": {"type": "integer"}, "limit": {"type": "integer", "maximum": 100}},
    ),
    _tool(
        "list_unoptimized_images",
        "Large images not in WebP/AVIF (requires image inventory probe).",
        {"property_id": _PID, "report_id": _RID, "min_size_kb": {"type": "integer"}, "limit": {"type": "integer", "maximum": 100}},
    ),
    _tool(
        "list_images_needing_attention",
        "Ranked images/pages with composite attention reasons (size, format, alt/lazy/dimension issues).",
        {"property_id": _PID, "report_id": _RID, "min_size_kb": {"type": "integer"}, "limit": {"type": "integer", "maximum": 100}},
    ),
    # Impact prioritization
    _tool(
        "list_top_impact_issues",
        "Audit issues ranked by traffic-weighted impact_score (GSC clicks + GA4 sessions + priority).",
        {"property_id": _PID, "report_id": _RID, "priority": {"type": "string"}, "category_id": {"type": "string"}, "limit": _LIMIT},
    ),
    # Payload extras
    _tool("get_rich_results_summary", "Rich Results validation meta counts from report build.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_rich_results_failures", "URLs failing rich-results validation (status != pass).", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_competitor_keyword_gap", "Competitor keyword gap rows from competitor_keyword_gap_json config.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_portfolio_benchmark", "Property health vs portfolio median benchmark.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_site_anchor_text_summary", "Top sitewide inlink anchor texts from inlink_anchor_matrix.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_pagination_audit_summary", "rel=prev/next and AMP pairing issue counts from crawl.", {"property_id": _PID, "report_id": _RID}),
    # Crawl extras
    _tool("list_pages_soft_404", "2xx pages whose title suggests not-found (soft 404).", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_with_axe_violations", "Pages with axe-core accessibility violations (enable_axe crawl).", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_axe_audit_summary", "Site-wide axe violation counts by rule id.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_pages_with_mixed_content", "HTTPS pages with mixed HTTP content references.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_dead_end_pages", "Crawlable pages with inlinks but zero outlinks.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_duplicate_title_groups", "Groups of pages sharing the same title and meta description.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_heavy_pages_by_bytes", "Pages ranked by total JS + CSS bytes.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_poor_cache_headers", "Pages missing or weak cache-control / etag headers.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_low_content_ratio", "Pages with low content_html_ratio (bloated HTML).", {"property_id": _PID, "report_id": _RID, "max_content_html_ratio": {"type": "number"}, "limit": _LIMIT}),
    _tool("get_heading_outline_for_url", "Heading sequence and outline for one URL.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    # Crawl metrics
    _tool("get_asset_weight_summary", "JS/CSS bytes and script_count percentiles from crawl.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_readability_summary", "Reading level histogram and mean/median from crawl.", {"property_id": _PID, "report_id": _RID}),
    # CTR opportunities
    _tool("list_keywords_ctr_opportunity", "Keywords flagged for CTR improvement (title/meta).", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("get_gsc_ctr_opportunity_pages", "GSC pages with high impressions and below-curve CTR.", {"property_id": _PID, "min_impressions": {"type": "integer"}, "limit": _LIMIT}),
    # Compare extras
    _tool("compare_indexation_deltas", "Indexation coverage count and gap list changes vs baseline.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    _tool("compare_orphan_deltas", "Orphan URL set changes vs baseline report.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    # GEO / AEO
    _tool("get_llms_txt_status", "Check for /llms.txt and /.well-known/llms.txt with depth scoring (H1, blockquote, sections, links).", {"property_id": _PID, "report_id": _RID}),
    _tool("get_ai_discovery_status", "Check AI discovery endpoints: /.well-known/ai.txt, /ai/summary.json, /ai/faq.json, /ai/service.json.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_robots_ai_access_score", "Score robots.txt AI-bot access /18 with 27 bots across training/search/citation tiers.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_faq_schema_coverage", "FAQPage/QAPage schema coverage across crawled pages.", {"property_id": _PID, "report_id": _RID}),
    _tool("list_pages_missing_faq_schema", "Q&A-style URLs missing FAQ schema markup.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_geo_readiness_score", "8-category GEO readiness score (0-100) with score bands: Robots/18, llms.txt/18, Schema/16, Meta/14, Content/12, Brand/10, Signals/6, AI Discovery/6.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_aeo_content_signals_for_url", "Per-URL answer-engine quotability signals.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("get_eeat_signals_summary", "Author/Organization schema and about/contact page counts.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_js_rendering_delta", "Static vs rendered title/word-count differences.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_internal_link_suggestions", "TF-IDF related pages and anchor hints for a source URL.", {"url": _URL, "property_id": _PID, "report_id": _RID, "limit": {"type": "integer", "maximum": 10}}, ["url"]),
    _tool("get_citability_score", "Site-wide citability score (0-100) from 9 research-backed KDD/AutoGEO signals (quotations, stats, fluency, front-loading, lists, FAQ, headings, entities, depth).", {"property_id": _PID, "report_id": _RID}),
    _tool("get_citability_for_url", "Per-URL citability score and detailed signal breakdown.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("get_negative_signals", "Detect 7 anti-citation signals: CTA overload, thin content, keyword stuffing, popups, missing author, no structure, affiliate overload.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("detect_prompt_injection", "Detect 8 prompt-injection / content-manipulation patterns: hidden text, invisible Unicode, micro-font, LLM instructions, HTML comment injection, monochrome text, data-attr injection, aria-hidden abuse.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_rag_chunk_readiness", "Score RAG retrieval readiness: section sizes, heading boundaries, anchor sentences.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_content_decay_signals", "Detect temporal, statistical, version, event, and price decay patterns. Returns evergreen score 0-100.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_multimodal_readiness", "Check image alt coverage, VideoObject/AudioObject schema, transcript/subtitle signals for multimodal AI engines.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_topic_authority", "Multi-page entity clusters and pillar page detection via TF-IDF cosine similarity.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("compare_geo_score_deltas", "GEO readiness score drift between current and baseline report.", {"baseline_report_id": _RID, "report_id": _RID}, ["baseline_report_id"]),
    # LLM generators
    _tool("generate_issue_fix", "LLM fix suggestion for one audit issue message.", {"property_id": _PID, "message": {"type": "string"}, "url": _URL, "priority": {"type": "string"}, "category_id": {"type": "string"}, "refresh": {"type": "boolean"}}, ["message"]),
    _tool("summarize_category_for_client", "Client-friendly category summary with optional LLM narrative.", {"category_id": {"type": "string"}, "property_id": _PID, "report_id": _RID}, ["category_id"]),
    _tool("prioritize_fix_roadmap", "Top N issues ranked by impact_score for a fix roadmap.", {"property_id": _PID, "report_id": _RID, "limit": {"type": "integer", "maximum": 30}}),
    _tool("analyze_serp_snippet_for_url", "GSC query context plus LLM title/meta CTR suggestions.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("draft_llms_txt", "Draft llms.txt content from top pages and schema coverage.", {"property_id": _PID, "report_id": _RID}),
    _tool("generate_schema", "Generate JSON-LD schema markup (WebSite/Organization/FAQPage/Article) from crawl data.", {"property_id": _PID, "report_id": _RID, "schema_type": {"type": "string"}, "url": _URL}),
    _tool("generate_robots_txt", "Generate a robots.txt that explicitly allows all 27 AI citation/search/training bots.", {"property_id": _PID, "report_id": _RID}),
    _tool("generate_meta_tags", "Generate meta/OG tag HTML recommendations for a URL.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("generate_geo_fix_bundle", "Generate all missing GEO fix files: llms.txt, robots.txt, WebSite schema, Organization schema.", {"property_id": _PID, "report_id": _RID}),
    # Integrations
    _tool("get_gsc_url_inspection", "Live GSC URL Inspection (indexing + rich results). Requires Google OAuth.", {"url": _URL, "property_id": _PID}, ["url", "property_id"]),
    _tool("get_gsc_index_coverage", "Estimated indexation coverage from crawl + sitemap + GSC join.", {"property_id": _PID, "report_id": _RID}),
    _tool("get_bing_index_status", "Bing Webmaster URL info (requires bing_webmaster_api_key).", {"url": _URL, "property_id": _PID}, ["url", "property_id"]),
    _tool("get_serp_feature_overlay", "Keywords with SERP feature / competition overlay data.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("check_ai_citation_presence", "On-site citation readiness estimate for brand/query (no live LLM API).", {"property_id": _PID, "query": {"type": "string"}, "brand": {"type": "string"}}),
    _tool("check_ai_citations_live", "Live AI citation check via Perplexity/OpenAI/Anthropic/Groq (opt-in, BYO key). Reports brand-mentioned, domain-cited, and competitors-cited.", {"property_id": _PID, "brand": {"type": "string"}, "query": {"type": "string"}, "provider": {"type": "string"}, "api_key": {"type": "string"}, "opt_in": {"type": "boolean"}, "multi_query": {"type": "string"}}),
    # Router / Tier 0 (Cursor-style)
    _tool("search_audit_tools", "Search the audit tool catalog by keyword. Returns matching tool names to call next.", {"query": {"type": "string"}, "limit": {"type": "integer", "maximum": 50}}, ["query"]),
    _tool("list_tool_domains", "List SEO tool domains with counts and example prompts.", {}),
    _tool("get_data_coverage_report", "Report which integrations and optional audit data are populated for a property.", {"property_id": _PID}, ["property_id"]),
    _tool("run_insight_workflow", "Run insight workflow: type=traffic|landing_pages|priorities (default).", {"property_id": _PID, "report_id": _RID, "type": {"type": "string"}, "limit": _LIMIT}),
    _tool("run_technical_workflow", "Run technical workflow: report summary, critical issues, priority chart; optional baseline compare.", {"property_id": _PID, "report_id": _RID, "baseline_report_id": {"type": "integer"}}),
    _tool("run_keyword_workflow", "Run keyword workflow: brand split, striking distance, CTR opportunities.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("run_domain_agent", "Subagent-style: run up to max_steps tools in one domain for a task description.", {"property_id": _PID, "report_id": _RID, "task": {"type": "string"}, "domain": {"type": "string"}, "max_steps": {"type": "integer", "maximum": 8}}, ["task"]),
    # Cross-platform insight (Tier 0)
    _tool("get_landing_page_blended_table", "GSC clicks + GA4 sessions per landing page with opportunity quadrant.", {"property_id": _PID, "limit": {"type": "integer", "maximum": 100}, "min_impressions": {"type": "integer"}}, ["property_id"]),
    _tool("get_opportunity_matrix", "Landing pages grouped by rank vs conversion opportunity quadrants.", {"property_id": _PID, "limit": _LIMIT}, ["property_id"]),
    _tool("get_traffic_health_check", "GSC clicks vs GA4 sessions ratio and tracking health diagnosis.", {"property_id": _PID}, ["property_id"]),
    _tool("get_landing_page_full_diagnosis", "One URL: GSC+GA4 slice, crawl, issues, Lighthouse, composite score.", {"url": _URL, "property_id": _PID, "report_id": _RID}, ["url"]),
    _tool("get_issue_to_traffic_map", "Audit issues ranked by traffic-weighted impact with GSC/GA4 columns.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    # Google dimensions
    _tool("get_gsc_daily_trend", "GSC daily clicks/impressions trend from latest fetch.", {"property_id": _PID}, ["property_id"]),
    _tool("get_ga4_daily_trend", "GA4 daily sessions trend from latest fetch.", {"property_id": _PID}, ["property_id"]),
    _tool("get_ga4_by_device", "GA4 sessions breakdown by device category.", {"property_id": _PID}, ["property_id"]),
    _tool("get_ga4_by_channel", "GA4 sessions breakdown by channel.", {"property_id": _PID}, ["property_id"]),
    _tool("get_gsc_page_queries", "GSC queries for a single page URL (full by_page blob).", {"url": _URL, "property_id": _PID, "limit": _LIMIT}, ["url"]),
    # Keyword dimensions
    _tool("get_brand_keyword_split", "Branded vs non-branded keyword counts and samples.", {"property_id": _PID}, ["property_id"]),
    _tool("list_keywords_by_intent", "Keywords filtered by intent (informational, commercial, etc.).", {"property_id": _PID, "intent": {"type": "string"}, "limit": _LIMIT}, ["property_id", "intent"]),

    # --- 100 new audit tools (240→340) ---
    _tool("list_pages_title_too_short", "Pages with title shorter than SEO minimum.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_title_too_long", "Pages with title longer than SEO maximum.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_slow_response", "Pages with server response time above threshold.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_missing_html_lang", "Pages missing html lang attribute.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_invalid_viewport", "Pages missing or invalid viewport meta.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_color_contrast_failures", "Pages failing color contrast checks.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_high_reading_level", "Pages with high reading grade level.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_very_thin_content", "Pages with very low word count.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_hreflang_issue_pages", "Pages with hreflang cluster issues.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_missing_og_tags", "Pages missing Open Graph tags.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_missing_twitter_cards", "Pages missing Twitter card tags.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_invalid_json_ld", "Pages with invalid JSON-LD schema.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_mixed_language", "Pages with mixed-language content signals.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_orphan_hub_suggestions", "Suggested hub pages to link orphan URLs.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_lighthouse_failure_lcp", "URLs failing Lighthouse LCP audit.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_lighthouse_failure_inp", "URLs failing Lighthouse INP audit.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_lighthouse_failure_cls", "URLs failing Lighthouse CLS audit.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_lighthouse_failure_seo", "URLs failing Lighthouse SEO audit.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_pages_by_impressions", "GSC pages sorted by impressions.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_pages_by_clicks", "GSC pages sorted by clicks.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_queries_by_impressions", "GSC queries sorted by impressions.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_queries_by_clicks", "GSC queries sorted by clicks.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_ctr_underperformers", "Queries/pages with low CTR for position band.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_decaying_pages", "GSC pages with click decline vs prior period.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_decaying_queries", "GSC queries with click decline vs prior period.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_new_queries", "New GSC queries vs prior period.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_ga4_landing_pages", "GA4 landing pages by sessions.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_ga4_pages_by_bounce_rate", "GA4 pages with high bounce rate.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_ga4_pages_by_engagement_rate", "GA4 pages sorted by engagement rate.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("get_gsc_query_trend", "Daily GSC clicks/impressions for one query.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "query": {'type': 'string'}}, ['query']),
    _tool("get_gsc_page_trend", "Daily GSC clicks/impressions for one URL.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "url": {'type': 'string', 'description': 'Page URL'}}, ['url']),
    _tool("get_ga4_path_trend", "GA4 sessions trend for one path.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "path": {'type': 'string'}}, ['path']),
    _tool("list_gsc_ga4_mismatch_pages", "High GSC clicks but low GA4 sessions.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_pages_by_position_band", "GSC pages in position range.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "min_position": {'type': 'number'}, "max_position": {'type': 'number'}}),
    _tool("get_gsc_site_benchmarks", "Sitewide median CTR and position benchmarks.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_branded_queries", "Branded GSC queries.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_gsc_non_branded_queries", "Non-branded GSC queries.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("compare_gsc_periods", "GSC summary delta vs prior Google snapshot.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_keyword_rank_improvements", "Keywords with improved position vs prior snapshot.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keyword_rank_declines", "Keywords with declined position vs prior snapshot.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keywords_new_to_top_10", "Keywords newly in top 10.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keywords_fell_out_of_top_10", "Keywords that fell out of top 10.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_cannibalisation_queries", "Queries with multiple ranking URLs.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_cannibalisation_urls", "URLs involved in keyword cannibalisation.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_misaligned_queries", "Queries landing on misaligned URLs.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keywords_by_recommended_action", "Keywords filtered by recommended_action.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "recommended_action": {'type': 'string'}}, ['property_id']),
    _tool("list_keywords_by_serp_feature", "Keywords with given SERP feature.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "serp_feature": {'type': 'string'}}, ['property_id']),
    _tool("list_semantic_cluster_queries", "Queries in a semantic keyword cluster.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "cluster_id": {'type': 'string'}}),
    _tool("list_semantic_cluster_pages", "Pages in a semantic keyword cluster.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "cluster_id": {'type': 'string'}}),
    _tool("get_keyword_opportunity_score", "Composite opportunity score for one keyword.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "keyword": {'type': 'string'}}, ['keyword', 'property_id']),
    _tool("list_keywords_near_page_one", "Keywords in striking-distance position band.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keywords_high_impression_zero_click", "High-impression keywords with zero clicks.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keywords_by_competition_band", "Keywords by SERP competition band.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "min_competition": {'type': 'number'}, "max_competition": {'type': 'number'}}, ['property_id']),
    _tool("get_keyword_serp_snapshot", "SERP overlay fields for one keyword.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "keyword": {'type': 'string'}}, ['keyword', 'property_id']),
    _tool("list_keywords_with_ai_overview", "Keywords triggering AI overview SERP features.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keywords_local_pack", "Keywords with local pack SERP feature.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keywords_question_intent", "Question-intent keywords.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_keywords_commercial_intent", "Commercial-intent keywords.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_referring_domains", "Top referring domains from GSC Links.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("list_backlinks_by_anchor_text", "Backlinks filtered by anchor text.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "anchor_text": {'type': 'string'}}, ['property_id']),
    _tool("list_backlinks_to_url", "Inbound links to target URL.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "url": {'type': 'string', 'description': 'Target URL'}}, ['url', 'property_id']),
    _tool("list_backlinks_from_domain", "Backlinks from referring domain.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "domain": {'type': 'string'}}, ['domain', 'property_id']),
    _tool("get_anchor_text_distribution", "Sitewide anchor text frequency from GSC Links.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}, ['property_id']),
    _tool("get_text_content_analysis", "Sitewide text content analysis summary.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_containing_keyword", "Pages containing keyword in body.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "keyword": {'type': 'string'}}, ['keyword']),
    _tool("list_pages_by_word_count_band", "Pages filtered by word count range.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "min_words": {'type': 'integer'}, "max_words": {'type': 'integer'}}),
    _tool("list_duplicate_content_pairs", "Near-duplicate content pairs.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_spell_check_issues", "Spell-check optional audit issues.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_html_validation_issues", "HTML validation optional audit issues.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_amp_validation_issues", "AMP validation optional audit issues.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pagination_issues", "Pagination optional audit issues.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_schema_errors_by_type", "Schema validation errors by type.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "schema_type": {'type': 'string'}}),
    _tool("list_pages_missing_article_schema", "Article/blog URLs missing Article schema.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_outbound_links", "Outbound links from crawl graph.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_internal_links_from_url", "Internal outlinks from source URL.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "url": {'type': 'string', 'description': 'Source URL'}}, ['url']),
    _tool("list_internal_links_to_url", "Internal inlinks to target URL.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "url": {'type': 'string', 'description': 'Target URL'}}, ['url']),
    _tool("list_links_by_rel_nofollow", "Links filtered by rel attribute.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "rel": {'type': 'string'}}),
    _tool("list_pagerank_low_pages", "Pages with lowest internal PageRank.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "max_pagerank": {'type': 'number'}}),
    _tool("list_indexation_submitted_not_indexed", "URLs submitted but not indexed.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_indexation_indexed_not_submitted", "Indexed URLs not in sitemap.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_sitemap_urls_not_in_crawl", "Sitemap URLs missing from crawl.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_crawl_urls_not_in_sitemap", "Crawled URLs missing from sitemap.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_log_paths_by_hits", "Access log paths ranked by hits.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_log_5xx_paths", "Access log paths with 5xx responses.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_log_googlebot_low_crawl", "High-value paths under-crawled by Googlebot.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_log_orphan_high_traffic", "Orphan URLs with high log traffic.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_redirect_chains_by_length", "Redirect chains above min_length.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "min_length": {'type': 'integer'}}),
    _tool("list_hreflang_reciprocal_gaps", "Hreflang alternates missing reciprocal return tags.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_compare_new_issues", "Issues new since baseline report.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "baseline_report_id": {'type': 'integer', 'description': 'Baseline report ID'}}, ['baseline_report_id']),
    _tool("list_compare_resolved_issues", "Issues resolved since baseline report.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "baseline_report_id": {'type': 'integer', 'description': 'Baseline report ID'}}, ['baseline_report_id']),
    _tool("list_compare_new_urls", "URLs new since baseline crawl.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "baseline_report_id": {'type': 'integer', 'description': 'Baseline report ID'}}, ['baseline_report_id']),
    _tool("list_compare_removed_urls", "URLs removed since baseline crawl.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "baseline_report_id": {'type': 'integer', 'description': 'Baseline report ID'}}, ['baseline_report_id']),
    _tool("list_compare_lighthouse_regressions", "Lighthouse score regressions vs baseline.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "baseline_report_id": {'type': 'integer', 'description': 'Baseline report ID'}}, ['baseline_report_id']),
    _tool("list_compare_traffic_losers", "GSC click losers vs baseline report.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "baseline_report_id": {'type': 'integer', 'description': 'Baseline report ID'}}, ['baseline_report_id']),
    _tool("list_pages_missing_howto_schema", "How-to URLs missing HowTo schema.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_ai_citation_signals", "Pages with AEO/AI citation readiness signals.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_missing_llms_txt_reference", "Pages not referenced in llms.txt.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_robots_blocked_ai_crawlers", "Pages blocking AI crawler user-agents.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
    _tool("list_pages_console_errors_by_type", "Console errors filtered by error_type.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT, "error_type": {'type': 'string'}}),
    _tool("list_pages_js_rendering_delta", "URLs with static vs rendered content delta.", {"property_id": _PID, "report_id": _RID, "limit": _LIMIT}),
]
