<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <RootNamespace>WebsiteProfiling.TypedConfig</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\WebsiteProfiling.Contracts\WebsiteProfiling.Contracts.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Npgsql" Version="10.0.1" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\..\..\config\typed_config_manifest.json" Link="config\typed_config_manifest.json" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
