// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://openapi.json` | (string & {});
};

/**
 * AppSettingBody
 */
export type AppSettingBody = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
};

/**
 * AuditToolBody
 */
export type AuditToolBody = {
    /**
     * Toolname
     */
    toolName: string;
    /**
     * Propertyid
     */
    propertyId: number;
    /**
     * Reportid
     */
    reportId?: number | null;
    /**
     * Args
     */
    args?: {
        [key: string]: unknown;
    };
};

/**
 * Body_logs_upload_api_logs_upload_post
 */
export type BodyLogsUploadApiLogsUploadPost = {
    /**
     * Propertyid
     */
    propertyId: number;
    /**
     * File
     */
    file: Blob | File;
};

/**
 * CancelResponse
 */
export type CancelResponse = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Status
     */
    status: string;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * CompareExportBody
 */
export type CompareExportBody = {
    /**
     * Reportida
     */
    reportIdA?: number | null;
    /**
     * Reportidb
     */
    reportIdB?: number | null;
};

/**
 * DashboardAiGenerateBody
 */
export type DashboardAiGenerateBody = {
    /**
     * Mode
     */
    mode: string;
    /**
     * Prompt
     */
    prompt: string;
    /**
     * Catalog
     */
    catalog: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Viz Types
     */
    viz_types: {
        [key: string]: string;
    };
    /**
     * Dashscript Help
     */
    dashscript_help: string;
    /**
     * Toolname
     */
    toolName?: string | null;
    /**
     * Propertyid
     */
    propertyId?: number | null;
    /**
     * Reportid
     */
    reportId?: number | null;
    /**
     * Current
     */
    current?: unknown | null;
    /**
     * Sample
     */
    sample?: {
        [key: string]: unknown;
    } | null;
};

/**
 * DashboardCreateBody
 */
export type DashboardCreateBody = {
    /**
     * Propertyid
     */
    propertyId: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Layoutjson
     */
    layoutJson?: unknown | null;
};

/**
 * DashboardUpdateBody
 */
export type DashboardUpdateBody = {
    /**
     * Propertyid
     */
    propertyId: number;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Layoutjson
     */
    layoutJson?: unknown | null;
    /**
     * Isdefault
     */
    isDefault?: boolean | null;
};

/**
 * GoogleCredentialsPatch
 */
export type GoogleCredentialsPatch = {
    /**
     * Refreshtoken
     */
    refreshToken?: string | null;
    /**
     * Authmode
     */
    authMode?: string | null;
    /**
     * Gscsiteurl
     */
    gscSiteUrl?: string | null;
    /**
     * Ga4Propertyid
     */
    ga4PropertyId?: string | null;
    /**
     * Daterangedays
     */
    dateRangeDays?: number | null;
    /**
     * Connectedemail
     */
    connectedEmail?: string | null;
};

/**
 * GoogleCredentialsPostBody
 */
export type GoogleCredentialsPostBody = {
    /**
     * Gscsiteurl
     */
    gscSiteUrl?: string | null;
    /**
     * Ga4Propertyid
     */
    ga4PropertyId?: string | null;
    /**
     * Daterangedays
     */
    dateRangeDays?: number | null;
    /**
     * Refreshtoken
     */
    refreshToken?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * JobsListResponse
 */
export type JobsListResponse = {
    /**
     * Jobs
     */
    jobs: Array<{
        [key: string]: unknown;
    }>;
    /**
     * Active
     */
    active?: {
        [key: string]: unknown;
    } | null;
    /**
     * Reconciled
     */
    reconciled?: number;
};

/**
 * OpsSettingsBody
 */
export type OpsSettingsBody = {
    /**
     * Schedulecron
     */
    scheduleCron?: string | null;
    /**
     * Alertwebhookurl
     */
    alertWebhookUrl?: string | null;
    /**
     * Alertemail
     */
    alertEmail?: string | null;
};

/**
 * PauseResponse
 */
export type PauseResponse = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * PipelineConfigBody
 */
export type PipelineConfigBody = {
    /**
     * State
     */
    state: {
        [key: string]: unknown;
    };
    /**
     * Unknownkeys
     */
    unknownKeys?: Array<{
        [key: string]: string;
    }> | null;
};

/**
 * PresetBody
 */
export type PresetBody = {
    /**
     * Preset
     */
    preset?: string | null;
};

/**
 * PropertyUpsertBody
 */
export type PropertyUpsertBody = {
    /**
     * Name
     */
    name?: string | null;
    /**
     * Canonical Domain
     */
    canonical_domain?: string | null;
    /**
     * Site Url
     */
    site_url?: string | null;
};

/**
 * ResumeResponse
 */
export type ResumeResponse = {
    /**
     * Ok
     */
    ok: boolean;
    /**
     * Newjobid
     */
    newJobId?: string | null;
    /**
     * Error
     */
    error?: string | null;
};

/**
 * RunPostBody
 */
export type RunPostBody = {
    /**
     * Command
     */
    command?: string | null;
    /**
     * State
     */
    state?: {
        [key: string]: unknown;
    } | null;
    /**
     * Unknownkeys
     */
    unknownKeys?: Array<UnknownKeyEntry>;
    /**
     * Propertyid
     */
    propertyId?: number | null;
    /**
     * Python
     */
    python?: string | null;
    /**
     * Reporoot
     */
    repoRoot?: string | null;
};

/**
 * RunResponse
 */
export type RunResponse = {
    /**
     * Jobid
     */
    jobId: string;
};

/**
 * UnknownKeyEntry
 */
export type UnknownKeyEntry = {
    /**
     * Key
     */
    key: string;
    /**
     * Value
     */
    value: string;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
    /**
     * Input
     */
    input?: unknown;
    /**
     * Context
     */
    ctx?: {
        [key: string]: unknown;
    };
};

export type HealthCheckApiHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/health';
};

export type HealthCheckApiHealthGetResponses = {
    /**
     * Response Health Check Api Health Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type HealthCheckApiHealthGetResponse = HealthCheckApiHealthGetResponses[keyof HealthCheckApiHealthGetResponses];

export type RunPipelineApiRunPostData = {
    body: RunPostBody;
    path?: never;
    query?: never;
    url: '/api/run';
};

export type RunPipelineApiRunPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunPipelineApiRunPostError = RunPipelineApiRunPostErrors[keyof RunPipelineApiRunPostErrors];

export type RunPipelineApiRunPostResponses = {
    /**
     * Successful Response
     */
    200: RunResponse;
};

export type RunPipelineApiRunPostResponse = RunPipelineApiRunPostResponses[keyof RunPipelineApiRunPostResponses];

export type ListPipelineJobsApiJobsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/jobs';
};

export type ListPipelineJobsApiJobsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPipelineJobsApiJobsGetError = ListPipelineJobsApiJobsGetErrors[keyof ListPipelineJobsApiJobsGetErrors];

export type ListPipelineJobsApiJobsGetResponses = {
    /**
     * Successful Response
     */
    200: JobsListResponse;
};

export type ListPipelineJobsApiJobsGetResponse = ListPipelineJobsApiJobsGetResponses[keyof ListPipelineJobsApiJobsGetResponses];

export type GetPipelineJobApiJobsJobIdGetData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}';
};

export type GetPipelineJobApiJobsJobIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPipelineJobApiJobsJobIdGetError = GetPipelineJobApiJobsJobIdGetErrors[keyof GetPipelineJobApiJobsJobIdGetErrors];

export type GetPipelineJobApiJobsJobIdGetResponses = {
    /**
     * Response Get Pipeline Job Api Jobs  Job Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPipelineJobApiJobsJobIdGetResponse = GetPipelineJobApiJobsJobIdGetResponses[keyof GetPipelineJobApiJobsJobIdGetResponses];

export type CancelPipelineJobApiJobsJobIdCancelPostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/cancel';
};

export type CancelPipelineJobApiJobsJobIdCancelPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CancelPipelineJobApiJobsJobIdCancelPostError = CancelPipelineJobApiJobsJobIdCancelPostErrors[keyof CancelPipelineJobApiJobsJobIdCancelPostErrors];

export type CancelPipelineJobApiJobsJobIdCancelPostResponses = {
    /**
     * Successful Response
     */
    200: CancelResponse;
};

export type CancelPipelineJobApiJobsJobIdCancelPostResponse = CancelPipelineJobApiJobsJobIdCancelPostResponses[keyof CancelPipelineJobApiJobsJobIdCancelPostResponses];

export type PausePipelineJobApiJobsJobIdPausePostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/pause';
};

export type PausePipelineJobApiJobsJobIdPausePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PausePipelineJobApiJobsJobIdPausePostError = PausePipelineJobApiJobsJobIdPausePostErrors[keyof PausePipelineJobApiJobsJobIdPausePostErrors];

export type PausePipelineJobApiJobsJobIdPausePostResponses = {
    /**
     * Successful Response
     */
    200: PauseResponse;
};

export type PausePipelineJobApiJobsJobIdPausePostResponse = PausePipelineJobApiJobsJobIdPausePostResponses[keyof PausePipelineJobApiJobsJobIdPausePostResponses];

export type ResumePipelineJobApiJobsJobIdResumePostData = {
    body?: never;
    path: {
        /**
         * Job Id
         */
        job_id: string;
    };
    query?: never;
    url: '/api/jobs/{job_id}/resume';
};

export type ResumePipelineJobApiJobsJobIdResumePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResumePipelineJobApiJobsJobIdResumePostError = ResumePipelineJobApiJobsJobIdResumePostErrors[keyof ResumePipelineJobApiJobsJobIdResumePostErrors];

export type ResumePipelineJobApiJobsJobIdResumePostResponses = {
    /**
     * Successful Response
     */
    200: ResumeResponse;
};

export type ResumePipelineJobApiJobsJobIdResumePostResponse = ResumePipelineJobApiJobsJobIdResumePostResponses[keyof ResumePipelineJobApiJobsJobIdResumePostResponses];

export type BrowserStatusCheckApiCrawlBrowserStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/crawl/browser-status';
};

export type BrowserStatusCheckApiCrawlBrowserStatusGetResponses = {
    /**
     * Response Browser Status Check Api Crawl Browser Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BrowserStatusCheckApiCrawlBrowserStatusGetResponse = BrowserStatusCheckApiCrawlBrowserStatusGetResponses[keyof BrowserStatusCheckApiCrawlBrowserStatusGetResponses];

export type GetPageHtmlApiCrawlPageHtmlGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         *
         * Page URL to retrieve stored HTML for
         */
        url: string;
        /**
         * Crawlrunid
         *
         * Crawl run ID
         */
        crawlRunId?: number | null;
    };
    url: '/api/crawl/page-html';
};

export type GetPageHtmlApiCrawlPageHtmlGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPageHtmlApiCrawlPageHtmlGetError = GetPageHtmlApiCrawlPageHtmlGetErrors[keyof GetPageHtmlApiCrawlPageHtmlGetErrors];

export type GetPageHtmlApiCrawlPageHtmlGetResponses = {
    /**
     * Response Get Page Html Api Crawl Page Html Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPageHtmlApiCrawlPageHtmlGetResponse = GetPageHtmlApiCrawlPageHtmlGetResponses[keyof GetPageHtmlApiCrawlPageHtmlGetResponses];

export type GetPipelineConfigApiPipelineConfigGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/pipeline-config';
};

export type GetPipelineConfigApiPipelineConfigGetResponses = {
    /**
     * Response Get Pipeline Config Api Pipeline Config Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPipelineConfigApiPipelineConfigGetResponse = GetPipelineConfigApiPipelineConfigGetResponses[keyof GetPipelineConfigApiPipelineConfigGetResponses];

export type PutPipelineConfigApiPipelineConfigPutData = {
    body: PipelineConfigBody;
    path?: never;
    query?: never;
    url: '/api/pipeline-config';
};

export type PutPipelineConfigApiPipelineConfigPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutPipelineConfigApiPipelineConfigPutError = PutPipelineConfigApiPipelineConfigPutErrors[keyof PutPipelineConfigApiPipelineConfigPutErrors];

export type PutPipelineConfigApiPipelineConfigPutResponses = {
    /**
     * Response Put Pipeline Config Api Pipeline Config Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PutPipelineConfigApiPipelineConfigPutResponse = PutPipelineConfigApiPipelineConfigPutResponses[keyof PutPipelineConfigApiPipelineConfigPutResponses];

export type GetAppSettingApiAppSettingsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Key
         *
         * Settings key to retrieve
         */
        key: string;
    };
    url: '/api/app-settings';
};

export type GetAppSettingApiAppSettingsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetAppSettingApiAppSettingsGetError = GetAppSettingApiAppSettingsGetErrors[keyof GetAppSettingApiAppSettingsGetErrors];

export type GetAppSettingApiAppSettingsGetResponses = {
    /**
     * Response Get App Setting Api App Settings Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetAppSettingApiAppSettingsGetResponse = GetAppSettingApiAppSettingsGetResponses[keyof GetAppSettingApiAppSettingsGetResponses];

export type PutAppSettingApiAppSettingsPutData = {
    body: AppSettingBody;
    path?: never;
    query?: never;
    url: '/api/app-settings';
};

export type PutAppSettingApiAppSettingsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PutAppSettingApiAppSettingsPutError = PutAppSettingApiAppSettingsPutErrors[keyof PutAppSettingApiAppSettingsPutErrors];

export type PutAppSettingApiAppSettingsPutResponses = {
    /**
     * Response Put App Setting Api App Settings Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PutAppSettingApiAppSettingsPutResponse = PutAppSettingApiAppSettingsPutResponses[keyof PutAppSettingApiAppSettingsPutResponses];

export type ListPropertiesApiPropertiesGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/properties';
};

export type ListPropertiesApiPropertiesGetResponses = {
    /**
     * Response List Properties Api Properties Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListPropertiesApiPropertiesGetResponse = ListPropertiesApiPropertiesGetResponses[keyof ListPropertiesApiPropertiesGetResponses];

export type CreatePropertyApiPropertiesPostData = {
    body: PropertyUpsertBody;
    path?: never;
    query?: never;
    url: '/api/properties';
};

export type CreatePropertyApiPropertiesPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreatePropertyApiPropertiesPostError = CreatePropertyApiPropertiesPostErrors[keyof CreatePropertyApiPropertiesPostErrors];

export type CreatePropertyApiPropertiesPostResponses = {
    /**
     * Response Create Property Api Properties Post
     *
     * Successful Response
     */
    201: {
        [key: string]: unknown;
    };
};

export type CreatePropertyApiPropertiesPostResponse = CreatePropertyApiPropertiesPostResponses[keyof CreatePropertyApiPropertiesPostResponses];

export type ResolvePropertyApiPropertiesResolveGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Starturl
         *
         * Start URL to resolve a property from
         */
        startUrl: string;
    };
    url: '/api/properties/resolve';
};

export type ResolvePropertyApiPropertiesResolveGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResolvePropertyApiPropertiesResolveGetError = ResolvePropertyApiPropertiesResolveGetErrors[keyof ResolvePropertyApiPropertiesResolveGetErrors];

export type ResolvePropertyApiPropertiesResolveGetResponses = {
    /**
     * Response Resolve Property Api Properties Resolve Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ResolvePropertyApiPropertiesResolveGetResponse = ResolvePropertyApiPropertiesResolveGetResponses[keyof ResolvePropertyApiPropertiesResolveGetResponses];

export type DeletePropertyRouteApiPropertiesPropertyIdDeleteData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}';
};

export type DeletePropertyRouteApiPropertiesPropertyIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePropertyRouteApiPropertiesPropertyIdDeleteError = DeletePropertyRouteApiPropertiesPropertyIdDeleteErrors[keyof DeletePropertyRouteApiPropertiesPropertyIdDeleteErrors];

export type DeletePropertyRouteApiPropertiesPropertyIdDeleteResponses = {
    /**
     * Response Delete Property Route Api Properties  Property Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeletePropertyRouteApiPropertiesPropertyIdDeleteResponse = DeletePropertyRouteApiPropertiesPropertyIdDeleteResponses[keyof DeletePropertyRouteApiPropertiesPropertyIdDeleteResponses];

export type GetPropertyApiPropertiesPropertyIdGetData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}';
};

export type GetPropertyApiPropertiesPropertyIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropertyApiPropertiesPropertyIdGetError = GetPropertyApiPropertiesPropertyIdGetErrors[keyof GetPropertyApiPropertiesPropertyIdGetErrors];

export type GetPropertyApiPropertiesPropertyIdGetResponses = {
    /**
     * Response Get Property Api Properties  Property Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPropertyApiPropertiesPropertyIdGetResponse = GetPropertyApiPropertiesPropertyIdGetResponses[keyof GetPropertyApiPropertiesPropertyIdGetResponses];

export type GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/ops';
};

export type GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetError = GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetErrors[keyof GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetErrors];

export type GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetResponses = {
    /**
     * Response Get Property Ops Route Api Properties  Property Id  Ops Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetResponse = GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetResponses[keyof GetPropertyOpsRouteApiPropertiesPropertyIdOpsGetResponses];

export type UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutData = {
    body: OpsSettingsBody;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/ops';
};

export type UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutError = UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutErrors[keyof UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutErrors];

export type UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutResponses = {
    /**
     * Response Update Property Ops Route Api Properties  Property Id  Ops Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutResponse = UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutResponses[keyof UpdatePropertyOpsRouteApiPropertiesPropertyIdOpsPutResponses];

export type GetPropertyPresetApiPropertiesPropertyIdPresetGetData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/preset';
};

export type GetPropertyPresetApiPropertiesPropertyIdPresetGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetPropertyPresetApiPropertiesPropertyIdPresetGetError = GetPropertyPresetApiPropertiesPropertyIdPresetGetErrors[keyof GetPropertyPresetApiPropertiesPropertyIdPresetGetErrors];

export type GetPropertyPresetApiPropertiesPropertyIdPresetGetResponses = {
    /**
     * Response Get Property Preset Api Properties  Property Id  Preset Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetPropertyPresetApiPropertiesPropertyIdPresetGetResponse = GetPropertyPresetApiPropertiesPropertyIdPresetGetResponses[keyof GetPropertyPresetApiPropertiesPropertyIdPresetGetResponses];

export type UpdatePropertyPresetApiPropertiesPropertyIdPresetPutData = {
    body: PresetBody;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/preset';
};

export type UpdatePropertyPresetApiPropertiesPropertyIdPresetPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdatePropertyPresetApiPropertiesPropertyIdPresetPutError = UpdatePropertyPresetApiPropertiesPropertyIdPresetPutErrors[keyof UpdatePropertyPresetApiPropertiesPropertyIdPresetPutErrors];

export type UpdatePropertyPresetApiPropertiesPropertyIdPresetPutResponses = {
    /**
     * Response Update Property Preset Api Properties  Property Id  Preset Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdatePropertyPresetApiPropertiesPropertyIdPresetPutResponse = UpdatePropertyPresetApiPropertiesPropertyIdPresetPutResponses[keyof UpdatePropertyPresetApiPropertiesPropertyIdPresetPutResponses];

export type AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/authorize';
};

export type AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostError = AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostErrors[keyof AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostErrors];

export type AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostResponses = {
    /**
     * Response Authorize Property Crawl Route Api Properties  Property Id  Authorize Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostResponse = AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostResponses[keyof AuthorizePropertyCrawlRouteApiPropertiesPropertyIdAuthorizePostResponses];

export type PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/google/status';
};

export type PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetError = PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetErrors[keyof PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetErrors];

export type PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetResponses = {
    /**
     * Response Property Google Status Api Properties  Property Id  Google Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetResponse = PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetResponses[keyof PropertyGoogleStatusApiPropertiesPropertyIdGoogleStatusGetResponses];

export type PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/google/test';
};

export type PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostError = PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostErrors[keyof PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostErrors];

export type PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostResponses = {
    /**
     * Response Property Google Test Api Properties  Property Id  Google Test Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostResponse = PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostResponses[keyof PropertyGoogleTestApiPropertiesPropertyIdGoogleTestPostResponses];

export type PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/google/properties';
};

export type PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetError = PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetErrors[keyof PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetErrors];

export type PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetResponses = {
    /**
     * Response Property Google Properties Api Properties  Property Id  Google Properties Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetResponse = PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetResponses[keyof PropertyGooglePropertiesApiPropertiesPropertyIdGooglePropertiesGetResponses];

export type PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/google/links/status';
};

export type PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetError = PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetErrors[keyof PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetErrors];

export type PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetResponses = {
    /**
     * Response Property Google Links Status Api Properties  Property Id  Google Links Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetResponse = PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetResponses[keyof PropertyGoogleLinksStatusApiPropertiesPropertyIdGoogleLinksStatusGetResponses];

export type PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/google/links/import';
};

export type PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostError = PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostErrors[keyof PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostErrors];

export type PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostResponses = {
    /**
     * Response Property Google Links Import Api Properties  Property Id  Google Links Import Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostResponse = PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostResponses[keyof PropertyGoogleLinksImportApiPropertiesPropertyIdGoogleLinksImportPostResponses];

export type PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchData = {
    body: GoogleCredentialsPatch;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/google/credentials';
};

export type PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchError = PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchErrors[keyof PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchErrors];

export type PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchResponses = {
    /**
     * Response Patch Property Google Credentials Api Properties  Property Id  Google Credentials Patch
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchResponse = PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchResponses[keyof PatchPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPatchResponses];

export type PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostData = {
    body: GoogleCredentialsPostBody;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/google/credentials';
};

export type PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostError = PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostErrors[keyof PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostErrors];

export type PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostResponses = {
    /**
     * Response Post Property Google Credentials Api Properties  Property Id  Google Credentials Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostResponse = PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostResponses[keyof PostPropertyGoogleCredentialsApiPropertiesPropertyIdGoogleCredentialsPostResponses];

export type PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostData = {
    body?: never;
    path: {
        /**
         * Property Id
         */
        property_id: number;
    };
    query?: never;
    url: '/api/properties/{property_id}/google/disconnect';
};

export type PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostError = PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostErrors[keyof PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostErrors];

export type PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostResponses = {
    /**
     * Response Post Property Google Disconnect Api Properties  Property Id  Google Disconnect Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostResponse = PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostResponses[keyof PostPropertyGoogleDisconnectApiPropertiesPropertyIdGoogleDisconnectPostResponses];

export type ListDashboardsApiDashboardsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Propertyid
         *
         * Property ID
         */
        propertyId: number;
    };
    url: '/api/dashboards';
};

export type ListDashboardsApiDashboardsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListDashboardsApiDashboardsGetError = ListDashboardsApiDashboardsGetErrors[keyof ListDashboardsApiDashboardsGetErrors];

export type ListDashboardsApiDashboardsGetResponses = {
    /**
     * Response List Dashboards Api Dashboards Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListDashboardsApiDashboardsGetResponse = ListDashboardsApiDashboardsGetResponses[keyof ListDashboardsApiDashboardsGetResponses];

export type CreateDashboardApiDashboardsPostData = {
    body: DashboardCreateBody;
    path?: never;
    query?: never;
    url: '/api/dashboards';
};

export type CreateDashboardApiDashboardsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDashboardApiDashboardsPostError = CreateDashboardApiDashboardsPostErrors[keyof CreateDashboardApiDashboardsPostErrors];

export type CreateDashboardApiDashboardsPostResponses = {
    /**
     * Response Create Dashboard Api Dashboards Post
     *
     * Successful Response
     */
    201: {
        [key: string]: unknown;
    };
};

export type CreateDashboardApiDashboardsPostResponse = CreateDashboardApiDashboardsPostResponses[keyof CreateDashboardApiDashboardsPostResponses];

export type DeleteDashboardApiDashboardsDashboardIdDeleteData = {
    body?: never;
    path: {
        /**
         * Dashboard Id
         */
        dashboard_id: number;
    };
    query: {
        /**
         * Propertyid
         *
         * Property ID
         */
        propertyId: number;
    };
    url: '/api/dashboards/{dashboard_id}';
};

export type DeleteDashboardApiDashboardsDashboardIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDashboardApiDashboardsDashboardIdDeleteError = DeleteDashboardApiDashboardsDashboardIdDeleteErrors[keyof DeleteDashboardApiDashboardsDashboardIdDeleteErrors];

export type DeleteDashboardApiDashboardsDashboardIdDeleteResponses = {
    /**
     * Response Delete Dashboard Api Dashboards  Dashboard Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteDashboardApiDashboardsDashboardIdDeleteResponse = DeleteDashboardApiDashboardsDashboardIdDeleteResponses[keyof DeleteDashboardApiDashboardsDashboardIdDeleteResponses];

export type GetDashboardApiDashboardsDashboardIdGetData = {
    body?: never;
    path: {
        /**
         * Dashboard Id
         */
        dashboard_id: number;
    };
    query: {
        /**
         * Propertyid
         *
         * Property ID
         */
        propertyId: number;
    };
    url: '/api/dashboards/{dashboard_id}';
};

export type GetDashboardApiDashboardsDashboardIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetDashboardApiDashboardsDashboardIdGetError = GetDashboardApiDashboardsDashboardIdGetErrors[keyof GetDashboardApiDashboardsDashboardIdGetErrors];

export type GetDashboardApiDashboardsDashboardIdGetResponses = {
    /**
     * Response Get Dashboard Api Dashboards  Dashboard Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetDashboardApiDashboardsDashboardIdGetResponse = GetDashboardApiDashboardsDashboardIdGetResponses[keyof GetDashboardApiDashboardsDashboardIdGetResponses];

export type UpdateDashboardApiDashboardsDashboardIdPutData = {
    body: DashboardUpdateBody;
    path: {
        /**
         * Dashboard Id
         */
        dashboard_id: number;
    };
    query?: never;
    url: '/api/dashboards/{dashboard_id}';
};

export type UpdateDashboardApiDashboardsDashboardIdPutErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateDashboardApiDashboardsDashboardIdPutError = UpdateDashboardApiDashboardsDashboardIdPutErrors[keyof UpdateDashboardApiDashboardsDashboardIdPutErrors];

export type UpdateDashboardApiDashboardsDashboardIdPutResponses = {
    /**
     * Response Update Dashboard Api Dashboards  Dashboard Id  Put
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateDashboardApiDashboardsDashboardIdPutResponse = UpdateDashboardApiDashboardsDashboardIdPutResponses[keyof UpdateDashboardApiDashboardsDashboardIdPutResponses];

export type DashboardsAiGenerateApiDashboardsAiGeneratePostData = {
    body: DashboardAiGenerateBody;
    path?: never;
    query?: never;
    url: '/api/dashboards/ai-generate';
};

export type DashboardsAiGenerateApiDashboardsAiGeneratePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DashboardsAiGenerateApiDashboardsAiGeneratePostError = DashboardsAiGenerateApiDashboardsAiGeneratePostErrors[keyof DashboardsAiGenerateApiDashboardsAiGeneratePostErrors];

export type DashboardsAiGenerateApiDashboardsAiGeneratePostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type GetGoogleCredentialsApiIntegrationsGoogleCredentialsGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/google/credentials';
};

export type GetGoogleCredentialsApiIntegrationsGoogleCredentialsGetResponses = {
    /**
     * Response Get Google Credentials Api Integrations Google Credentials Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetGoogleCredentialsApiIntegrationsGoogleCredentialsGetResponse = GetGoogleCredentialsApiIntegrationsGoogleCredentialsGetResponses[keyof GetGoogleCredentialsApiIntegrationsGoogleCredentialsGetResponses];

export type GoogleStatusApiIntegrationsGoogleStatusGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/google/status';
};

export type GoogleStatusApiIntegrationsGoogleStatusGetResponses = {
    /**
     * Response Google Status Api Integrations Google Status Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleStatusApiIntegrationsGoogleStatusGetResponse = GoogleStatusApiIntegrationsGoogleStatusGetResponses[keyof GoogleStatusApiIntegrationsGoogleStatusGetResponses];

export type GoogleDisconnectApiIntegrationsGoogleDisconnectPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/google/disconnect';
};

export type GoogleDisconnectApiIntegrationsGoogleDisconnectPostResponses = {
    /**
     * Response Google Disconnect Api Integrations Google Disconnect Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleDisconnectApiIntegrationsGoogleDisconnectPostResponse = GoogleDisconnectApiIntegrationsGoogleDisconnectPostResponses[keyof GoogleDisconnectApiIntegrationsGoogleDisconnectPostResponses];

export type GoogleOauthStartApiIntegrationsGoogleAuthGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Propertyid
         */
        propertyId?: number | null;
        /**
         * Starturl
         */
        startUrl?: string | null;
        /**
         * Returnto
         */
        returnTo?: string | null;
    };
    url: '/api/integrations/google/auth';
};

export type GoogleOauthStartApiIntegrationsGoogleAuthGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleOauthStartApiIntegrationsGoogleAuthGetError = GoogleOauthStartApiIntegrationsGoogleAuthGetErrors[keyof GoogleOauthStartApiIntegrationsGoogleAuthGetErrors];

export type GoogleOauthStartApiIntegrationsGoogleAuthGetResponses = {
    /**
     * Response Google Oauth Start Api Integrations Google Auth Get
     *
     * Successful Response
     */
    200: unknown;
};

export type GoogleOauthCallbackApiIntegrationsGoogleCallbackGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Code
         */
        code?: string | null;
        /**
         * State
         */
        state?: string | null;
        /**
         * Error
         */
        error?: string | null;
    };
    url: '/api/integrations/google/callback';
};

export type GoogleOauthCallbackApiIntegrationsGoogleCallbackGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleOauthCallbackApiIntegrationsGoogleCallbackGetError = GoogleOauthCallbackApiIntegrationsGoogleCallbackGetErrors[keyof GoogleOauthCallbackApiIntegrationsGoogleCallbackGetErrors];

export type GoogleOauthCallbackApiIntegrationsGoogleCallbackGetResponses = {
    /**
     * Response Google Oauth Callback Api Integrations Google Callback Get
     *
     * Successful Response
     */
    200: unknown;
};

export type GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Propertyid
         */
        propertyId?: number | null;
    };
    url: '/api/integrations/google/properties';
};

export type GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetError = GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetErrors[keyof GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetErrors];

export type GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetResponses = {
    /**
     * Response Google Properties Deprecated Api Integrations Google Properties Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetResponse = GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetResponses[keyof GooglePropertiesDeprecatedApiIntegrationsGooglePropertiesGetResponses];

export type GoogleTestApiIntegrationsGoogleTestPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/google/test';
};

export type GoogleTestApiIntegrationsGoogleTestPostResponses = {
    /**
     * Response Google Test Api Integrations Google Test Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleTestApiIntegrationsGoogleTestPostResponse = GoogleTestApiIntegrationsGoogleTestPostResponses[keyof GoogleTestApiIntegrationsGoogleTestPostResponses];

export type GooglePageDataApiIntegrationsGooglePageDataGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
        /**
         * Googlesnapshotid
         */
        googleSnapshotId?: number | null;
        /**
         * Propertyid
         */
        propertyId?: string | null;
        /**
         * Domain
         */
        domain?: string | null;
    };
    url: '/api/integrations/google/page-data';
};

export type GooglePageDataApiIntegrationsGooglePageDataGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GooglePageDataApiIntegrationsGooglePageDataGetError = GooglePageDataApiIntegrationsGooglePageDataGetErrors[keyof GooglePageDataApiIntegrationsGooglePageDataGetErrors];

export type GooglePageDataApiIntegrationsGooglePageDataGetResponses = {
    /**
     * Response Google Page Data Api Integrations Google Page Data Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GooglePageDataApiIntegrationsGooglePageDataGetResponse = GooglePageDataApiIntegrationsGooglePageDataGetResponses[keyof GooglePageDataApiIntegrationsGooglePageDataGetResponses];

export type GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
        /**
         * Propertyid
         */
        propertyId?: string | null;
        /**
         * Domain
         */
        domain?: string | null;
    };
    url: '/api/integrations/google/page-data/history';
};

export type GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetError = GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetErrors[keyof GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetErrors];

export type GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetResponses = {
    /**
     * Response Google Page Data History Api Integrations Google Page Data History Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetResponse = GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetResponses[keyof GooglePageDataHistoryApiIntegrationsGooglePageDataHistoryGetResponses];

export type GooglePageLiveApiIntegrationsGooglePageLivePostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/integrations/google/page-live';
};

export type GooglePageLiveApiIntegrationsGooglePageLivePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GooglePageLiveApiIntegrationsGooglePageLivePostError = GooglePageLiveApiIntegrationsGooglePageLivePostErrors[keyof GooglePageLiveApiIntegrationsGooglePageLivePostErrors];

export type GooglePageLiveApiIntegrationsGooglePageLivePostResponses = {
    /**
     * Response Google Page Live Api Integrations Google Page Live Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GooglePageLiveApiIntegrationsGooglePageLivePostResponse = GooglePageLiveApiIntegrationsGooglePageLivePostResponses[keyof GooglePageLiveApiIntegrationsGooglePageLivePostResponses];

export type GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
        /**
         * Propertyid
         */
        propertyId?: string | null;
        /**
         * Domain
         */
        domain?: string | null;
    };
    url: '/api/integrations/google/keywords/by-page';
};

export type GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetError = GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetErrors[keyof GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetErrors];

export type GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetResponses = {
    /**
     * Response Google Keywords By Page Api Integrations Google Keywords By Page Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetResponse = GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetResponses[keyof GoogleKeywordsByPageApiIntegrationsGoogleKeywordsByPageGetResponses];

export type GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Keyword
         */
        keyword: string;
        /**
         * Propertyid
         */
        propertyId?: string | null;
        /**
         * Domain
         */
        domain?: string | null;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/integrations/google/keywords/history';
};

export type GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetError = GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetErrors[keyof GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetErrors];

export type GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetResponses = {
    /**
     * Response Google Keywords History Api Integrations Google Keywords History Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetResponse = GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetResponses[keyof GoogleKeywordsHistoryApiIntegrationsGoogleKeywordsHistoryGetResponses];

export type BingSyncApiIntegrationsBingSyncPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/integrations/bing/sync';
};

export type BingSyncApiIntegrationsBingSyncPostResponses = {
    /**
     * Response Bing Sync Api Integrations Bing Sync Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BingSyncApiIntegrationsBingSyncPostResponse = BingSyncApiIntegrationsBingSyncPostResponses[keyof BingSyncApiIntegrationsBingSyncPostResponses];

export type GooglePageCompareApiIntegrationsGooglePageCompareGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
        /**
         * Currenttype
         */
        currentType?: string;
        /**
         * Currentid
         */
        currentId: number;
        /**
         * Baselinetype
         */
        baselineType?: string;
        /**
         * Baselineid
         */
        baselineId: number;
    };
    url: '/api/integrations/google/page-compare';
};

export type GooglePageCompareApiIntegrationsGooglePageCompareGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GooglePageCompareApiIntegrationsGooglePageCompareGetError = GooglePageCompareApiIntegrationsGooglePageCompareGetErrors[keyof GooglePageCompareApiIntegrationsGooglePageCompareGetErrors];

export type GooglePageCompareApiIntegrationsGooglePageCompareGetResponses = {
    /**
     * Response Google Page Compare Api Integrations Google Page Compare Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GooglePageCompareApiIntegrationsGooglePageCompareGetResponse = GooglePageCompareApiIntegrationsGooglePageCompareGetResponses[keyof GooglePageCompareApiIntegrationsGooglePageCompareGetResponses];

export type GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Url
         */
        url: string;
        /**
         * Limit
         */
        limit?: number;
    };
    url: '/api/integrations/google/page-live/history';
};

export type GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetError = GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetErrors[keyof GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetErrors];

export type GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetResponses = {
    /**
     * Response Google Page Live History Api Integrations Google Page Live History Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetResponse = GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetResponses[keyof GooglePageLiveHistoryApiIntegrationsGooglePageLiveHistoryGetResponses];

export type GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/integrations/google/keywords/history/batch';
};

export type GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostError = GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostErrors[keyof GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostErrors];

export type GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostResponses = {
    /**
     * Response Google Keywords History Batch Api Integrations Google Keywords History Batch Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostResponse = GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostResponses[keyof GoogleKeywordsHistoryBatchApiIntegrationsGoogleKeywordsHistoryBatchPostResponses];

export type GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/integrations/google/keywords/expand';
};

export type GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostError = GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostErrors[keyof GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostErrors];

export type GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostResponses = {
    /**
     * Response Google Keywords Expand Api Integrations Google Keywords Expand Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostResponse = GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostResponses[keyof GoogleKeywordsExpandApiIntegrationsGoogleKeywordsExpandPostResponses];

export type GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostData = {
    /**
     * Body
     */
    body: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/integrations/google/keywords/planner';
};

export type GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostError = GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostErrors[keyof GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostErrors];

export type GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostResponses = {
    /**
     * Response Google Keywords Planner Api Integrations Google Keywords Planner Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostResponse = GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostResponses[keyof GoogleKeywordsPlannerApiIntegrationsGoogleKeywordsPlannerPostResponses];

export type KeywordsCompetitorImportApiKeywordsCompetitorImportPostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/keywords/competitor-import';
};

export type KeywordsCompetitorImportApiKeywordsCompetitorImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KeywordsCompetitorImportApiKeywordsCompetitorImportPostError = KeywordsCompetitorImportApiKeywordsCompetitorImportPostErrors[keyof KeywordsCompetitorImportApiKeywordsCompetitorImportPostErrors];

export type KeywordsCompetitorImportApiKeywordsCompetitorImportPostResponses = {
    /**
     * Response Keywords Competitor Import Api Keywords Competitor Import Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type KeywordsCompetitorImportApiKeywordsCompetitorImportPostResponse = KeywordsCompetitorImportApiKeywordsCompetitorImportPostResponses[keyof KeywordsCompetitorImportApiKeywordsCompetitorImportPostResponses];

export type KeywordsContentBriefApiKeywordsContentBriefPostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/keywords/content-brief';
};

export type KeywordsContentBriefApiKeywordsContentBriefPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type KeywordsContentBriefApiKeywordsContentBriefPostError = KeywordsContentBriefApiKeywordsContentBriefPostErrors[keyof KeywordsContentBriefApiKeywordsContentBriefPostErrors];

export type KeywordsContentBriefApiKeywordsContentBriefPostResponses = {
    /**
     * Response Keywords Content Brief Api Keywords Content Brief Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type KeywordsContentBriefApiKeywordsContentBriefPostResponse = KeywordsContentBriefApiKeywordsContentBriefPostResponses[keyof KeywordsContentBriefApiKeywordsContentBriefPostResponses];

export type BacklinksVelocityApiBacklinksVelocityGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Propertyid
         */
        propertyId: number;
    };
    url: '/api/backlinks/velocity';
};

export type BacklinksVelocityApiBacklinksVelocityGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BacklinksVelocityApiBacklinksVelocityGetError = BacklinksVelocityApiBacklinksVelocityGetErrors[keyof BacklinksVelocityApiBacklinksVelocityGetErrors];

export type BacklinksVelocityApiBacklinksVelocityGetResponses = {
    /**
     * Response Backlinks Velocity Api Backlinks Velocity Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BacklinksVelocityApiBacklinksVelocityGetResponse = BacklinksVelocityApiBacklinksVelocityGetResponses[keyof BacklinksVelocityApiBacklinksVelocityGetResponses];

export type BacklinksCompetitorImportApiBacklinksCompetitorImportPostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/backlinks/competitor-import';
};

export type BacklinksCompetitorImportApiBacklinksCompetitorImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BacklinksCompetitorImportApiBacklinksCompetitorImportPostError = BacklinksCompetitorImportApiBacklinksCompetitorImportPostErrors[keyof BacklinksCompetitorImportApiBacklinksCompetitorImportPostErrors];

export type BacklinksCompetitorImportApiBacklinksCompetitorImportPostResponses = {
    /**
     * Response Backlinks Competitor Import Api Backlinks Competitor Import Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BacklinksCompetitorImportApiBacklinksCompetitorImportPostResponse = BacklinksCompetitorImportApiBacklinksCompetitorImportPostResponses[keyof BacklinksCompetitorImportApiBacklinksCompetitorImportPostResponses];

export type BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/backlinks/third-party-import';
};

export type BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostError = BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostErrors[keyof BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostErrors];

export type BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostResponses = {
    /**
     * Response Backlinks Third Party Import Api Backlinks Third Party Import Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostResponse = BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostResponses[keyof BacklinksThirdPartyImportApiBacklinksThirdPartyImportPostResponses];

export type ContentAnalyzeApiContentAnalyzePostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/content/analyze';
};

export type ContentAnalyzeApiContentAnalyzePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ContentAnalyzeApiContentAnalyzePostError = ContentAnalyzeApiContentAnalyzePostErrors[keyof ContentAnalyzeApiContentAnalyzePostErrors];

export type ContentAnalyzeApiContentAnalyzePostResponses = {
    /**
     * Response Content Analyze Api Content Analyze Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContentAnalyzeApiContentAnalyzePostResponse = ContentAnalyzeApiContentAnalyzePostResponses[keyof ContentAnalyzeApiContentAnalyzePostResponses];

export type ContentScoreApiContentScorePostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/content/score';
};

export type ContentScoreApiContentScorePostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ContentScoreApiContentScorePostError = ContentScoreApiContentScorePostErrors[keyof ContentScoreApiContentScorePostErrors];

export type ContentScoreApiContentScorePostResponses = {
    /**
     * Response Content Score Api Content Score Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContentScoreApiContentScorePostResponse = ContentScoreApiContentScorePostResponses[keyof ContentScoreApiContentScorePostResponses];

export type ContentWizardApiContentWizardPostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/content/wizard';
};

export type ContentWizardApiContentWizardPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ContentWizardApiContentWizardPostError = ContentWizardApiContentWizardPostErrors[keyof ContentWizardApiContentWizardPostErrors];

export type ContentWizardApiContentWizardPostResponses = {
    /**
     * Response Content Wizard Api Content Wizard Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ContentWizardApiContentWizardPostResponse = ContentWizardApiContentWizardPostResponses[keyof ContentWizardApiContentWizardPostResponses];

export type ListContentDraftsRouteApiContentDraftsGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Propertyid
         */
        propertyId: number;
    };
    url: '/api/content-drafts';
};

export type ListContentDraftsRouteApiContentDraftsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListContentDraftsRouteApiContentDraftsGetError = ListContentDraftsRouteApiContentDraftsGetErrors[keyof ListContentDraftsRouteApiContentDraftsGetErrors];

export type ListContentDraftsRouteApiContentDraftsGetResponses = {
    /**
     * Response List Content Drafts Route Api Content Drafts Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListContentDraftsRouteApiContentDraftsGetResponse = ListContentDraftsRouteApiContentDraftsGetResponses[keyof ListContentDraftsRouteApiContentDraftsGetResponses];

export type CreateContentDraftRouteApiContentDraftsPostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/content-drafts';
};

export type CreateContentDraftRouteApiContentDraftsPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateContentDraftRouteApiContentDraftsPostError = CreateContentDraftRouteApiContentDraftsPostErrors[keyof CreateContentDraftRouteApiContentDraftsPostErrors];

export type CreateContentDraftRouteApiContentDraftsPostResponses = {
    /**
     * Response Create Content Draft Route Api Content Drafts Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type CreateContentDraftRouteApiContentDraftsPostResponse = CreateContentDraftRouteApiContentDraftsPostResponses[keyof CreateContentDraftRouteApiContentDraftsPostResponses];

export type DeleteContentDraftRouteApiContentDraftsDraftIdDeleteData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: number;
    };
    query?: never;
    url: '/api/content-drafts/{draft_id}';
};

export type DeleteContentDraftRouteApiContentDraftsDraftIdDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteContentDraftRouteApiContentDraftsDraftIdDeleteError = DeleteContentDraftRouteApiContentDraftsDraftIdDeleteErrors[keyof DeleteContentDraftRouteApiContentDraftsDraftIdDeleteErrors];

export type DeleteContentDraftRouteApiContentDraftsDraftIdDeleteResponses = {
    /**
     * Response Delete Content Draft Route Api Content Drafts  Draft Id  Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeleteContentDraftRouteApiContentDraftsDraftIdDeleteResponse = DeleteContentDraftRouteApiContentDraftsDraftIdDeleteResponses[keyof DeleteContentDraftRouteApiContentDraftsDraftIdDeleteResponses];

export type GetContentDraftRouteApiContentDraftsDraftIdGetData = {
    body?: never;
    path: {
        /**
         * Draft Id
         */
        draft_id: number;
    };
    query?: never;
    url: '/api/content-drafts/{draft_id}';
};

export type GetContentDraftRouteApiContentDraftsDraftIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContentDraftRouteApiContentDraftsDraftIdGetError = GetContentDraftRouteApiContentDraftsDraftIdGetErrors[keyof GetContentDraftRouteApiContentDraftsDraftIdGetErrors];

export type GetContentDraftRouteApiContentDraftsDraftIdGetResponses = {
    /**
     * Response Get Content Draft Route Api Content Drafts  Draft Id  Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type GetContentDraftRouteApiContentDraftsDraftIdGetResponse = GetContentDraftRouteApiContentDraftsDraftIdGetResponses[keyof GetContentDraftRouteApiContentDraftsDraftIdGetResponses];

export type UpdateContentDraftRouteApiContentDraftsDraftIdPatchData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path: {
        /**
         * Draft Id
         */
        draft_id: number;
    };
    query?: never;
    url: '/api/content-drafts/{draft_id}';
};

export type UpdateContentDraftRouteApiContentDraftsDraftIdPatchErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UpdateContentDraftRouteApiContentDraftsDraftIdPatchError = UpdateContentDraftRouteApiContentDraftsDraftIdPatchErrors[keyof UpdateContentDraftRouteApiContentDraftsDraftIdPatchErrors];

export type UpdateContentDraftRouteApiContentDraftsDraftIdPatchResponses = {
    /**
     * Response Update Content Draft Route Api Content Drafts  Draft Id  Patch
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type UpdateContentDraftRouteApiContentDraftsDraftIdPatchResponse = UpdateContentDraftRouteApiContentDraftsDraftIdPatchResponses[keyof UpdateContentDraftRouteApiContentDraftsDraftIdPatchResponses];

export type DeletePageMarkdownRouteApiPageMarkdownDeleteData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/page-markdown';
};

export type DeletePageMarkdownRouteApiPageMarkdownDeleteErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeletePageMarkdownRouteApiPageMarkdownDeleteError = DeletePageMarkdownRouteApiPageMarkdownDeleteErrors[keyof DeletePageMarkdownRouteApiPageMarkdownDeleteErrors];

export type DeletePageMarkdownRouteApiPageMarkdownDeleteResponses = {
    /**
     * Response Delete Page Markdown Route Api Page Markdown Delete
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type DeletePageMarkdownRouteApiPageMarkdownDeleteResponse = DeletePageMarkdownRouteApiPageMarkdownDeleteResponses[keyof DeletePageMarkdownRouteApiPageMarkdownDeleteResponses];

export type ListPageMarkdownRouteApiPageMarkdownGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Crawlrunid
         */
        crawlRunId: number;
        /**
         * Page
         */
        page?: number;
        /**
         * Limit
         */
        limit?: number;
        /**
         * Q
         */
        q?: string | null;
    };
    url: '/api/page-markdown';
};

export type ListPageMarkdownRouteApiPageMarkdownGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListPageMarkdownRouteApiPageMarkdownGetError = ListPageMarkdownRouteApiPageMarkdownGetErrors[keyof ListPageMarkdownRouteApiPageMarkdownGetErrors];

export type ListPageMarkdownRouteApiPageMarkdownGetResponses = {
    /**
     * Response List Page Markdown Route Api Page Markdown Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ListPageMarkdownRouteApiPageMarkdownGetResponse = ListPageMarkdownRouteApiPageMarkdownGetResponses[keyof ListPageMarkdownRouteApiPageMarkdownGetResponses];

export type PageMarkdownContentRouteApiPageMarkdownContentGetData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Crawlrunid
         */
        crawlRunId: number;
        /**
         * Url
         */
        url: string;
    };
    url: '/api/page-markdown/content';
};

export type PageMarkdownContentRouteApiPageMarkdownContentGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PageMarkdownContentRouteApiPageMarkdownContentGetError = PageMarkdownContentRouteApiPageMarkdownContentGetErrors[keyof PageMarkdownContentRouteApiPageMarkdownContentGetErrors];

export type PageMarkdownContentRouteApiPageMarkdownContentGetResponses = {
    /**
     * Response Page Markdown Content Route Api Page Markdown Content Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PageMarkdownContentRouteApiPageMarkdownContentGetResponse = PageMarkdownContentRouteApiPageMarkdownContentGetResponses[keyof PageMarkdownContentRouteApiPageMarkdownContentGetResponses];

export type PageMarkdownExtractApiPageMarkdownExtractPostData = {
    /**
     * Body
     */
    body?: {
        [key: string]: unknown;
    };
    path?: never;
    query?: never;
    url: '/api/page-markdown/extract';
};

export type PageMarkdownExtractApiPageMarkdownExtractPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PageMarkdownExtractApiPageMarkdownExtractPostError = PageMarkdownExtractApiPageMarkdownExtractPostErrors[keyof PageMarkdownExtractApiPageMarkdownExtractPostErrors];

export type PageMarkdownExtractApiPageMarkdownExtractPostResponses = {
    /**
     * Response Page Markdown Extract Api Page Markdown Extract Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PageMarkdownExtractApiPageMarkdownExtractPostResponse = PageMarkdownExtractApiPageMarkdownExtractPostResponses[keyof PageMarkdownExtractApiPageMarkdownExtractPostResponses];

export type PageMarkdownRunsRouteApiPageMarkdownRunsGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Propertyid
         */
        propertyId?: number | null;
    };
    url: '/api/page-markdown/runs';
};

export type PageMarkdownRunsRouteApiPageMarkdownRunsGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type PageMarkdownRunsRouteApiPageMarkdownRunsGetError = PageMarkdownRunsRouteApiPageMarkdownRunsGetErrors[keyof PageMarkdownRunsRouteApiPageMarkdownRunsGetErrors];

export type PageMarkdownRunsRouteApiPageMarkdownRunsGetResponses = {
    /**
     * Response Page Markdown Runs Route Api Page Markdown Runs Get
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type PageMarkdownRunsRouteApiPageMarkdownRunsGetResponse = PageMarkdownRunsRouteApiPageMarkdownRunsGetResponses[keyof PageMarkdownRunsRouteApiPageMarkdownRunsGetResponses];

export type AlertsCheckApiAlertsCheckPostData = {
    body?: never;
    path?: never;
    query: {
        /**
         * Propertyid
         */
        propertyId: number;
    };
    url: '/api/alerts/check';
};

export type AlertsCheckApiAlertsCheckPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AlertsCheckApiAlertsCheckPostError = AlertsCheckApiAlertsCheckPostErrors[keyof AlertsCheckApiAlertsCheckPostErrors];

export type AlertsCheckApiAlertsCheckPostResponses = {
    /**
     * Response Alerts Check Api Alerts Check Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type AlertsCheckApiAlertsCheckPostResponse = AlertsCheckApiAlertsCheckPostResponses[keyof AlertsCheckApiAlertsCheckPostResponses];

export type ScheduleCheckApiScheduleCheckPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/api/schedule/check';
};

export type ScheduleCheckApiScheduleCheckPostResponses = {
    /**
     * Response Schedule Check Api Schedule Check Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type ScheduleCheckApiScheduleCheckPostResponse = ScheduleCheckApiScheduleCheckPostResponses[keyof ScheduleCheckApiScheduleCheckPostResponses];

export type LogsUploadApiLogsUploadPostData = {
    body: BodyLogsUploadApiLogsUploadPost;
    path?: never;
    query?: never;
    url: '/api/logs/upload';
};

export type LogsUploadApiLogsUploadPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type LogsUploadApiLogsUploadPostError = LogsUploadApiLogsUploadPostErrors[keyof LogsUploadApiLogsUploadPostErrors];

export type LogsUploadApiLogsUploadPostResponses = {
    /**
     * Response Logs Upload Api Logs Upload Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type LogsUploadApiLogsUploadPostResponse = LogsUploadApiLogsUploadPostResponses[keyof LogsUploadApiLogsUploadPostResponses];

export type CompareExportApiCompareExportPostData = {
    body: CompareExportBody;
    path?: never;
    query?: never;
    url: '/api/compare/export';
};

export type CompareExportApiCompareExportPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CompareExportApiCompareExportPostError = CompareExportApiCompareExportPostErrors[keyof CompareExportApiCompareExportPostErrors];

export type CompareExportApiCompareExportPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RunAuditToolApiReportAuditToolPostData = {
    body: AuditToolBody;
    path?: never;
    query?: never;
    url: '/api/report/audit-tool';
};

export type RunAuditToolApiReportAuditToolPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RunAuditToolApiReportAuditToolPostError = RunAuditToolApiReportAuditToolPostErrors[keyof RunAuditToolApiReportAuditToolPostErrors];

export type RunAuditToolApiReportAuditToolPostResponses = {
    /**
     * Response Run Audit Tool Api Report Audit Tool Post
     *
     * Successful Response
     */
    200: {
        [key: string]: unknown;
    };
};

export type RunAuditToolApiReportAuditToolPostResponse = RunAuditToolApiReportAuditToolPostResponses[keyof RunAuditToolApiReportAuditToolPostResponses];
