"""Report generation: PDF, Excel, and HTML reports with templates."""
import json
import os
from datetime import datetime
from typing import Optional


BUILTIN_TEMPLATES = {
    "seo-overview": {
        "name": "SEO Overview",
        "description": "High-level SEO health, rankings, and traffic",
        "widgets": ["rankings_summary", "traffic_chart", "top_keywords", "technical_issues"],
    },
    "backlink-report": {
        "name": "Backlink Report",
        "description": "Link profile analysis and referring domains",
        "widgets": ["domain_rating", "backlinks_chart", "top_referring_domains", "anchor_text_cloud"],
    },
    "keyword-report": {
        "name": "Keyword Rankings Report",
        "description": "Tracked keyword positions and trends",
        "widgets": ["rank_changes", "visibility_score", "top_movers", "keyword_table"],
    },
    "site-audit": {
        "name": "Site Audit Report",
        "description": "Technical SEO issues and recommendations",
        "widgets": ["audit_score", "critical_issues", "warnings", "recommendations"],
    },
}

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>{{ title }}</title>
<style>
  body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; margin: 0; padding: 32px; color: #1a1a2e; background: #f8f9fa; }
  .report-header { background: linear-gradient(135deg, #667eea 0%, #764ba2 100%); color: white; padding: 32px; border-radius: 12px; margin-bottom: 32px; }
  .report-header h1 { margin: 0 0 8px; font-size: 28px; }
  .report-header p { margin: 0; opacity: 0.85; }
  .section { background: white; border-radius: 8px; padding: 24px; margin-bottom: 24px; box-shadow: 0 1px 3px rgba(0,0,0,0.1); }
  .section h2 { margin-top: 0; color: #4a5568; font-size: 18px; border-bottom: 2px solid #e2e8f0; padding-bottom: 12px; }
  table { width: 100%; border-collapse: collapse; }
  th { background: #f7fafc; color: #4a5568; font-weight: 600; padding: 10px 14px; text-align: left; font-size: 13px; border-bottom: 2px solid #e2e8f0; }
  td { padding: 10px 14px; font-size: 13px; border-bottom: 1px solid #f0f0f0; }
  tr:last-child td { border-bottom: none; }
  .metric { display: inline-block; text-align: center; padding: 16px 24px; margin: 8px; background: #f7fafc; border-radius: 8px; min-width: 100px; }
  .metric .value { font-size: 24px; font-weight: 700; color: #667eea; }
  .metric .label { font-size: 12px; color: #718096; margin-top: 4px; }
  .footer { text-align: center; color: #a0aec0; font-size: 12px; margin-top: 32px; }
</style>
</head>
<body>
<div class="report-header">
  <h1>{{ title }}</h1>
  <p>Generated {{ generated_at }} &mdash; {{ domain }}</p>
</div>
{{ content }}
<div class="footer">Generated by WebsiteProfiling &middot; {{ generated_at }}</div>
</body>
</html>"""


class ReportBuilder:
    """Build reports from DB data in various formats."""

    def build_html_report(self, db_path: str, project_id: int, template_name: str = "seo-overview",
                           title: str = None, output_path: str = None) -> str:
        """Generate an HTML report."""
        template = BUILTIN_TEMPLATES.get(template_name, BUILTIN_TEMPLATES["seo-overview"])
        title = title or template["name"]
        domain = self._get_project_domain(db_path, project_id)
        content = self._render_widgets(db_path, project_id, template["widgets"])
        now = datetime.now().strftime("%Y-%m-%d %H:%M")
        html = (HTML_TEMPLATE
                .replace("{{ title }}", title)
                .replace("{{ generated_at }}", now)
                .replace("{{ domain }}", domain)
                .replace("{{ content }}", content))
        if not output_path:
            output_path = f"report_{project_id}_{template_name}_{datetime.now().strftime('%Y%m%d_%H%M%S')}.html"
        with open(output_path, "w", encoding="utf-8") as f:
            f.write(html)
        return output_path

    def _get_project_domain(self, db_path: str, project_id: int) -> str:
        try:
            from src.db import get_connection
            conn = get_connection(db_path)
            cur = conn.execute("SELECT domain FROM projects WHERE id=?", (project_id,))
            row = cur.fetchone()
            conn.close()
            return row[0] if row else f"Project {project_id}"
        except Exception:
            return f"Project {project_id}"

    def _render_widgets(self, db_path: str, project_id: int, widgets: list) -> str:
        parts = []
        for widget in widgets:
            parts.append(self._render_widget(db_path, project_id, widget))
        return "\n".join(parts)

    def _render_widget(self, db_path: str, project_id: int, widget: str) -> str:
        try:
            from src.db import get_connection, read_rank_history, read_tracked_keywords, read_backlinks
            conn = get_connection(db_path)
            if widget == "rankings_summary":
                keywords = read_tracked_keywords(conn, project_id)
                history = read_rank_history(conn, days=7)
                top_10 = sum(1 for h in history if h.get("position", 99) <= 10)
                return self._section("Rankings Summary", f"""
                    <div class="metric"><div class="value">{len(keywords)}</div><div class="label">Tracked Keywords</div></div>
                    <div class="metric"><div class="value">{top_10}</div><div class="label">Top 10 Positions</div></div>
                """)
            elif widget == "top_keywords":
                keywords = read_tracked_keywords(conn, project_id)[:20]
                rows = "".join(f"<tr><td>{k.get('keyword','')}</td><td>{k.get('location','')}</td><td>{k.get('device','')}</td></tr>" for k in keywords)
                return self._section("Tracked Keywords", f"<table><thead><tr><th>Keyword</th><th>Location</th><th>Device</th></tr></thead><tbody>{rows}</tbody></table>")
            elif widget == "domain_rating":
                try:
                    domain = self._get_project_domain(db_path, project_id)
                    from src.db import read_domain_profile
                    profile = read_domain_profile(conn, domain)
                    dr = profile.get("domain_rating", 0)
                    return self._section("Domain Authority", f'<div class="metric"><div class="value">{dr}</div><div class="label">Domain Rating</div></div>')
                except Exception:
                    return self._section("Domain Authority", "<p>No data available</p>")
            conn.close()
        except Exception as e:
            return self._section(widget.replace("_", " ").title(), f"<p>Data unavailable: {e}</p>")
        return self._section(widget.replace("_", " ").title(), "<p>No data available</p>")

    def _section(self, title: str, content: str) -> str:
        return f'<div class="section"><h2>{title}</h2>{content}</div>'

    def build_excel_report(self, db_path: str, project_id: int, output_path: str = None) -> str:
        """Export key data to Excel workbook."""
        try:
            import openpyxl
            from openpyxl.styles import Font, PatternFill, Alignment
        except ImportError:
            raise ImportError("openpyxl is required: pip install openpyxl")

        from src.db import get_connection, read_tracked_keywords, read_rank_history, read_backlinks

        wb = openpyxl.Workbook()
        header_font = Font(bold=True, color="FFFFFF")
        header_fill = PatternFill(start_color="667EEA", end_color="667EEA", fill_type="solid")

        def make_header(ws, headers):
            ws.append(headers)
            for cell in ws[1]:
                cell.font = header_font
                cell.fill = header_fill
                cell.alignment = Alignment(horizontal="center")

        conn = get_connection(db_path)

        # Keywords sheet
        ws_kw = wb.active
        ws_kw.title = "Tracked Keywords"
        make_header(ws_kw, ["ID", "Keyword", "Location", "Device", "Language", "Tags"])
        for kw in read_tracked_keywords(conn, project_id):
            ws_kw.append([kw.get("id"), kw.get("keyword"), kw.get("location"), kw.get("device"), kw.get("language"), kw.get("tags")])

        # Rankings sheet
        ws_rank = wb.create_sheet("Rank History")
        make_header(ws_rank, ["Keyword ID", "Date", "Position", "Previous", "URL"])
        for r in read_rank_history(conn, days=30):
            ws_rank.append([r.get("tracked_keyword_id"), r.get("date"), r.get("position"), r.get("previous_position"), r.get("url")])

        conn.close()

        if not output_path:
            output_path = f"report_{project_id}_{datetime.now().strftime('%Y%m%d')}.xlsx"
        wb.save(output_path)
        return output_path

    def save_to_db(self, db_path: str, project_id: int, template_id: int, title: str, file_path: str) -> int:
        """Save generated report record to DB."""
        from src.db import get_connection, init_extended_schema
        conn = get_connection(db_path)
        init_extended_schema(conn)
        cur = conn.execute(
            "INSERT INTO generated_reports (template_id, project_id, title, file_path) VALUES (?, ?, ?, ?)",
            (template_id, project_id, title, file_path),
        )
        report_id = cur.lastrowid
        conn.commit()
        conn.close()
        return report_id


class PortfolioManager:
    """Manage multi-site portfolios."""

    def create_portfolio(self, db_path: str, name: str, urls: list, description: str = "") -> int:
        """Create a new portfolio."""
        from src.db import get_connection, write_portfolio
        conn = get_connection(db_path)
        pid = write_portfolio(conn, {"name": name, "description": description, "urls": urls})
        conn.close()
        return pid

    def list_portfolios(self, db_path: str) -> list:
        """List all portfolios."""
        from src.db import get_connection, read_portfolios
        conn = get_connection(db_path)
        portfolios = read_portfolios(conn)
        conn.close()
        return portfolios

    def portfolio_health_score(self, db_path: str, portfolio_id: int) -> dict:
        """Compute aggregate health score for a portfolio."""
        from src.db import get_connection, read_portfolios
        conn = get_connection(db_path)
        portfolios = read_portfolios(conn)
        conn.close()
        portfolio = next((p for p in portfolios if p["id"] == portfolio_id), None)
        if not portfolio:
            return {"error": f"Portfolio {portfolio_id} not found"}
        urls = portfolio.get("urls", [])
        return {
            "portfolio_id": portfolio_id,
            "name": portfolio.get("name"),
            "sites": len(urls),
            "health_score": 0,
            "note": "Run crawl on each site to compute health scores",
        }


def cmd_html(db_path: str, project_id: int, template: str, output: str = None):
    builder = ReportBuilder()
    print(f"Building HTML report (template={template})...")
    path = builder.build_html_report(db_path, project_id, template, output_path=output)
    print(f"Report saved: {path}")


def cmd_excel(db_path: str, project_id: int, output: str = None):
    builder = ReportBuilder()
    print("Building Excel report...")
    path = builder.build_excel_report(db_path, project_id, output)
    print(f"Excel report saved: {path}")


def cmd_portfolio_create(db_path: str, name: str, urls_file: str):
    with open(urls_file) as f:
        urls = [line.strip() for line in f if line.strip()]
    manager = PortfolioManager()
    pid = manager.create_portfolio(db_path, name, urls)
    print(f"Portfolio '{name}' created (id={pid}) with {len(urls)} sites")


def cmd_portfolio_list(db_path: str):
    manager = PortfolioManager()
    portfolios = manager.list_portfolios(db_path)
    print(f"Portfolios: {len(portfolios)}")
    for p in portfolios:
        urls = p.get("urls", [])
        print(f"  id={p['id']}  {p['name']}  ({len(urls)} sites)")


def cmd_templates():
    print("Available report templates:")
    for key, tmpl in BUILTIN_TEMPLATES.items():
        print(f"  {key:<20} - {tmpl['description']}")


def main(args=None):
    import argparse
    from dotenv import load_dotenv
    load_dotenv()

    parser = argparse.ArgumentParser(description="Report Builder")
    sub = parser.add_subparsers(dest="cmd")

    html_p = sub.add_parser("html", help="Generate HTML report")
    html_p.add_argument("--project-id", type=int, default=1)
    html_p.add_argument("--template", default="seo-overview")
    html_p.add_argument("--output", default=None)

    xl_p = sub.add_parser("excel", help="Generate Excel report")
    xl_p.add_argument("--project-id", type=int, default=1)
    xl_p.add_argument("--output", default=None)

    pc_p = sub.add_parser("portfolio-create", help="Create a multi-site portfolio")
    pc_p.add_argument("--name", required=True)
    pc_p.add_argument("--urls-file", required=True)

    sub.add_parser("portfolio-list", help="List portfolios")
    sub.add_parser("templates", help="List available report templates")

    parsed = parser.parse_args(args)
    db = os.getenv("DB_PATH", "report.db")

    if parsed.cmd == "html":
        cmd_html(db, parsed.project_id, parsed.template, parsed.output)
    elif parsed.cmd == "excel":
        cmd_excel(db, parsed.project_id, parsed.output)
    elif parsed.cmd == "portfolio-create":
        cmd_portfolio_create(db, parsed.name, parsed.urls_file)
    elif parsed.cmd == "portfolio-list":
        cmd_portfolio_list(db)
    elif parsed.cmd == "templates":
        cmd_templates()
    else:
        parser.print_help()
