/** @type {import('tailwindcss').Config} */
export default {
  content: [
    './app/**/*.{js,jsx,ts,tsx}',
    './src/**/*.{js,jsx,ts,tsx}',
  ],
  theme: {
    extend: {
      fontFamily: {
        sans: ['var(--font-dm-sans)', 'DM Sans', 'system-ui', 'sans-serif'],
      },
      colors: {
        'md-sys': {
          primary: 'var(--md-sys-color-primary)',
          'on-primary': 'var(--md-sys-color-on-primary)',
          'primary-container': 'var(--md-sys-color-primary-container)',
          'on-primary-container': 'var(--md-sys-color-on-primary-container)',
          secondary: 'var(--md-sys-color-secondary)',
          'on-secondary': 'var(--md-sys-color-on-secondary)',
          'secondary-container': 'var(--md-sys-color-secondary-container)',
          'on-secondary-container': 'var(--md-sys-color-on-secondary-container)',
          tertiary: 'var(--md-sys-color-tertiary)',
          'on-tertiary': 'var(--md-sys-color-on-tertiary)',
          'tertiary-container': 'var(--md-sys-color-tertiary-container)',
          'on-tertiary-container': 'var(--md-sys-color-on-tertiary-container)',
          error: 'var(--md-sys-color-error)',
          'on-error': 'var(--md-sys-color-on-error)',
          'error-container': 'var(--md-sys-color-error-container)',
          'on-error-container': 'var(--md-sys-color-on-error-container)',
          success: 'var(--md-sys-color-success)',
          'on-success': 'var(--md-sys-color-on-success)',
          'success-container': 'var(--md-sys-color-success-container)',
          'on-success-container': 'var(--md-sys-color-on-success-container)',
          warning: 'var(--md-sys-color-warning)',
          'on-warning': 'var(--md-sys-color-on-warning)',
          'warning-container': 'var(--md-sys-color-warning-container)',
          'on-warning-container': 'var(--md-sys-color-on-warning-container)',
          info: 'var(--md-sys-color-info)',
          'on-info': 'var(--md-sys-color-on-info)',
          'info-container': 'var(--md-sys-color-info-container)',
          'on-info-container': 'var(--md-sys-color-on-info-container)',
          surface: 'var(--md-sys-color-surface)',
          'on-surface': 'var(--md-sys-color-on-surface)',
          'surface-dim': 'var(--md-sys-color-surface-dim)',
          'surface-bright': 'var(--md-sys-color-surface-bright)',
          'surface-container-lowest': 'var(--md-sys-color-surface-container-lowest)',
          'surface-container-low': 'var(--md-sys-color-surface-container-low)',
          'surface-container': 'var(--md-sys-color-surface-container)',
          'surface-container-high': 'var(--md-sys-color-surface-container-high)',
          'surface-container-highest': 'var(--md-sys-color-surface-container-highest)',
          'surface-variant': 'var(--md-sys-color-surface-variant)',
          'on-surface-variant': 'var(--md-sys-color-on-surface-variant)',
          outline: 'var(--md-sys-color-outline)',
          'outline-variant': 'var(--md-sys-color-outline-variant)',
        },
      },
      borderRadius: {
        'm3-full': '9999px',
        'm3-card': '1rem',
        'm3-modal': '1.75rem',
      },
      spacing: {
        'page-x': '1.5rem',
        'page-y': '1.5rem',
        card: '1.25rem',
      },
    },
  },
  plugins: [],
};
